//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Particles_Billboard_AN_Vd_VtxAtm_Soft_ProjPos.vso
//
//
// Parameters:
//
//   float4 g__cameraPos;
//   float4 g__cameraRight;
//   float4 g__cameraUp;
//   float4 g__scatteringBeta1PlusBeta2;
//   float4 g__scatteringBetaDash1;
//   float4 g__scatteringBetaDash2;
//   float4 g__scatteringConstant;
//   float4 g__scatteringExtinctionColor;
//   float4 g__scatteringHG;
//   float4 g__scatteringInscatteringColor;
//   float4 g__scatteringMultiplier;
//   float4 g__scatteringOneOverBeta1PlusBeta2;
//   float4 g__sunCol;
//   float4 g__sunDir;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                               Reg   Size
//   ---------------------------------- ----- ----
//   g__worldMatrix                     c178     4
//   g__scatteringInscatteringColor     c198     1
//   g__scatteringExtinctionColor       c199     1
//   g__scatteringConstant              c200     1
//   g__scatteringOneOverBeta1PlusBeta2 c201     1
//   g__scatteringBeta1PlusBeta2        c202     1
//   g__scatteringBetaDash1             c203     1
//   g__scatteringBetaDash2             c204     1
//   g__scatteringHG                    c205     1
//   g__scatteringMultiplier            c206     1
//   g__viewProjMatrix                  c239     4
//   g__cameraRight                     c243     1
//   g__cameraUp                        c244     1
//   g__cameraPos                       c245     1
//   g__sunCol                          c250     1
//   g__sunDir                          c251     1
//

    vs_3_0
    def c252, 1, -1, 0.159154937, 0.5
    def c253, -1, -1, 6.28318548, -3.14159274
    def c254, -1, 1, 0, 1.44269502
    def c255, 1, 1, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_color v1  // IN<4,5,6,7>
    dcl_texcoord v2  // IN<8,9,10>
    dcl_texcoord1 v3  // IN<11,12,13,14>
    dcl_texcoord2 v4  // IN<15>
    dcl_texcoord3 v5  // IN<16,17>
    dcl_texcoord4 v6  // IN<18,19>
    dcl_texcoord5 v7  // IN<20>
    dcl_texcoord6 v8  // IN<21>
    dcl_position o0
    dcl_color o1
    dcl_color1 o2
    dcl_texcoord o3.xyz
    dcl_texcoord1 o4.xy
    dcl_texcoord4 o5.xyz
    dcl_texcoord5 o6.x
    dcl_texcoord6 o7.xy
    dcl_texcoord9 o8

#line 363 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Particles_Billboard_AN_Vd_VtxAtm_Soft_ProjPos.final"
    mad r0.x, v2.x, c252.z, c252.w
    frc r0.x, r0.x
    mad r0.x, r0.x, c253.z, c253.w
    sincos r1.xy, r0.x  // ::cosX<0>, ::sinX<0>

#line 360
    mov r0.xyz, c243  // ::g__cameraRight<0,1,2>
    mul r2.xyz, r0.yzxw, c244.zxyw
    mad r0.xyz, c244.yzxw, r0.zxyw, -r2
    nrm r2.xyz, r0  // ::look<0,1,2>

#line 371
    mul r0.xyz, r1.y, r2.zxyw  // ::sz<0>, ::sx<0>, ::sy<0>

#line 364
    add r0.w, -r1.x, c252.x  // ::t<0>
    mul r3, r2.yxxx, r0.w  // ::ty<0>, ::tx<0,0,0>

#line 379
    mad r1.yzw, r3.xwyx, r2.xyzz, r0.xxzy  // ::rotateLook<1,6,5>
    mad r0.xyz, r3.ywxw, r2.zyzw, -r0.zxyw  // ::rotateLook<2,3,7>
    mov r4.x, r1.z
    mov r4.y, r0.z
    mul r0.z, r2.z, r2.z
    lrp r4.z, r0.z, c252.x, r1.x  // ::rotateLook<8>
    dp3 r5.z, r4, -c243  // ::right<2>

#line 373
    mad r6.x, r3.z, r2.x, r1.x  // ::rotateLook<0>

#line 377
    mad r1.z, r3.x, r2.y, r1.x  // ::rotateLook<4>

#line 382
    mov r6.y, r1.y
    mov r6.z, r0.x
    mov r1.y, r0.y
    dp3 r5.x, r6, -c243  // ::right<0>
    dp3 r5.y, r1.yzww, -c243  // ::right<1>

#line 397
    dp3 o5.x, c251, r5  // ::main<17>

#line 383
    mul r0.xyz, r2.zxyw, r5.yzxw
    mad r0.xyz, r2.yzxw, r5.zxyw, -r0

#line 397
    dp3 o5.z, c251, r2  // ::main<19>

#line 383
    nrm r2.xyz, r0  // ::up<0,1,2>

#line 397
    dp3 o5.y, c251, r2  // ::main<18>

#line 185
    slt r0.x, v4.x, -v4.x
    frc r0.y, v4.x
    add r0.z, -r0.y, v4.x
    slt r0.y, -r0.y, r0.y
    mad r0.x, r0.x, r0.y, r0.z  // ::g__index<0>

#line 128
    mova a0.x, r0.x

#line 385
    mul r0.xy, v5.yxzw, c252[a0.x].yxzw
    mul r0.xzw, r0.x, c244.xyyz
    mad r0.xyz, c243, r0.y, r0.xzww  // ::pos<0,1,2>

#line 388
    mad r0.xyz, c243, v6.x, r0  // ::pos<0,1,2>
    mad r0.xyz, c244, v6.y, r0  // ::pos<0,1,2>
    dp3 r2.x, r6, r0  // ::pos<0>
    dp3 r2.y, r1.yzww, r0  // ::pos<1>
    dp3 r2.z, r4, r0  // ::pos<2>
    mad r0.xyz, c243, -v6.x, r2  // ::pos<0,1,2>
    mad r0.xyz, c244, -v6.y, r0  // ::pos<0,1,2>

#line 356
    mul r1, c179, v0.y
    mad r1, v0.x, c178, r1
    mad r1, v0.z, c180, r1
    add r1, r1, c181  // ::g__worldPos<0,1,2,3>

#line 393
    add r0.xyz, r0, r1  // ::g__worldPos<0,1,2>

#line 275
    add r1.xyz, -r0, c245  // ::viewVec<0,1,2>
    dp3 r0.w, r1, r1
    rsq r2.x, r0.w

#line 406
    mul r0.w, r0.w, c252.w  // ::fade<0>
    mul r0.w, r0.w, r0.w  // ::fade<0>
    mul r0.w, r0.w, r0.w  // ::fade<0>
    min o7.y, r0.w, c252.x  // ::main<22>

#line 277
    mul r1.xyz, r1, r2.x  // ::viewVec<0,1,2>
    rcp r0.w, r2.x  // ::s<0>
    mul r0.w, r0.w, c199.w  // ::s<0>
    dp3 r1.x, r1, c251
    min r1.x, r1.x, c254.z  // ::cosTheta<0>

#line 285
    mad r1.y, c205.z, r1.x, c205.y

#line 280
    mad r1.x, r1.x, r1.x, c252.x  // ::phase1Theta<0>

#line 285
    rsq r1.z, r1.y  // ::phase2Theta<0>
    rcp r1.y, r1.y
    mul r1.y, r1.z, r1.y
    mul r1.y, r1.y, c205.x  // ::phase2Theta<0>
    mul r2.xyz, r1.y, c204
    mad r1.xyz, c203, r1.x, r2  // calculateScattering::inscattering<0,1,2>

#line 260
    min r2.w, r0.y, c245.y  // ::r11<1>
    max r2.z, r0.y, c245.y  // ::r11<0>

#line 262
    mul r3, r2.zwzw, c200.yyww  // ::r11<0,1,2,3>
    mad r2.xy, r2.z, c200.ywzw, -r3.ywzw  // ::r11<0,1>
    min r3, r3, c252.x  // ::r10<0,1,2,3>
    add r2.zw, -r3.xyyw, r3.xyxz  // ::r11<2,3>

#line 270
    add r3.xy, r3.xzzw, r3.ywzw  // ::r10<1,3>
    mad r3.xy, r3, -c252.w, c252.x  // ::r10<1,3>

#line 266
    max r2, r2, c200.y  // ::r11<0,1,2,3>
    rcp r4.x, r2.x  // ::r11<0>
    rcp r4.y, r2.y  // ::r11<1>
    mul r2.xy, r2.zwzw, r4  // ::r11<0,1>

#line 273
    mul r2.xy, r3, r2
    mul r2.xy, r2, c200.xzzw  // ::atmosphereDensity<0>, ::hazeDensity<0>
    add r2.x, r2.y, r2.x  // ::density<0>

#line 281
    mul r2.xyz, r2.x, -c202
    mul r2.xyz, r0.w, r2
    mul r2.xyz, r2, c254.w  // calculateScattering::extinction<0,1,2>
    exp r3.x, r2.x  // calculateScattering::extinction<0>
    exp r3.y, r2.y  // calculateScattering::extinction<1>
    exp r3.z, r2.z  // calculateScattering::extinction<2>

#line 288
    add r2.xyz, -r3, c252.x
    mul r3.xyz, r3, c206.x  // calculateScattering::extinction<0,1,2>
    mul r3.xyz, r3, c199  // calculateScattering::extinction<0,1,2>

#line 402
    mul r3.xyz, r3, v1
    mul o1.xyz, r3, v2.z  // ::main<4,5,6>

#line 288
    mul r1.xyz, r1, r2  // calculateScattering::inscattering<0,1,2>
    mul r1.xyz, r1, c201  // calculateScattering::inscattering<0,1,2>

#line 292
    mov r2.y, c206.y  // ::g__scatteringMultiplier<1>
    mul r2.xyz, r2.y, c250
    mul r2.xyz, r2, c198
    mul o2.xyz, r1, r2  // ::main<8,9,10>

#line 394
    mul r2, r0.y, c240
    mad r2, r0.x, c239, r2
    mad r0, r0.z, c241, r2
    mad r0, r1.w, c242, r0  // ::OUT<0,1,2,3>
    mov o0, r0  // ::main<0,1,2,3>
    mov o8, r0  // ::main<23,24,25,26>

#line 402
    mov o1.w, v1.w  // ::main<7>

#line 292
    mov o2.w, c252.x  // ::main<11>

#line 423
    mov o3.xy, v3  // ::main<12,13>
    mov o3.z, v2.y  // ::main<14>
    mov o4.xy, v3.zwzw  // ::main<15,16>
    mov o6.x, v7.x  // ::main<20>
    mov o7.x, v8.x  // ::main<21>

// approximately 128 instruction slots used
