//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_skinned_ADN_Dn_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float3x4 g__matrixPalette[59];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm2;
//   row_major float2x4 g__texXfm4;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      3
//   g__matrixPalette         c0     177
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__texXfm2               c186     2
//   g__texXfm4               c190     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    12
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c177, 2, -1, 1, 0
    def c188, 3, 0.00999999978, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_blendweight v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,7,8,9>
    dcl_normal v3  // IN<10,11,12>
    dcl_texcoord v4  // IN<13,14>
    dcl_texcoord1 v5  // IN<15,16>
    dcl_texcoord2 v6  // IN<17,18>
    dcl_texcoord4 v7  // IN<19,20>
    dcl_tangent v8  // IN<21,22,23,24>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord3 o6
    dcl_texcoord4 o7
    dcl_texcoord5 o8
    dcl_texcoord6 o9

#line 170 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_skinned_ADN_Dn_VtxAtm_WPos_VNorm_8DL.final"
    mad r0.xyz, v3, c177.x, c177.y  // ::g__vertexNormal<0,1,2>
    frc r1, v2
    add r2, -r1, v2
    slt r3, v2, -v2
    slt r1, -r1, r1
    mad r1, r3, r1, r2  // ::g__indices<0,1,2,3>

#line 132
    mad r2.xyz, v4.xyxw, c177.zzww, c177.wwzw
    dp3 o7.x, c182, r2  // ::main<27>
    dp3 o7.y, c183, r2  // ::main<28>
    mad r2.xyz, v5.xyxw, c177.zzww, c177.wwzw
    dp3 o7.z, c184, r2  // ::main<29>
    dp3 o7.w, c185, r2  // ::main<30>
    mad r2.xyz, v6.xyxw, c177.zzww, c177.wwzw
    dp3 o8.x, c186, r2  // ::main<31>
    dp3 o8.y, c187, r2  // ::main<32>
    mad r2.xyz, v7.xyxw, c177.zzww, c177.wwzw
    dp3 o9.x, c190, r2  // ::main<35>
    dp3 o9.y, c191, r2  // ::main<36>

#line 194
    mad r2, v8, c177.x, c177.y  // ::g__vertexTangent<0,1,2,3>
    nrm r3.xyz, r2  // ::g__vertexTangent<0,1,2>
    mul r2.xyz, r0.zxyw, r3.yzxw
    mad r2.xyz, r0.yzxw, r3.zxyw, -r2
    mul r2.xyz, r2.w, r2  // ::g__vertexBinormal<0,1,2>

#line 208
    add r0.w, c177.z, -v1.x
    add r0.w, r0.w, -v1.y
    add r0.w, r0.w, -v1.z  // ::w<3>

#line 213
    mul r1, r1, c188.x
    mova a0, r1
    mul r1, v1.y, c0[a0.y]
    mul r4, v1.y, c1[a0.y]
    mul r5, v1.y, c2[a0.y]
    mad r1, c0[a0.x], v1.x, r1  // ::skinMatrix<0,1,2,3>
    mad r4, c1[a0.x], v1.x, r4  // ::skinMatrix<4,5,6,7>
    mad r5, c2[a0.x], v1.x, r5  // ::skinMatrix<8,9,10,11>
    mad r1, c0[a0.z], v1.z, r1  // ::skinMatrix<0,1,2,3>
    mad r4, c1[a0.z], v1.z, r4  // ::skinMatrix<4,5,6,7>
    mad r5, c2[a0.z], v1.z, r5  // ::skinMatrix<8,9,10,11>
    mad r1, c0[a0.w], r0.w, r1  // ::skinMatrix<0,1,2,3>
    mad r4, c1[a0.w], r0.w, r4  // ::skinMatrix<4,5,6,7>
    mad r5, c2[a0.w], r0.w, r5  // ::skinMatrix<8,9,10,11>

#line 354
    mad r6, v0.xyzx, c177.zzzw, c177.wwwz
    dp4 r0.w, r6, r1  // ::localPos<0>
    dp4 r1.w, r6, r4  // ::localPos<1>
    dp4 r2.w, r6, r5  // ::localPos<2>
    dp3 r3.w, r0, r1  // ::g__worldNormal<0>
    dp3 r4.w, r0, r4  // ::g__worldNormal<1>
    dp3 r0.x, r0, r5  // ::g__worldNormal<2>
    mul r6, r1.w, c179
    mad r6, r0.w, c178, r6
    mad r6, r2.w, c180, r6
    add r6, r6, c181  // ::g__worldPos<0,1,2,3>
    mul r0.yzw, r4.w, c179.xxyz
    mad r0.yzw, r3.w, c178.xxyz, r0
    mad r0.xyz, r0.x, c180, r0.yzww  // ::g__worldNormal<0,1,2>
    mul r7, r6.y, c240
    mad r7, r6.x, c239, r7
    mad r7, r6.z, c241, r7
    mad o0, r6.w, c242, r7  // ::main<0,1,2,3>

#line 247
    add r7.xyz, -r6, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r7, r7
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r7.xyz, r7, r0.w  // ::lightVec<0,1,2>

#line 255
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c188.y  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r8.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 306
    dp3_sat r0.w, r0, r7  // calcLambert::Qd<0>

#line 332
    mul r7.xyz, r8.zxyw, r0.w  // ::Ir<2,0,1>
    if b13

#line 247
      add r8.xyz, -r6, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r8, r8
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r8.xyz, r8, r0.w  // ::lightVec<0,1,2>

#line 255
      add r0.w, r1.w, -c212.x
      max r0.w, r0.w, c188.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c212.w
      mad r0.w, r0.w, c212.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r9.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 306
      dp3_sat r0.w, r0, r8  // calcLambert::Qd<0>

#line 337
      mad r7.xyz, r0.w, r9.zxyw, r7  // ::Ir<2,0,1>

#line 333
    endif

#line 339
    if b14

#line 247
      add r8.xyz, -r6, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r8, r8
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r8.xyz, r8, r0.w  // ::lightVec<0,1,2>

#line 255
      add r0.w, r1.w, -c215.x
      max r0.w, r0.w, c188.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c215.w
      mad r0.w, r0.w, c215.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r9.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 306
      dp3_sat r0.w, r0, r8  // calcLambert::Qd<0>

#line 343
      mad r8.xyz, r0.w, r9, r7.yzxw  // ::Ir<0,1,2>

#line 247
      add r9.xyz, -r6, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r9, r9
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r9.xyz, r9, r0.w  // ::lightVec<0,1,2>

#line 255
      add r0.w, r1.w, -c218.x
      max r0.w, r0.w, c188.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c218.w
      mad r0.w, r0.w, c218.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r10.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 306
      dp3_sat r0.w, r0, r9  // calcLambert::Qd<0>

#line 346
      mad r7.xyz, r0.w, r10.zxyw, r8.zxyw  // ::Ir<2,0,1>

#line 339
      mov r8.x, r7.y  // ::Ir<0>
      mov r9.x, r7.z  // ::Ir<1>
    else
      mov r8.x, r7.y  // ::Ir<0>
      mov r9.x, r7.z  // ::Ir<1>
    endif

#line 373
    dp3 r0.w, r3, r1  // ::worldTangent<0>
    dp3 r1.w, r3, r4  // ::worldTangent<1>
    dp3 r2.w, r3, r5  // ::worldTangent<2>
    dp3 r1.x, r2, r1  // ::worldBinormal<0>
    dp3 r1.y, r2, r4  // ::worldBinormal<1>
    dp3 r1.z, r2, r5  // ::worldBinormal<2>
    mul r2.xyz, r1.w, c179
    mad r2.xyz, r0.w, c178, r2
    mad r2.xyz, r2.w, c180, r2  // ::worldTangent<0,1,2>
    mul r3.xyz, r1.y, c179
    mad r1.xyw, r1.x, c178.xyzz, r3.xyzz
    mad r1.xyz, r1.z, c180, r1.xyww  // ::worldBinormal<0,1,2>

#line 173
    mov o1, c197  // ::main<4,5,6,7>

#line 357
    mov o2.xyz, r0  // ::main<8,9,10>
    mov o3, r6  // ::main<11,12,13,14>

#line 375
    mov r8.y, r2.x
    mov r8.z, r1.x
    mov r8.w, r0.x
    mov o4, r8.yzwx  // ::main<15,16,17,18>
    mov r9.y, r2.y
    mov r9.z, r1.y
    mov r9.w, r0.y
    mov o5, r9.yzwx  // ::main<19,20,21,22>
    mov r7.y, r2.z
    mov r7.z, r1.z
    mov r7.w, r0.z
    mov o6, r7.yzwx  // ::main<23,24,25,26>

#line 132
    mov o8.zw, c177.w  // ::main<33,34>
    mov o9.zw, c177.w  // ::main<37,38>

// approximately 158 instruction slots used
