//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_skinned_Morphable_ADS_Vd_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float3x4 g__matrixPalette[59];
//   row_major float2x4 g__morphing;
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm3;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      3
//   g__matrixPalette         c0     177
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__texXfm3               c188     2
//   g__morphing              c194     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    12
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c177, 2, -1, 1, 0
    def c186, 3, 0.00999999978, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_blendweight v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,7,8,9>
    dcl_normal v3  // IN<10,11,12>
    dcl_color v4  // IN<13,14,15,16>
    dcl_position1 v5  // IN<17,18,19>
    dcl_normal1 v6  // IN<20,21,22>
    dcl_color2 v7  // IN<23,24,25,26>
    dcl_texcoord v8  // IN<27,28>
    dcl_texcoord1 v9  // IN<29,30>
    dcl_texcoord2 v10  // IN<31,32>
    dcl_texcoord3 v11  // IN<33,34>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord4 o6

#line 169 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_skinned_Morphable_ADS_Vd_VtxAtm_WPos_VNorm_8DL.final"
    mov r0.xyz, v0  // IN<0,1,2>
    add r0.xyz, -r0, v5
    mad r0.xyz, c195.w, r0, v0  // ::g__vertexPos<0,1,2>
    mad r1.xyz, v3, c177.x, c177.y
    mad r2.xyz, v6, c177.x, c177.y
    lrp r3.xyz, c195.w, r2, r1  // ::g__vertexNormal<0,1,2>
    frc r1, v2
    add r2, -r1, v2
    slt r4, v2, -v2
    slt r1, -r1, r1
    mad r1, r4, r1, r2  // ::g__indices<0,1,2,3>
    mov r2, v4  // IN<13,14,15,16>
    add r2, -r2, v7
    mad r2, c195.w, r2, v4
    mul o1, r2, c197  // ::main<4,5,6,7>

#line 195
    mov r2.z, c177.z
    add r2.xyz, r2.z, -c194.xyww

#line 184
    mul r4, r2.xxyy, v8.xyxy
    mad r4, c194.xxyy, v9.xyxy, r4  // ::albedoMapUVStart<0,1>, ::detailMapUVStart<0,1>
    mul r5, r2.xxyy, v10.xyxy
    mad r5, c194.xxyy, v11.xyxy, r5  // ::albedoMapUVEnd<0,1>, ::detailMapUVEnd<0,1>
    lrp r6, c195.w, r5, r4  // ::albedoMapUV<0,1>, ::detailMapUV<0,1>

#line 132
    mad r2.xyw, r6.xyzx, c177.zzzw, c177.wwzz
    dp3 o4.x, c182, r2.xyww  // ::main<15>
    dp3 o4.y, c183, r2.xyww  // ::main<16>
    mad r2.xyw, r6.zwzx, c177.zzzw, c177.wwzz
    dp3 o4.z, c184, r2.xyww  // ::main<17>
    dp3 o4.w, c185, r2.xyww  // ::main<18>

#line 195
    mul r2.xy, r2.z, v8
    mad r2.xy, c194.w, v9, r2  // ::specMapUVStart<0,1>
    mul r2.zw, r2.z, v10.xyxy
    mad r2.zw, c194.w, v11.xyxy, r2  // ::specMapUVEnd<0,1>
    lrp r4.xy, c195.w, r2.zwzw, r2  // ::specMapUV<0,1>

#line 132
    mov r4.z, c177.z
    dp3 o5.z, c188, r4  // ::main<21>
    dp3 o5.w, c189, r4  // ::main<22>

#line 215
    add r2.x, c177.z, -v1.x
    add r2.x, r2.x, -v1.y
    add r2.x, r2.x, -v1.z  // ::w<3>

#line 220
    mul r1, r1, c186.x
    mova a0, r1
    mul r1, v1.y, c0[a0.y]
    mul r4, v1.y, c1[a0.y]
    mul r5, v1.y, c2[a0.y]
    mad r1, c0[a0.x], v1.x, r1  // ::skinMatrix<0,1,2,3>
    mad r4, c1[a0.x], v1.x, r4  // ::skinMatrix<4,5,6,7>
    mad r5, c2[a0.x], v1.x, r5  // ::skinMatrix<8,9,10,11>
    mad r1, c0[a0.z], v1.z, r1  // ::skinMatrix<0,1,2,3>
    mad r4, c1[a0.z], v1.z, r4  // ::skinMatrix<4,5,6,7>
    mad r5, c2[a0.z], v1.z, r5  // ::skinMatrix<8,9,10,11>
    mad r1, c0[a0.w], r2.x, r1  // ::skinMatrix<0,1,2,3>
    mad r4, c1[a0.w], r2.x, r4  // ::skinMatrix<4,5,6,7>
    mad r2, c2[a0.w], r2.x, r5  // ::skinMatrix<8,9,10,11>

#line 361
    mov r0.w, c177.z
    dp4 r1.w, r0, r1  // ::localPos<0>
    dp4 r3.w, r0, r4  // ::localPos<1>
    dp4 r0.x, r0, r2  // ::localPos<2>
    dp3 r0.y, r3, r1  // ::g__worldNormal<0>
    dp3 r0.z, r3, r4  // ::g__worldNormal<1>
    dp3 r0.w, r3, r2  // ::g__worldNormal<2>
    mul r2, r3.w, c179
    mad r1, r1.w, c178, r2
    mad r1, r0.x, c180, r1
    add r1, r1, c181  // ::g__worldPos<0,1,2,3>
    mul r2.xyz, r0.z, c179
    mad r0.xyz, r0.y, c178, r2
    mad r0.xyz, r0.w, c180, r0  // ::g__worldNormal<0,1,2>
    mul r2, r1.y, c240
    mad r2, r1.x, c239, r2
    mad r2, r1.z, c241, r2
    mad o0, r1.w, c242, r2  // ::main<0,1,2,3>

#line 254
    add r2.xyz, -r1, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r2, r2
    rsq r0.w, r0.w
    rcp r2.w, r0.w  // ::lightVecLen<0>
    mul r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 262
    add r0.w, r2.w, -c209.x
    max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
    mul r2.w, r0.w, r0.w
    mul r2.w, r2.w, c209.w
    mad r0.w, r0.w, c209.z, r2.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r3.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 313
    dp3_sat r0.w, r0, r2  // calcLambert::Qd<0>

#line 339
    mul r2.xyz, r3, r0.w  // ::Ir<0,1,2>
    if b13

#line 254
      add r3.xyz, -r1, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r3.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 262
      add r0.w, r3.w, -c212.x
      max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
      mul r3.w, r0.w, r0.w
      mul r3.w, r3.w, c212.w
      mad r0.w, r0.w, c212.z, r3.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 313
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 344
      mad r2.xyz, r0.w, r4, r2  // ::Ir<0,1,2>

#line 340
    endif

#line 346
    if b14

#line 254
      add r3.xyz, -r1, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r3.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 262
      add r0.w, r3.w, -c215.x
      max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
      mul r3.w, r0.w, r0.w
      mul r3.w, r3.w, c215.w
      mad r0.w, r0.w, c215.z, r3.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 313
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 350
      mad r3.xyz, r0.w, r4, r2  // ::Ir<0,1,2>

#line 254
      add r4.xyz, -r1, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r3.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 262
      add r0.w, r3.w, -c218.x
      max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
      mul r3.w, r0.w, r0.w
      mul r3.w, r3.w, c218.w
      mad r0.w, r0.w, c218.z, r3.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 313
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 353
      mad r2.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 346
    endif

#line 364
    mov o2.xyz, r0  // ::main<8,9,10>
    mov o3, r1  // ::main<11,12,13,14>

#line 373
    mov o5.xy, c177.w  // ::main<19,20>

#line 346
    mov r2.w, c177.z
    mov o6, r2  // ::main<23,24,25,26>

// approximately 140 instruction slots used
