//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_skinned_AD_Ao_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float3x4 g__matrixPalette[59];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      3
//   g__matrixPalette         c0     177
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    12
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c177, 2, -1, 1, 0
    def c186, 3, 0.00999999978, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_blendweight v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,7,8,9>
    dcl_normal v3  // IN<10,11,12>
    dcl_color1 v4  // IN<13>
    dcl_texcoord v5  // IN<17,18>
    dcl_texcoord1 v6  // IN<19,20>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord4 o5

#line 164 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_skinned_AD_Ao_VtxAtm_WPos_VNorm_8DL.final"
    mad r0.xyz, v3, c177.x, c177.y  // ::g__vertexNormal<0,1,2>
    frc r1, v2
    add r2, -r1, v2
    slt r3, v2, -v2
    slt r1, -r1, r1
    mad r1, r3, r1, r2  // ::g__indices<0,1,2,3>

#line 132
    mad r2.xyz, v5.xyxw, c177.zzww, c177.wwzw
    dp3 o4.x, c182, r2  // ::main<16>
    dp3 o4.y, c183, r2  // ::main<17>
    mad r2.xyz, v6.xyxw, c177.zzww, c177.wwzw
    dp3 o4.z, c184, r2  // ::main<18>
    dp3 o4.w, c185, r2  // ::main<19>

#line 200
    add r0.w, c177.z, -v1.x
    add r0.w, r0.w, -v1.y
    add r0.w, r0.w, -v1.z  // ::w<3>

#line 205
    mul r1, r1, c186.x
    mova a0, r1
    mul r1, v1.y, c0[a0.y]
    mul r2, v1.y, c1[a0.y]
    mul r3, v1.y, c2[a0.y]
    mad r1, c0[a0.x], v1.x, r1  // ::skinMatrix<0,1,2,3>
    mad r2, c1[a0.x], v1.x, r2  // ::skinMatrix<4,5,6,7>
    mad r3, c2[a0.x], v1.x, r3  // ::skinMatrix<8,9,10,11>
    mad r1, c0[a0.z], v1.z, r1  // ::skinMatrix<0,1,2,3>
    mad r2, c1[a0.z], v1.z, r2  // ::skinMatrix<4,5,6,7>
    mad r3, c2[a0.z], v1.z, r3  // ::skinMatrix<8,9,10,11>
    mad r1, c0[a0.w], r0.w, r1  // ::skinMatrix<0,1,2,3>
    mad r2, c1[a0.w], r0.w, r2  // ::skinMatrix<4,5,6,7>
    mad r3, c2[a0.w], r0.w, r3  // ::skinMatrix<8,9,10,11>

#line 346
    mad r4, v0.xyzx, c177.zzzw, c177.wwwz
    dp4 r0.w, r4, r1  // ::localPos<0>
    dp4 r1.w, r4, r2  // ::localPos<1>
    dp4 r2.w, r4, r3  // ::localPos<2>
    dp3 r1.x, r0, r1  // ::g__worldNormal<0>
    dp3 r1.y, r0, r2  // ::g__worldNormal<1>
    dp3 r0.x, r0, r3  // ::g__worldNormal<2>
    mul r3, r1.w, c179
    mad r3, r0.w, c178, r3
    mad r2, r2.w, c180, r3
    add r2, r2, c181  // ::g__worldPos<0,1,2,3>
    mul r0.yzw, r1.y, c179.xxyz
    mad r0.yzw, r1.x, c178.xxyz, r0
    mad r0.xyz, r0.x, c180, r0.yzww  // ::g__worldNormal<0,1,2>
    mul r1, r2.y, c240
    mad r1, r2.x, c239, r1
    mad r1, r2.z, c241, r1
    mad o0, r2.w, c242, r1  // ::main<0,1,2,3>

#line 239
    add r1.xyz, -r2, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r1, r1
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r1.xyz, r1, r0.w  // ::lightVec<0,1,2>

#line 247
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r3.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 298
    dp3_sat r0.w, r0, r1  // calcLambert::Qd<0>

#line 324
    mul r1.xyz, r3, r0.w  // ::Ir<0,1,2>
    if b13

#line 239
      add r3.xyz, -r2, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r3.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r3.w, -c212.x
      max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
      mul r3.w, r0.w, r0.w
      mul r3.w, r3.w, c212.w
      mad r0.w, r0.w, c212.z, r3.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 329
      mad r1.xyz, r0.w, r4, r1  // ::Ir<0,1,2>

#line 325
    endif

#line 331
    if b14

#line 239
      add r3.xyz, -r2, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r3.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r3.w, -c215.x
      max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
      mul r3.w, r0.w, r0.w
      mul r3.w, r3.w, c215.w
      mad r0.w, r0.w, c215.z, r3.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 335
      mad r3.xyz, r0.w, r4, r1  // ::Ir<0,1,2>

#line 239
      add r4.xyz, -r2, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r3.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r3.w, -c218.x
      max r0.w, r0.w, c186.y  // ::lightVecLenPrime<0>
      mul r3.w, r0.w, r0.w
      mul r3.w, r3.w, c218.w
      mad r0.w, r0.w, c218.z, r3.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 338
      mad r1.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 331
    endif

#line 167
    mov o1, c197  // ::main<4,5,6,7>

#line 349
    mov o2.w, v4.x  // ::main<11>
    mov o2.xyz, r0  // ::main<8,9,10>
    mov o3, r2  // ::main<12,13,14,15>

#line 331
    mov r1.w, c177.z
    mov o5, r1  // ::main<20,21,22,23>

// approximately 117 instruction slots used
