//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Crowd_HVA_Billboard_AN_Vd_VtxAtm.vso
//
//
// Parameters:
//
//   float4 g__cameraPos;
//   float4 g__cameraRight;
//   float4 g__cameraUp;
//   float4 g__crowdControl1;
//   float4 g__crowdControl2;
//   float4 g__crowdControl3;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__crowdControl1  c20      1
//   g__crowdControl2  c21      1
//   g__crowdControl3  c22      1
//   g__worldMatrix    c178     4
//   g__viewProjMatrix c239     4
//   g__cameraRight    c243     1
//   g__cameraUp       c244     1
//   g__cameraPos      c245     1
//

    vs_3_0
    def c186, -0.0187292993, 0.0742610022, -0.212114394, 1.57072878
    def c187, -2, 3.14159274, 57.2957802, 0.180141002
    def c188, 0.100000001, -0.100000001, -1, -0.330299497
    def c189, 0.0208350997, -0.0851330012, 0.999866009, 180
    def c190, -2, 1.57079637, 0.00277777785, 0
    def c182, 1, -1, 0, 1
    def c183, -1, -1, 1, 1
    def c184, -1, 1, 1, 0
    def c185, 1, 1, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_color v1  // IN<3,4,5,6>
    dcl_texcoord v2  // IN<7,8>
    dcl_texcoord1 v3  // IN<9>
    dcl_texcoord2 v4  // IN<10>
    dcl_texcoord3 v5  // IN<11>
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2
    dcl_texcoord1 o3
    dcl_texcoord2 o4
    dcl_texcoord3 o5
    dcl_texcoord5 o6.xy

#line 166 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Crowd_HVA_Billboard_AN_Vd_VtxAtm.final"
    slt r0.x, v5.x, -v5.x
    frc r0.y, v5.x
    add r0.z, -r0.y, v5.x
    slt r0.y, -r0.y, r0.y
    mad r0.x, r0.x, r0.y, r0.z  // ::g__index<0>

#line 115
    mova a0.x, r0.x

#line 333
    mov r0.xyz, c243  // ::g__cameraRight<0,1,2>
    mul r1.xyz, r0, c182[a0.x].x
    mul r2, c179, v0.y
    mad r2, v0.x, c178, r2
    mad r2, v0.z, c180, r2
    add r2, r2, c181  // ::g__worldPos<0,1,2,3>
    mad r1.xyz, r1, v3.x, r2  // ::g__worldPos<0,1,2>
    mov r3.xyz, c244  // ::g__cameraUp<0,1,2>
    mul r3.xyz, r3, c182[a0.x].y
    mad r1.xyz, r3, v4.x, r1  // ::g__worldPos<0,1,2>

#line 337
    mul r3, r1.y, c240
    mad r3, r1.x, c239, r3
    mad r1, r1.z, c241, r3
    mad o0, r2.w, c242, r1  // ::main<0,1,2,3>

#line 332
    add r1.xyz, -r2.yzxw, c245.yzxw

#line 352
    add r0.w, c20.y, v2.y
    rcp r1.w, c20.x
    mul r0.w, r0.w, r1.w
    frc r2.x, r0_abs.w
    sge r0.w, r0.w, -r0.w
    lrp r3.x, r0.w, r2.x, -r2.x
    mul r0.w, r3.x, c20.x  // ::animTime<0>
    mul r0.w, r1.w, r0.w
    mul r1.w, r0.w, c20.z  // ::blendFrame<0>
    frc r2.x, r1.w
    add r1.w, r1.w, -r2.x  // ::currFrame<0>
    mad o5.w, r0.w, c20.z, -r1.w  // ::main<23>

#line 332
    dp3 r0.w, r1, r1
    rsq r0.w, r0.w
    mul r1.xyz, r1, r0.w  // ::look<1,2,0>

#line 342
    max r0.w, r1_abs.z, r1_abs.y
    rcp r0.w, r0.w
    min r2.x, r1_abs.z, r1_abs.y
    mul r0.w, r0.w, r2.x
    mul r2.x, r0.w, r0.w
    mad r2.y, r2.x, c189.x, c189.y
    mad r2.y, r2.x, r2.y, c187.w
    mad r2.y, r2.x, r2.y, c188.w
    mad r2.x, r2.x, r2.y, c189.z
    mul r0.w, r0.w, r2.x
    mad r2.x, r0.w, c190.x, c190.y
    slt r2.y, r1_abs.z, r1_abs.y
    mad r0.w, r2.x, r2.y, r0.w
    slt r2.xy, r1.xzzw, -r1.xzzw
    mad r0.w, r2.y, -c187.y, r0.w
    add r2.y, r0.w, r0.w
    min r2.z, r1.z, r1.y
    slt r2.z, r2.z, -r2.z
    max r1.y, r1.z, r1.y
    sge r1.y, r1.y, -r1.y
    mul r1.y, r2.z, r1.y
    mad r0.w, r1.y, -r2.y, r0.w
    mad r0.w, r0.w, c187.z, v2.x
    add r0.w, r0.w, c189.w
    mul r0.w, r0.w, c190.z
    frc r1.y, r0_abs.w
    sge r0.w, r0.w, -r0.w
    lrp r2.y, r0.w, r1.y, -r1.y
    mul r0.w, r2.y, c21.x  // ::currSlice<0>
    frc r1.y, r0.w
    add r0.w, r0.w, -r1.y
    mad r3.x, c21.x, r2.y, -r0.w  // ::blendSlice<0>
    mad r0.w, c21.x, r2.y, -r3.x  // ::currSlice<0>

#line 338
    mad r1.y, r1_abs.x, c186.x, c186.y
    mad r1.y, r1.y, r1_abs.x, c186.z
    mad r1.y, r1.y, r1_abs.x, c186.w
    add r1.x, -r1_abs.x, c182.w
    rsq r1.x, r1.x
    rcp r1.x, r1.x
    mul r1.x, r1.y, r1.x
    mad r1.y, r1.x, c187.x, c187.y
    mad r1.x, r1.y, r2.x, r1.x
    mul r1.x, r1.x, c187.z  // ::vAngle<0>

#line 350
    mov r2.yzw, c21  // ::g__crowdControl2<1,2,3>
    add r2.xyz, r2.zwyw, c188

#line 339
    max r1.x, r1.x, r2.x  // ::vAngle<0>
    add r1.x, r1.x, -c21.z  // ::vAngle<0>
    min r1.x, r2.y, r1.x  // ::vAngle<0>

#line 347
    mul r1.x, r1.x, c21.y
    rcp r1.y, c21.w
    mul r1.z, r1.x, r1.y  // ::currStack<0>
    frc r2.x, r1.z
    add r1.z, r1.z, -r2.x
    mad r3.y, r1.x, r1.y, -r1.z  // ::blendStack<0>
    mad r1.x, r1.x, r1.y, -r3.y  // ::currStack<0>

#line 344
    mov o4.xy, r3  // ::main<16,17>

#line 357
    mad r1.y, r1.x, c21.x, r0.w
    mul o2.x, r1.y, c22.x  // ::main<8>

#line 346
    add r1.y, r0.w, c182.w
    rcp r1.z, c21.x
    mul r1.y, r1.y, r1.z
    frc r1.z, r1_abs.y
    sge r1.y, r1.y, -r1.y
    lrp r2.x, r1.y, r1.z, -r1.z
    mul r1.y, r2.x, c21.x  // ::nextSlice<0>

#line 358
    mad r1.z, r1.x, c21.x, r1.y

#line 350
    add r1.x, r1.x, c182.w
    max r1.x, r1.x, c182.z
    min r1.x, r2.z, r1.x  // ::nextStack<0>

#line 358
    mul o2.y, r1.z, c22.x  // ::main<9>
    mad r0.w, r1.x, c21.x, r0.w
    mad r1.x, r1.x, c21.x, r1.y
    mul o2.w, r1.x, c22.x  // ::main<11>
    mul o2.z, r0.w, c22.x  // ::main<10>
    mul o3.x, r1.w, c22.y  // ::main<12>

#line 355
    add r0.w, r1.w, c182.w
    rcp r1.x, c20.z
    mul r0.w, r0.w, r1.x
    frc r1.x, r0_abs.w
    sge r0.w, r0.w, -r0.w
    lrp r2.x, r0.w, r1.x, -r1.x
    mul r0.w, r2.x, c20.z  // ::nextFrame<0>

#line 362
    mul o3.y, r0.w, c22.y  // ::main<13>

#line 371
    mul r1.xyz, r0.yzxw, c244.zxyw
    mad r0.xyz, c244.yzxw, r0.zxyw, -r1
    dp3 r0.x, r0, r0
    rsq r0.x, r0.x
    mul o5.z, r0.y, r0.x  // ::main<22>

#line 388
    mov o1, v1  // ::main<4,5,6,7>

#line 361
    mov o3.zw, c22.xyxy  // ::main<14,15>

#line 344
    mov o4.zw, c22  // ::main<18,19>

#line 374
    mov o5.x, c243.y  // ::main<20>
    mov o5.y, c244.y  // ::main<21>

#line 123
    mov o6.xy, c182[a0.x].zwzw  // ::main<24,25>

// approximately 130 instruction slots used
