//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_SpeedTree_Branch_Lit_ADS_Shdw_WPos_Vd_VNorm_VtxAtm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__mtlColor;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float3x4 g__windMat[3];
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__windMat               c0       9
//   g__worldMatrix           c178     4
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c9, 2, -1, 0.00392156886, 0.333333343
    def c10, 3, 0.00999999978, 0, 0
    def c11, 1, 0, 0.329411775, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,8>
    dcl_texcoord v3  // IN<10,11>
    dcl_texcoord1 v4  // IN<12,13>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord4 o6

#line 159 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_SpeedTree_Branch_Lit_ADS_Shdw_WPos_Vd_VNorm_VtxAtm_8DL.final"
    mad r0.xyz, v1, c9.x, c9.y  // ::g__vertexNormal<0,1,2>

#line 166
    mul r0.w, c9.z, v2.x  // ::g__weights<0>
    frc r1.x, v2.z
    add r1.y, -r1.x, v2.z
    slt r1.z, v2.z, -v2.z
    slt r1.x, -r1.x, r1.x
    mad r1.x, r1.z, r1.x, r1.y  // ::g__indices<0>

#line 319
    mul r1.yzw, c179.xxyz, v0.y
    mad r1.yzw, v0.x, c178.xxyz, r1
    mad r1.yzw, v0.z, c180.xxyz, r1  // ::g__worldPos<0,1,2>
    mul r2.xyz, r0.y, c179
    mad r2.xyz, r0.x, c178, r2
    mad r0.xyz, r0.z, c180, r2  // ::g__worldNormal<0,1,2>

#line 311
    mul r1.x, r1.x, c9.w
    frc r2.x, r1_abs.x
    sge r1.x, r1.x, -r1.x
    lrp r3.x, r1.x, r2.x, -r2.x
    mul r1.x, r3.x, c10.x
    frc r2.x, r1.x
    add r2.y, r1.x, -r2.x
    slt r1.x, r1.x, -r1.x
    slt r2.x, -r2.x, r2.x
    mad r1.x, r1.x, r2.x, r2.y  // ::modInd<0>
    mul r1.x, r1.x, c10.x
    mova a0.x, r1.x
    mul r2.xyz, r1.z, c1[a0.x]
    mad r2.xyz, r1.y, c0[a0.x], r2
    mad r2.xyz, r1.w, c2[a0.x], r2  // ::windPos<0,1,2>
    lrp r3.xyz, r0.w, r2, r1.yzww  // ::windEffect<0,1,2>

#line 322
    add r1.xyz, r3, c181  // ::g__worldPos<0,1,2>

#line 196
    add r2.xyz, -r1, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r2, r2
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 204
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c10.y  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r3.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 255
    dp3_sat r0.w, r0, r2  // calcLambert::Qd<0>

#line 281
    mul r2.xyz, r3, r0.w  // ::Ir<0,1,2>
    if b13

#line 196
      add r3.xyz, -r1, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 204
      add r0.w, r1.w, -c212.x
      max r0.w, r0.w, c10.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c212.w
      mad r0.w, r0.w, c212.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 255
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 286
      mad r2.xyz, r0.w, r4, r2  // ::Ir<0,1,2>

#line 282
    endif

#line 288
    if b14

#line 196
      add r3.xyz, -r1, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 204
      add r0.w, r1.w, -c215.x
      max r0.w, r0.w, c10.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c215.w
      mad r0.w, r0.w, c215.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 255
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 292
      mad r3.xyz, r0.w, r4, r2  // ::Ir<0,1,2>

#line 196
      add r4.xyz, -r1, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 204
      add r0.w, r1.w, -c218.x
      max r0.w, r0.w, c10.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c218.w
      mad r0.w, r0.w, c218.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 255
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 295
      mad r2.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 288
    endif

#line 297
    if b15

#line 196
      add r3.xyz, -r1, c220  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 204
      add r0.w, r1.w, -c221.x
      max r0.w, r0.w, c10.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c221.w
      mad r0.w, r0.w, c221.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c219  // getDynamicPointLight::color<0,1,2>

#line 255
      dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 301
      mad r3.xyz, r0.w, r4, r2  // ::Ir<0,1,2>

#line 196
      add r4.xyz, -r1, c223  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 204
      add r0.w, r1.w, -c224.x
      max r0.w, r0.w, c10.y  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c224.w
      mad r0.w, r0.w, c224.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c222  // getDynamicPointLight::color<0,1,2>

#line 255
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 304
      mad r2.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 297
    endif

#line 328
    mul r3, r1.y, c240
    mad r3, r1.x, c239, r3
    mad r3, r1.z, c241, r3
    add o0, r3, c242  // ::main<0,1,2,3>

#line 160
    mov r3.xyz, c11
    mad o1, c197.xyzx, r3.xxxy, r3.yyyz  // ::main<4,5,6,7>

#line 320
    mov o2.xyz, r0  // ::main<8,9,10>
    mov o3.w, -c9.y  // ::main<14>
    mov o3.xyz, r1  // ::main<11,12,13>

#line 348
    mov o4.xy, v3  // ::main<15,16>
    mov o4.zw, v4.xyxy  // ::main<17,18>
    mov o5, v3.xyxy  // ::main<19,20,21,22>

#line 297
    mov r2.w, -c9.y
    mov o6, r2  // ::main<23,24,25,26>

// approximately 140 instruction slots used
