//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Terrain3_VtxAtm.vso
//
//
// Parameters:
//
//   row_major float4x4 g__viewProjMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c0, 1, 0, 2, -1
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_position o0
    dcl_texcoord o1
    dcl_texcoord1 o2

#line 320 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Terrain3_VtxAtm.final"
    mul r0, c240, v0.y
    mad r0, v0.x, c239, r0
    mad r0, v0.z, c241, r0
    add o0, r0, c242  // ::main<0,1,2,3>

#line 334
    mad o1, v0.xyzx, c0.xxxy, c0.yyyx  // ::main<4,5,6,7>

#line 153
    mad o2, v1.xyzx, c0.zzzy, c0.wwwx  // ::main<8,9,10,11>

// approximately 6 instruction slots used
