//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_Morphable_AD_Ao_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float2x4 g__morphing;
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__morphing              c194     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c0, 2, -1, 1, 0
    def c1, 0.00999999978, 0, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6>
    dcl_position1 v3  // IN<10,11,12>
    dcl_normal1 v4  // IN<13,14,15>
    dcl_texcoord v5  // IN<16,17>
    dcl_texcoord1 v6  // IN<18,19>
    dcl_texcoord2 v7  // IN<20,21>
    dcl_texcoord3 v8  // IN<22,23>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord4 o5

#line 165 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_Morphable_AD_Ao_VtxAtm_WPos_VNorm_8DL.final"
    mov r0.xyz, v0  // IN<0,1,2>
    add r0.xyz, -r0, v3
    mad r0.xyz, c195.w, r0, v0  // ::g__vertexPos<0,1,2>
    mad r1.xyz, v1, c0.x, c0.y
    mad r2.xyz, v4, c0.x, c0.y
    lrp r3.xyz, c195.w, r2, r1  // ::g__vertexNormal<0,1,2>

#line 178
    mov r1.z, c0.z
    add r1, r1.z, -c194.xxyy
    mul r2, r1.yyww, v5.xyxy
    mad r2, c194.xxyy, v6.xyxy, r2  // ::albedoMapUVStart<0,1>, ::detailMapUVStart<0,1>
    mul r1, r1, v7.xyxy
    mad r1, c194.xxyy, v8.xyxy, r1  // ::albedoMapUVEnd<0,1>, ::detailMapUVEnd<0,1>
    lrp r4, c195.w, r1, r2  // ::albedoMapUV<0,1>, ::detailMapUV<0,1>

#line 132
    mad r1.xyz, r4.xyxw, c0.zzww, c0.wwzw
    dp3 o4.x, c182, r1  // ::main<16>
    dp3 o4.y, c183, r1  // ::main<17>
    mad r1.xyz, r4.zwxw, c0.zzww, c0.wwzw
    dp3 o4.z, c184, r1  // ::main<18>
    dp3 o4.w, c185, r1  // ::main<19>

#line 362
    mul r1, r0.y, c179
    mad r1, r0.x, c178, r1
    mad r0, r0.z, c180, r1
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>
    mul r1.xyz, r3.y, c179
    mad r1.xyz, r3.x, c178, r1
    mad r1.xyz, r3.z, c180, r1  // ::g__worldNormal<0,1,2>

#line 245
    add r2.xyz, -r0, c208  // ::lightVec<0,1,2>
    dp3 r1.w, r2, r2
    rsq r1.w, r1.w
    rcp r2.w, r1.w  // ::lightVecLen<0>
    mul r2.xyz, r2, r1.w  // ::lightVec<0,1,2>

#line 253
    add r1.w, r2.w, -c209.x
    max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
    mul r2.w, r1.w, r1.w
    mul r2.w, r2.w, c209.w
    mad r1.w, r1.w, c209.z, r2.w
    rcp_sat r1.w, r1.w  // ::attenuation<0>
    mul r3.xyz, r1.w, c207  // getDynamicPointLight::color<0,1,2>

#line 304
    dp3_sat r1.w, r1, r2  // calcLambert::Qd<0>

#line 330
    mul r2.xyz, r3, r1.w  // ::Ir<0,1,2>
    if b13

#line 245
      add r3.xyz, -r0, c211  // ::lightVec<0,1,2>
      dp3 r1.w, r3, r3
      rsq r1.w, r1.w
      rcp r3.w, r1.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r1.w  // ::lightVec<0,1,2>

#line 253
      add r1.w, r3.w, -c212.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r3.w, r1.w, r1.w
      mul r3.w, r3.w, c212.w
      mad r1.w, r1.w, c212.z, r3.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r4.xyz, r1.w, c210  // getDynamicPointLight::color<0,1,2>

#line 304
      dp3_sat r1.w, r1, r3  // calcLambert::Qd<0>

#line 335
      mad r2.xyz, r1.w, r4, r2  // ::Ir<0,1,2>

#line 331
    endif

#line 337
    if b14

#line 245
      add r3.xyz, -r0, c214  // ::lightVec<0,1,2>
      dp3 r1.w, r3, r3
      rsq r1.w, r1.w
      rcp r3.w, r1.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r1.w  // ::lightVec<0,1,2>

#line 253
      add r1.w, r3.w, -c215.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r3.w, r1.w, r1.w
      mul r3.w, r3.w, c215.w
      mad r1.w, r1.w, c215.z, r3.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r4.xyz, r1.w, c213  // getDynamicPointLight::color<0,1,2>

#line 304
      dp3_sat r1.w, r1, r3  // calcLambert::Qd<0>

#line 341
      mad r3.xyz, r1.w, r4, r2  // ::Ir<0,1,2>

#line 245
      add r4.xyz, -r0, c217  // ::lightVec<0,1,2>
      dp3 r1.w, r4, r4
      rsq r1.w, r1.w
      rcp r3.w, r1.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r1.w  // ::lightVec<0,1,2>

#line 253
      add r1.w, r3.w, -c218.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r3.w, r1.w, r1.w
      mul r3.w, r3.w, c218.w
      mad r1.w, r1.w, c218.z, r3.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r5.xyz, r1.w, c216  // getDynamicPointLight::color<0,1,2>

#line 304
      dp3_sat r1.w, r1, r4  // calcLambert::Qd<0>

#line 344
      mad r2.xyz, r1.w, r5, r3  // ::Ir<0,1,2>

#line 337
    endif

#line 346
    if b15

#line 245
      add r3.xyz, -r0, c220  // ::lightVec<0,1,2>
      dp3 r1.w, r3, r3
      rsq r1.w, r1.w
      rcp r3.w, r1.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r1.w  // ::lightVec<0,1,2>

#line 253
      add r1.w, r3.w, -c221.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r3.w, r1.w, r1.w
      mul r3.w, r3.w, c221.w
      mad r1.w, r1.w, c221.z, r3.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r4.xyz, r1.w, c219  // getDynamicPointLight::color<0,1,2>

#line 304
      dp3_sat r1.w, r1, r3  // calcLambert::Qd<0>

#line 350
      mad r3.xyz, r1.w, r4, r2  // ::Ir<0,1,2>

#line 245
      add r4.xyz, -r0, c223  // ::lightVec<0,1,2>
      dp3 r1.w, r4, r4
      rsq r1.w, r1.w
      rcp r3.w, r1.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r1.w  // ::lightVec<0,1,2>

#line 253
      add r1.w, r3.w, -c224.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r3.w, r1.w, r1.w
      mul r3.w, r3.w, c224.w
      mad r1.w, r1.w, c224.z, r3.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r5.xyz, r1.w, c222  // getDynamicPointLight::color<0,1,2>

#line 304
      dp3_sat r1.w, r1, r4  // calcLambert::Qd<0>

#line 353
      mad r2.xyz, r1.w, r5, r3  // ::Ir<0,1,2>

#line 346
    endif

#line 369
    mul r3, r0.y, c240
    mad r3, r0.x, c239, r3
    mad r3, r0.z, c241, r3
    mad o0, r0.w, c242, r3  // ::main<0,1,2,3>

#line 167
    mov o1, c197  // ::main<4,5,6,7>

#line 363
    mov o2.w, v2.x  // ::main<11>
    mov o2.xyz, r1  // ::main<8,9,10>
    mov o3, r0  // ::main<12,13,14,15>

#line 346
    mov r2.w, c0.z
    mov o5, r2  // ::main<20,21,22,23>

// approximately 132 instruction slots used
