//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_Morphable_ADN_Ao_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float2x4 g__morphing;
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm2;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__texXfm2               c186     2
//   g__morphing              c194     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c0, 2, -1, 1, 0
    def c1, 0.00999999978, 0, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6>
    dcl_position1 v3  // IN<10,11,12>
    dcl_normal1 v4  // IN<13,14,15>
    dcl_texcoord v5  // IN<16,17>
    dcl_texcoord1 v6  // IN<18,19>
    dcl_texcoord2 v7  // IN<20,21>
    dcl_texcoord3 v8  // IN<22,23>
    dcl_tangent v9  // IN<24,25,26,27>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord3 o6
    dcl_texcoord4 o7
    dcl_texcoord5 o8

#line 169 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_Morphable_ADN_Ao_VtxAtm_WPos_VNorm_8DL.final"
    mov r0.xyz, v0  // IN<0,1,2>
    add r0.xyz, -r0, v3
    mad r0.xyz, c195.w, r0, v0  // ::g__vertexPos<0,1,2>
    mad r1.xyz, v1.zxyw, c0.x, c0.y
    mad r2.xyz, v4.zxyw, c0.x, c0.y
    lrp r3.xyz, c195.w, r2, r1  // ::g__vertexNormal<2,0,1>

#line 189
    mov r1.z, c0.z
    add r1.xyz, r1.z, -c194

#line 182
    mul r2, r1.xxyy, v5.xyxy
    mad r2, c194.xxyy, v6.xyxy, r2  // ::albedoMapUVStart<0,1>, ::detailMapUVStart<0,1>
    mul r4, r1.xxyy, v7.xyxy
    mad r4, c194.xxyy, v8.xyxy, r4  // ::albedoMapUVEnd<0,1>, ::detailMapUVEnd<0,1>
    lrp r5, c195.w, r4, r2  // ::albedoMapUV<0,1>, ::detailMapUV<0,1>

#line 132
    mad r1.xyw, r5.xyzx, c0.zzzw, c0.wwzz
    dp3 o7.x, c182, r1.xyww  // ::main<28>
    dp3 o7.y, c183, r1.xyww  // ::main<29>
    mad r1.xyw, r5.zwzx, c0.zzzw, c0.wwzz
    dp3 o7.z, c184, r1.xyww  // ::main<30>
    dp3 o7.w, c185, r1.xyww  // ::main<31>

#line 189
    mul r1.xy, r1.z, v5
    mad r1.xy, c194.z, v6, r1  // ::normalMapUVStart<0,1>
    mul r1.zw, r1.z, v7.xyxy
    mad r1.zw, c194.z, v8.xyxy, r1  // ::normalMapUVEnd<0,1>
    lrp r2.xy, c195.w, r1.zwzw, r1  // ::normalMapUV<0,1>

#line 132
    mov r2.z, c0.z
    dp3 o8.x, c186, r2  // ::main<32>
    dp3 o8.y, c187, r2  // ::main<33>

#line 202
    mad r1, v9, c0.x, c0.y  // ::g__vertexTangent<0,1,2,3>
    dp3 r0.w, r1, r1
    rsq r0.w, r0.w
    mul r1.xyz, r1.yzxw, r0.w  // ::g__vertexTangent<1,2,0>
    mul r2.xyz, r3, r1
    mad r2.xyz, r3.zxyw, r1.yzxw, -r2
    mul r2.xyz, r1.w, r2  // ::g__vertexBinormal<0,1,2>

#line 372
    mul r4, r0.y, c179
    mad r4, r0.x, c178, r4
    mad r0, r0.z, c180, r4
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>
    mul r4.xyz, r3.z, c179
    mad r3.yzw, r3.y, c178.xxyz, r4.xxyz
    mad r3.xyz, r3.x, c180, r3.yzww  // ::g__worldNormal<0,1,2>

#line 255
    add r4.xyz, -r0, c208  // ::lightVec<0,1,2>
    dp3 r1.w, r4, r4
    rsq r1.w, r1.w
    rcp r2.w, r1.w  // ::lightVecLen<0>
    mul r4.xyz, r4, r1.w  // ::lightVec<0,1,2>

#line 263
    add r1.w, r2.w, -c209.x
    max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
    mul r2.w, r1.w, r1.w
    mul r2.w, r2.w, c209.w
    mad r1.w, r1.w, c209.z, r2.w
    rcp_sat r1.w, r1.w  // ::attenuation<0>
    mul r5.xyz, r1.w, c207  // getDynamicPointLight::color<0,1,2>

#line 314
    dp3_sat r1.w, r3, r4  // calcLambert::Qd<0>

#line 340
    mul r4.xyz, r5.zxyw, r1.w  // ::Ir<2,0,1>
    if b13

#line 255
      add r5.xyz, -r0, c211  // ::lightVec<0,1,2>
      dp3 r1.w, r5, r5
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r5.xyz, r5, r1.w  // ::lightVec<0,1,2>

#line 263
      add r1.w, r2.w, -c212.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c212.w
      mad r1.w, r1.w, c212.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r6.xyz, r1.w, c210  // getDynamicPointLight::color<0,1,2>

#line 314
      dp3_sat r1.w, r3, r5  // calcLambert::Qd<0>

#line 345
      mad r4.xyz, r1.w, r6.zxyw, r4  // ::Ir<2,0,1>

#line 341
    endif

#line 347
    if b14

#line 255
      add r5.xyz, -r0, c214  // ::lightVec<0,1,2>
      dp3 r1.w, r5, r5
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r5.xyz, r5, r1.w  // ::lightVec<0,1,2>

#line 263
      add r1.w, r2.w, -c215.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c215.w
      mad r1.w, r1.w, c215.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r6.xyz, r1.w, c213  // getDynamicPointLight::color<0,1,2>

#line 314
      dp3_sat r1.w, r3, r5  // calcLambert::Qd<0>

#line 351
      mad r5.xyz, r1.w, r6, r4.yzxw  // ::Ir<0,1,2>

#line 255
      add r6.xyz, -r0, c217  // ::lightVec<0,1,2>
      dp3 r1.w, r6, r6
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r1.w  // ::lightVec<0,1,2>

#line 263
      add r1.w, r2.w, -c218.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c218.w
      mad r1.w, r1.w, c218.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r7.xyz, r1.w, c216  // getDynamicPointLight::color<0,1,2>

#line 314
      dp3_sat r1.w, r3, r6  // calcLambert::Qd<0>

#line 354
      mad r4.xyz, r1.w, r7.zxyw, r5.zxyw  // ::Ir<2,0,1>

#line 347
    endif

#line 356
    if b15

#line 255
      add r5.xyz, -r0, c220  // ::lightVec<0,1,2>
      dp3 r1.w, r5, r5
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r5.xyz, r5, r1.w  // ::lightVec<0,1,2>

#line 263
      add r1.w, r2.w, -c221.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c221.w
      mad r1.w, r1.w, c221.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r6.xyz, r1.w, c219  // getDynamicPointLight::color<0,1,2>

#line 314
      dp3_sat r1.w, r3, r5  // calcLambert::Qd<0>

#line 360
      mad r5.xyz, r1.w, r6, r4.yzxw  // ::Ir<0,1,2>

#line 255
      add r6.xyz, -r0, c223  // ::lightVec<0,1,2>
      dp3 r1.w, r6, r6
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r1.w  // ::lightVec<0,1,2>

#line 263
      add r1.w, r2.w, -c224.x
      max r1.w, r1.w, c1.x  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c224.w
      mad r1.w, r1.w, c224.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r7.xyz, r1.w, c222  // getDynamicPointLight::color<0,1,2>

#line 314
      dp3_sat r1.w, r3, r6  // calcLambert::Qd<0>

#line 363
      mad r4.xyz, r1.w, r7.zxyw, r5.zxyw  // ::Ir<2,0,1>

#line 356
      mov r5.x, r4.y  // ::Ir<0>
      mov r6.x, r4.z  // ::Ir<1>
    else
      mov r5.x, r4.y  // ::Ir<0>
      mov r6.x, r4.z  // ::Ir<1>
    endif

#line 379
    mul r7, r0.y, c240
    mad r7, r0.x, c239, r7
    mad r7, r0.z, c241, r7
    mad o0, r0.w, c242, r7  // ::main<0,1,2,3>

#line 387
    mul r7.xyz, r1.x, c179
    mad r1.xzw, r1.z, c178.xyyz, r7.xyyz
    mad r1.xyz, r1.y, c180, r1.xzww  // ::worldTangent<0,1,2>
    mul r7.xyz, r2.y, c179
    mad r2.xyw, r2.x, c178.xyzz, r7.xyzz
    mad r2.xyz, r2.z, c180, r2.xyww  // ::worldBinormal<0,1,2>

#line 171
    mov o1, c197  // ::main<4,5,6,7>

#line 373
    mov o2.w, v2.x  // ::main<11>
    mov o2.xyz, r3  // ::main<8,9,10>
    mov o3, r0  // ::main<12,13,14,15>

#line 387
    mov r5.y, r1.x
    mov r5.z, r2.x
    mov r5.w, r3.x
    mov o4, r5.yzwx  // ::main<16,17,18,19>
    mov r6.y, r1.y
    mov r6.z, r2.y
    mov r6.w, r3.y
    mov o5, r6.yzwx  // ::main<20,21,22,23>
    mov r4.y, r1.z
    mov r4.z, r2.z
    mov r4.w, r3.z
    mov o6, r4.yzwx  // ::main<24,25,26,27>

#line 132
    mov o8.zw, c0.w  // ::main<34,35>

// approximately 169 instruction slots used
