//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Particles_Billboard_Vd_A.vso
//
//
// Parameters:
//
//   float4 g__cameraPos;
//   float4 g__cameraRight;
//   float4 g__cameraUp;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__worldMatrix    c178     4
//   g__viewProjMatrix c239     4
//   g__cameraRight    c243     1
//   g__cameraUp       c244     1
//   g__cameraPos      c245     1
//

    vs_3_0
    def c252, 1, -1, 0.159154937, 0.5
    def c253, -1, -1, 6.28318548, -3.14159274
    def c254, -1, 1, 0, 0
    def c255, 1, 1, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_color v1  // IN<4,5,6,7>
    dcl_texcoord v2  // IN<8,9,10>
    dcl_texcoord1 v3  // IN<11,12>
    dcl_texcoord2 v4  // IN<15>
    dcl_texcoord3 v5  // IN<16,17>
    dcl_texcoord4 v6  // IN<18,19>
    dcl_texcoord5 v7  // IN<20>
    dcl_texcoord6 v8  // IN<21>
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2.xyz
    dcl_texcoord5 o3.x
    dcl_texcoord6 o4.xy

#line 179 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Particles_Billboard_Vd_A.final"
    slt r0.x, v4.x, -v4.x
    frc r0.y, v4.x
    add r0.z, -r0.y, v4.x
    slt r0.y, -r0.y, r0.y
    mad r0.x, r0.x, r0.y, r0.z  // ::g__index<0>

#line 128
    mova a0.x, r0.x

#line 378
    mul r0.xy, v5.yxzw, c252[a0.x].yxzw
    mul r0.xzw, r0.x, c244.xyyz
    mad r0.xyz, c243, r0.y, r0.xzww  // ::pos<0,1,2>

#line 381
    mad r0.xyz, c243, v6.x, r0  // ::pos<0,1,2>
    mad r0.xyz, c244, v6.y, r0  // ::pos<0,1,2>

#line 357
    mad r0.w, v2.x, c252.z, c252.w
    frc r0.w, r0.w
    mad r0.w, r0.w, c253.z, c253.w
    sincos r1.xy, r0.w  // ::cosX<0>, ::sinX<0>

#line 354
    mov r2.xyz, c244  // ::g__cameraUp<0,1,2>
    mul r3, r2.yyzx, c243.xxyz
    mad r2, r2.xxyz, c243.yyzx, -r3
    dp3 r0.w, r2.yzww, r2.yzww
    rsq r0.w, r0.w
    mul r2, r2, r0.w  // ::look<2,2,0,1>

#line 358
    add r0.w, -r1.x, c252.x  // ::t<0>
    mul r3, r2.wzzz, r0.w  // ::ty<0>, ::tx<0,0,0>

#line 367
    mad r4.x, r3.z, r2.z, r1.x  // ::rotateLook<0>
    mul r1.yzw, r1.y, r2  // ::sz<0>, ::sx<0>, ::sy<0>

#line 373
    mad r5.xyz, r3.wxyw, r2.wxyw, r1.yzww  // ::rotateLook<1,5,6>
    mad r1.yzw, r3.xywx, r2.xywx, -r1.xwyz  // ::rotateLook<2,3,7>

#line 371
    mad r3.y, r3.x, r2.w, r1.x  // ::rotateLook<4>

#line 375
    mul r0.w, r2.y, r2.y
    lrp r2.z, r0.w, c252.x, r1.x  // ::rotateLook<8>

#line 383
    mov r4.y, r5.x
    mov r4.z, r1.y
    dp3 r4.x, r4, r0  // ::pos<0>
    mov r3.x, r1.z
    mov r2.y, r1.w
    mov r3.z, r5.y
    mov r2.x, r5.z
    dp3 r4.z, r2, r0  // ::pos<2>
    dp3 r4.y, r3, r0  // ::pos<1>
    mad r0.xyz, c243, -v6.x, r4  // ::pos<0,1,2>
    mad r0.xyz, c244, -v6.y, r0  // ::pos<0,1,2>

#line 350
    mul r1, c179, v0.y
    mad r1, v0.x, c178, r1
    mad r1, v0.z, c180, r1
    add r1, r1, c181  // ::g__worldPos<0,1,2,3>

#line 386
    add r0.xyz, r0, r1  // ::g__worldPos<0,1,2>
    mul r2, r0.y, c240
    mad r2, r0.x, c239, r2
    mad r2, r0.z, c241, r2

#line 393
    add r0.xyz, -r0, c245  // ::diff<0,1,2>
    dp3 r0.x, r0, r0
    mul r0.x, r0.x, c252.w  // ::fade<0>
    mul r0.x, r0.x, r0.x  // ::fade<0>
    mul r0.x, r0.x, r0.x  // ::fade<0>
    min o4.y, r0.x, c252.x  // ::main<13>

#line 387
    mad o0, r1.w, c242, r2  // ::main<0,1,2,3>

#line 391
    mov r0.z, v2.z  // IN<10>
    mul o1.xyz, r0.z, v1  // ::main<4,5,6>
    mov o1.w, v1.w  // ::main<7>

#line 411
    mov o2.xy, v3  // ::main<8,9>
    mov o2.z, v2.y  // ::main<10>
    mov o3.x, v7.x  // ::main<11>
    mov o4.x, v8.x  // ::main<12>

// approximately 70 instruction slots used
