//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Z_palettemesh_Ao.vso
//
//
// Parameters:
//
//   row_major float3x4 g__matrixPalette[59];
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__matrixPalette  c0     177
//   g__worldMatrix    c178     4
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c177, 255, 0.5, 3, 0
    def c182, 0, 1, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_color1 v1  // IN<3,6>
    dcl_position o0
    dcl_normal o1

#line 153 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Z_palettemesh_Ao.final"
    mad r0.x, v1.w, c177.x, c177.y
    frc r0.y, r0.x
    add r0.z, r0.x, -r0.y
    slt r0.y, -r0.y, r0.y
    slt r0.x, r0.x, -r0.x
    mad r0.x, r0.x, r0.y, r0.z  // ::g__indices<0>

#line 199
    mul r0.x, r0.x, c177.z
    mova a0.x, r0.x

#line 342
    mov r0, c1[a0.x]  // ::g__matrixPalette<4,5,6,7>
    mul r1, r0, c179.y
    mov r2, c0[a0.x]  // ::g__matrixPalette<0,1,2,3>
    mad r1, r2, c178.y, r1
    mov r3, c2[a0.x]  // ::g__matrixPalette<8,9,10,11>
    mad r1, r3, c180.y, r1
    mov r4.xy, c182
    mad r1, c181.y, r4.xxxy, r1  // ::worldMatrix<1,5,9,13>
    mad r5, v0.xyzx, c182.yyyx, c182.xxxy
    dp4 r1.x, r5, r1  // ::g__worldPos<1>
    mov o1.y, r1.y  // ::main<5>

#line 346
    mul r1, r1.x, c240

#line 342
    mul r6, r0, c179.x
    mad r6, r2, c178.x, r6
    mad r6, r3, c180.x, r6
    mad r6, c181.x, r4.xxxy, r6  // ::worldMatrix<0,4,8,12>
    dp4 r4.z, r5, r6  // ::g__worldPos<0>
    mov o1.x, r6.y  // ::main<4>

#line 346
    mad r1, r4.z, c239, r1

#line 342
    mul r6, r0, c179.z
    mad r6, r2, c178.z, r6
    mad r6, r3, c180.z, r6
    mad r6, c181.z, r4.xxxy, r6  // ::worldMatrix<2,6,10,14>
    dp4 r4.z, r5, r6  // ::g__worldPos<2>
    mov o1.z, r6.y  // ::main<6>

#line 346
    mad r1, r4.z, c241, r1

#line 342
    mul r0, r0, c179.w
    mad r0, r2, c178.w, r0
    mad r0, r3, c180.w, r0
    mad r0, c181.w, r4.xxxy, r0  // ::worldMatrix<3,7,11,15>
    dp4 r0.x, r5, r0  // ::g__worldPos<3>

#line 346
    mad o0, r0.x, c242, r1  // ::main<0,1,2,3>

#line 342
    mov o1.w, v1.x  // ::main<7>

// approximately 41 instruction slots used
