//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_SL_ADS_Vd_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm3;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__texXfm3               c188     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c0, 2, -1, 1, 0
    def c1, 0.00999999978, 31.875, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color v2  // IN<6,7,8,9>
    dcl_texcoord v3  // IN<10,11>
    dcl_texcoord1 v4  // IN<12,13>
    dcl_texcoord3 v5  // IN<14,15>
    dcl_texcoord5 v6  // IN<16,17,18,19>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord4 o6

#line 165 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_SL_ADS_Vd_VtxAtm_WPos_VNorm_8DL.final"
    mad r0.xyz, v1, c0.x, c0.y  // ::g__vertexNormal<0,1,2>
    mul o1, c197, v2  // ::main<4,5,6,7>

#line 132
    mad r1.xyz, v3.xyxw, c0.zzww, c0.wwzw
    dp3 o4.x, c182, r1  // ::main<15>
    dp3 o4.y, c183, r1  // ::main<16>
    mad r1.xyz, v4.xyxw, c0.zzww, c0.wwzw
    dp3 o4.z, c184, r1  // ::main<17>
    dp3 o4.w, c185, r1  // ::main<18>
    mad r1.xyz, v5.xyxw, c0.zzww, c0.wwzw
    dp3 o5.z, c188, r1  // ::main<21>
    dp3 o5.w, c189, r1  // ::main<22>

#line 188
    mul r1.xyz, v6.w, v6

#line 355
    mul r2, c179, v0.y
    mad r2, v0.x, c178, r2
    mad r2, v0.z, c180, r2
    add r2, r2, c181  // ::g__worldPos<0,1,2,3>
    mul r3.xyz, r0.y, c179
    mad r0.xyw, r0.x, c178.xyzz, r3.xyzz
    mad r0.xyz, r0.z, c180, r0.xyww  // ::g__worldNormal<0,1,2>

#line 238
    add r3.xyz, -r2, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r3, r3
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 246
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c1.x  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r4.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 297
    dp3_sat r0.w, r0, r3  // calcLambert::Qd<0>

#line 323
    mul r3.xyz, r4, r0.w  // ::Ir<0,1,2>
    if b13

#line 238
      add r4.xyz, -r2, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 246
      add r0.w, r1.w, -c212.x
      max r0.w, r0.w, c1.x  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c212.w
      mad r0.w, r0.w, c212.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 297
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 328
      mad r3.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 324
    endif

#line 330
    if b14

#line 238
      add r4.xyz, -r2, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 246
      add r0.w, r1.w, -c215.x
      max r0.w, r0.w, c1.x  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c215.w
      mad r0.w, r0.w, c215.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 297
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 334
      mad r4.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 238
      add r5.xyz, -r2, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r5, r5
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r5.xyz, r5, r0.w  // ::lightVec<0,1,2>

#line 246
      add r0.w, r1.w, -c218.x
      max r0.w, r0.w, c1.x  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c218.w
      mad r0.w, r0.w, c218.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r6.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 297
      dp3_sat r0.w, r0, r5  // calcLambert::Qd<0>

#line 337
      mad r3.xyz, r0.w, r6, r4  // ::Ir<0,1,2>

#line 330
    endif

#line 339
    if b15

#line 238
      add r4.xyz, -r2, c220  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 246
      add r0.w, r1.w, -c221.x
      max r0.w, r0.w, c1.x  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c221.w
      mad r0.w, r0.w, c221.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r5.xyz, r0.w, c219  // getDynamicPointLight::color<0,1,2>

#line 297
      dp3_sat r0.w, r0, r4  // calcLambert::Qd<0>

#line 343
      mad r4.xyz, r0.w, r5, r3  // ::Ir<0,1,2>

#line 238
      add r5.xyz, -r2, c223  // ::lightVec<0,1,2>
      dp3 r0.w, r5, r5
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r5.xyz, r5, r0.w  // ::lightVec<0,1,2>

#line 246
      add r0.w, r1.w, -c224.x
      max r0.w, r0.w, c1.x  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c224.w
      mad r0.w, r0.w, c224.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r6.xyz, r0.w, c222  // getDynamicPointLight::color<0,1,2>

#line 297
      dp3_sat r0.w, r0, r5  // calcLambert::Qd<0>

#line 346
      mad r3.xyz, r0.w, r6, r4  // ::Ir<0,1,2>

#line 339
    endif

#line 364
    mad o6.xyz, r1, c1.y, r3  // ::main<23,24,25>
    mul r1, r2.y, c240
    mad r1, r2.x, c239, r1
    mad r1, r2.z, c241, r1
    mad o0, r2.w, c242, r1  // ::main<0,1,2,3>

#line 356
    mov o2.xyz, r0  // ::main<8,9,10>
    mov o3, r2  // ::main<11,12,13,14>

#line 369
    mov o5.xy, c0.w  // ::main<19,20>

#line 364
    mov o6.w, c0.z  // ::main<26>

// approximately 124 instruction slots used
