//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_skinned_ADS_VtxAtm_WPos_VNorm.vso
//
//
// Parameters:
//
//   row_major float3x4 g__matrixPalette[59];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm3;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__matrixPalette  c0     177
//   g__worldMatrix    c178     4
//   g__texXfm0        c182     2
//   g__texXfm1        c184     2
//   g__texXfm3        c188     2
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c177, 2, -1, 1, 0
    def c186, 3, 0, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_blendweight v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,7,8,9>
    dcl_normal v3  // IN<10,11,12>
    dcl_texcoord v4  // IN<13,14>
    dcl_texcoord1 v5  // IN<15,16>
    dcl_texcoord3 v6  // IN<17,18>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord4 o6

#line 132 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_skinned_ADS_VtxAtm_WPos_VNorm.final"
    mad r0.xyz, v4.xyxw, c177.zzww, c177.wwzw
    dp3 o4.x, c182, r0  // ::main<15>
    dp3 o4.y, c183, r0  // ::main<16>
    mad r0.xyz, v5.xyxw, c177.zzww, c177.wwzw
    dp3 o4.z, c184, r0  // ::main<17>
    dp3 o4.w, c185, r0  // ::main<18>
    mad r0.xyz, v6.xyxw, c177.zzww, c177.wwzw
    dp3 o5.z, c188, r0  // ::main<21>
    dp3 o5.w, c189, r0  // ::main<22>

#line 200
    add r0.x, c177.z, -v1.x
    add r0.x, r0.x, -v1.y
    add r0.x, r0.x, -v1.z  // ::w<3>

#line 167
    slt r1, v2, -v2
    frc r2, v2
    add r3, -r2, v2
    slt r2, -r2, r2
    mad r1, r1, r2, r3  // ::g__indices<0,1,2,3>

#line 205
    mul r1, r1, c186.x
    mova a0, r1
    mul r1, v1.y, c1[a0.y]
    mad r1, c1[a0.x], v1.x, r1  // ::skinMatrix<4,5,6,7>
    mad r1, c1[a0.z], v1.z, r1  // ::skinMatrix<4,5,6,7>
    mad r1, c1[a0.w], r0.x, r1  // ::skinMatrix<4,5,6,7>

#line 165
    mad r0.yzw, v3.xxyz, c177.x, c177.y  // ::g__vertexNormal<0,1,2>

#line 347
    dp3 r2.x, r0.yzww, r1  // ::g__worldNormal<1>
    mul r2.xyz, r2.x, c179

#line 205
    mul r3, v1.y, c0[a0.y]
    mad r3, c0[a0.x], v1.x, r3  // ::skinMatrix<0,1,2,3>
    mad r3, c0[a0.z], v1.z, r3  // ::skinMatrix<0,1,2,3>
    mad r3, c0[a0.w], r0.x, r3  // ::skinMatrix<0,1,2,3>

#line 347
    dp3 r2.w, r0.yzww, r3  // ::g__worldNormal<0>
    mad r2.xyz, r2.w, c178, r2

#line 205
    mul r4, v1.y, c2[a0.y]
    mad r4, c2[a0.x], v1.x, r4  // ::skinMatrix<8,9,10,11>
    mad r4, c2[a0.z], v1.z, r4  // ::skinMatrix<8,9,10,11>
    mad r4, c2[a0.w], r0.x, r4  // ::skinMatrix<8,9,10,11>

#line 347
    dp3 r0.x, r0.yzww, r4  // ::g__worldNormal<2>
    mad o2.xyz, r0.x, c180, r2  // ::main<8,9,10>

#line 346
    mad r0, v0.xyzx, c177.zzzw, c177.wwwz
    dp4 r1.x, r0, r1  // ::localPos<1>
    mul r1, r1.x, c179
    dp4 r2.x, r0, r3  // ::localPos<0>
    dp4 r0.x, r0, r4  // ::localPos<2>
    mad r1, r2.x, c178, r1
    mad r0, r0.x, c180, r1
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>
    mul r1, r0.y, c240
    mad r1, r0.x, c239, r1
    mad r1, r0.z, c241, r1
    mad o0, r0.w, c242, r1  // ::main<0,1,2,3>
    mov o3, r0  // ::main<11,12,13,14>

#line 168
    mov o1, c197  // ::main<4,5,6,7>

#line 354
    mov o5.xy, c177.w  // ::main<19,20>

#line 359
    mov o6, c177.wwwz  // ::main<23,24,25,26>

// approximately 54 instruction slots used
