//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_Morphable_AD_Ao_VtxAtm_WPos_VNorm.vso
//
//
// Parameters:
//
//   row_major float2x4 g__morphing;
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__worldMatrix    c178     4
//   g__texXfm0        c182     2
//   g__texXfm1        c184     2
//   g__morphing       c194     2
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c0, 2, -1, 1, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6>
    dcl_position1 v3  // IN<10,11,12>
    dcl_normal1 v4  // IN<13,14,15>
    dcl_texcoord v5  // IN<16,17>
    dcl_texcoord1 v6  // IN<18,19>
    dcl_texcoord2 v7  // IN<20,21>
    dcl_texcoord3 v8  // IN<22,23>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord4 o5

#line 178 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_Morphable_AD_Ao_VtxAtm_WPos_VNorm.final"
    mov r0.z, c0.z
    add r0, r0.z, -c194.xxyy
    mul r1, r0.yyww, v5.xyxy
    mul r0, r0, v7.xyxy
    mad r0, c194.xxyy, v8.xyxy, r0  // ::albedoMapUVEnd<0,1>, ::detailMapUVEnd<0,1>
    mad r1, c194.xxyy, v6.xyxy, r1  // ::albedoMapUVStart<0,1>, ::detailMapUVStart<0,1>
    lrp r2, c195.w, r0, r1  // ::albedoMapUV<0,1>, ::detailMapUV<0,1>

#line 132
    mad r0.xyz, r2.xyxw, c0.zzww, c0.wwzw
    mad r1.xyz, r2.zwxw, c0.zzww, c0.wwzw
    dp3 o4.x, c182, r0  // ::main<16>
    dp3 o4.y, c183, r0  // ::main<17>
    dp3 o4.z, c184, r1  // ::main<18>
    dp3 o4.w, c185, r1  // ::main<19>

#line 166
    mad r0.xyz, v1, c0.x, c0.y
    mad r1.xyz, v4, c0.x, c0.y
    lrp r2.xyz, c195.w, r1, r0  // ::g__vertexNormal<0,1,2>

#line 363
    mul r0.xyz, r2.y, c179
    mad r0.xyz, r2.x, c178, r0
    mad o2.xyz, r2.z, c180, r0  // ::main<8,9,10>

#line 165
    mov r0.xyz, v0  // IN<0,1,2>
    add r0.xyz, -r0, v3
    mad r0.xyz, c195.w, r0, v0  // ::g__vertexPos<0,1,2>

#line 362
    mul r1, r0.y, c179
    mad r1, r0.x, c178, r1
    mad r0, r0.z, c180, r1
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>

#line 365
    mul r1, r0.y, c240
    mad r1, r0.x, c239, r1
    mad r1, r0.z, c241, r1
    mad o0, r0.w, c242, r1  // ::main<0,1,2,3>

#line 362
    mov o3, r0  // ::main<12,13,14,15>

#line 167
    mov o1, c197  // ::main<4,5,6,7>

#line 363
    mov o2.w, v2.x  // ::main<11>

#line 371
    mov o5, c0.wwwz  // ::main<20,21,22,23>

// approximately 34 instruction slots used
