//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_2D_Compress.vso
//
//
// Parameters:
//
//   float4 g__invViewport;
//   float4 g__mtlColor;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g__mtlColor    c197     1
//   g__invViewport c248     1
//

    vs_3_0
    def c0, 2048, 0, 1, 0
    dcl_position v0  // IN<0,1>
    dcl_position o0
    dcl_color o1
    dcl_texcoord3 o2

#line 151 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_2D_Compress.final"
    mul r0.xy, c248, v0

#line 344
    mov r1.x, c0.x
    mad o0.xy, r0, r1.x, c248.zwzw  // ::main<0,1>
    mov o0.zw, c0.xyyz  // ::main<2,3>

#line 153
    mov o1, c197  // ::main<4,5,6,7>

#line 346
    mov o2, c0.yyyz  // ::main<8,9,10,11>

// approximately 6 instruction slots used
