//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_palettemesh_AD_Ao_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float3x4 g__matrixPalette[59];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__matrixPalette         c0     177
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c177, 2, -1, 255, 0.5
    def c186, 1, 0, 3, 0.00999999978
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6,9>
    dcl_texcoord v3  // IN<10,11>
    dcl_texcoord1 v4  // IN<12,13>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord4 o5

#line 162 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_palettemesh_AD_Ao_VtxAtm_WPos_VNorm_8DL.final"
    mad r0.xyz, v1, c177.x, c177.y  // ::g__vertexNormal<0,1,2>
    mad r0.w, v2.w, c177.z, c177.w
    frc r1.x, r0.w
    add r1.y, r0.w, -r1.x
    slt r0.w, r0.w, -r0.w
    slt r1.x, -r1.x, r1.x
    mad r0.w, r0.w, r1.x, r1.y  // ::g__indices<0>

#line 132
    mad r1.xyz, v3.xyxw, c186.xxyw, c186.yyxw
    dp3 o4.x, c182, r1  // ::main<16>
    dp3 o4.y, c183, r1  // ::main<17>
    mad r1.xyz, v4.xyxw, c186.xxyw, c186.yyxw
    dp3 o4.z, c184, r1  // ::main<18>
    dp3 o4.w, c185, r1  // ::main<19>

#line 209
    mul r0.w, r0.w, c186.z
    mova a0.x, r0.w

#line 352
    mov r1, c1[a0.x]  // ::g__matrixPalette<4,5,6,7>
    mul r2, r1, c179.x
    mov r3, c0[a0.x]  // ::g__matrixPalette<0,1,2,3>
    mad r2, r3, c178.x, r2
    mov r4, c2[a0.x]  // ::g__matrixPalette<8,9,10,11>
    mad r2, r4, c180.x, r2
    mov r5.xy, c186
    mad r2, c181.x, r5.yyyx, r2  // ::worldMatrix<0,4,8,12>
    mul r6, r1, c179.y
    mad r6, r3, c178.y, r6
    mad r6, r4, c180.y, r6
    mad r6, c181.y, r5.yyyx, r6  // ::worldMatrix<1,5,9,13>
    mul r7, r1, c179.z
    mad r7, r3, c178.z, r7
    mad r7, r4, c180.z, r7
    mad r7, c181.z, r5.yyyx, r7  // ::worldMatrix<2,6,10,14>
    mul r1, r1, c179.w
    mad r1, r3, c178.w, r1
    mad r1, r4, c180.w, r1
    mad r1, c181.w, r5.yyyx, r1  // ::worldMatrix<3,7,11,15>
    mad r3, v0.xyzx, c186.xxxy, c186.yyyx
    dp4 r4.x, r3, r2  // ::g__worldPos<0>
    dp4 r4.y, r3, r6  // ::g__worldPos<1>
    dp4 r4.z, r3, r7  // ::g__worldPos<2>
    dp4 r4.w, r3, r1  // ::g__worldPos<3>
    dp3 r1.x, r0, r2  // ::g__worldNormal<0>
    dp3 r1.y, r0, r6  // ::g__worldNormal<1>
    dp3 r1.z, r0, r7  // ::g__worldNormal<2>

#line 236
    add r0.xyz, -r4, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 244
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r2.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 295
    dp3_sat r0.x, r1, r0  // calcLambert::Qd<0>

#line 321
    mul r0.xyz, r2, r0.x  // ::Ir<0,1,2>
    if b13

#line 236
      add r2.xyz, -r4, c211  // ::lightVec<0,1,2>
      dp3 r1.w, r2, r2
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r2.xyz, r2, r1.w  // ::lightVec<0,1,2>

#line 244
      add r1.w, r2.w, -c212.x
      max r1.w, r1.w, c186.w  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c212.w
      mad r1.w, r1.w, c212.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r3.xyz, r1.w, c210  // getDynamicPointLight::color<0,1,2>

#line 295
      dp3_sat r1.w, r1, r2  // calcLambert::Qd<0>

#line 326
      mad r0.xyz, r1.w, r3, r0  // ::Ir<0,1,2>

#line 322
    endif

#line 328
    if b14

#line 236
      add r2.xyz, -r4, c214  // ::lightVec<0,1,2>
      dp3 r1.w, r2, r2
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r2.xyz, r2, r1.w  // ::lightVec<0,1,2>

#line 244
      add r1.w, r2.w, -c215.x
      max r1.w, r1.w, c186.w  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c215.w
      mad r1.w, r1.w, c215.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r3.xyz, r1.w, c213  // getDynamicPointLight::color<0,1,2>

#line 295
      dp3_sat r1.w, r1, r2  // calcLambert::Qd<0>

#line 332
      mad r2.xyz, r1.w, r3, r0  // ::Ir<0,1,2>

#line 236
      add r3.xyz, -r4, c217  // ::lightVec<0,1,2>
      dp3 r1.w, r3, r3
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r1.w  // ::lightVec<0,1,2>

#line 244
      add r1.w, r2.w, -c218.x
      max r1.w, r1.w, c186.w  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c218.w
      mad r1.w, r1.w, c218.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r5.xyz, r1.w, c216  // getDynamicPointLight::color<0,1,2>

#line 295
      dp3_sat r1.w, r1, r3  // calcLambert::Qd<0>

#line 335
      mad r0.xyz, r1.w, r5, r2  // ::Ir<0,1,2>

#line 328
    endif

#line 337
    if b15

#line 236
      add r2.xyz, -r4, c220  // ::lightVec<0,1,2>
      dp3 r1.w, r2, r2
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r2.xyz, r2, r1.w  // ::lightVec<0,1,2>

#line 244
      add r1.w, r2.w, -c221.x
      max r1.w, r1.w, c186.w  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c221.w
      mad r1.w, r1.w, c221.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r3.xyz, r1.w, c219  // getDynamicPointLight::color<0,1,2>

#line 295
      dp3_sat r1.w, r1, r2  // calcLambert::Qd<0>

#line 341
      mad r2.xyz, r1.w, r3, r0  // ::Ir<0,1,2>

#line 236
      add r3.xyz, -r4, c223  // ::lightVec<0,1,2>
      dp3 r1.w, r3, r3
      rsq r1.w, r1.w
      rcp r2.w, r1.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r1.w  // ::lightVec<0,1,2>

#line 244
      add r1.w, r2.w, -c224.x
      max r1.w, r1.w, c186.w  // ::lightVecLenPrime<0>
      mul r2.w, r1.w, r1.w
      mul r2.w, r2.w, c224.w
      mad r1.w, r1.w, c224.z, r2.w
      rcp_sat r1.w, r1.w  // ::attenuation<0>
      mul r5.xyz, r1.w, c222  // getDynamicPointLight::color<0,1,2>

#line 295
      dp3_sat r1.w, r1, r3  // calcLambert::Qd<0>

#line 344
      mad r0.xyz, r1.w, r5, r2  // ::Ir<0,1,2>

#line 337
    endif

#line 360
    mul r2, r4.y, c240
    mad r2, r4.x, c239, r2
    mad r2, r4.z, c241, r2
    mad o0, r4.w, c242, r2  // ::main<0,1,2,3>

#line 164
    mov o1, c197  // ::main<4,5,6,7>

#line 354
    mov o2.w, v2.x  // ::main<11>
    mov o2.xyz, r1  // ::main<8,9,10>
    mov o3, r4  // ::main<12,13,14,15>

#line 337
    mov r0.w, -c177.y
    mov o5, r0  // ::main<20,21,22,23>

// approximately 149 instruction slots used
