//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_palettemesh_SL_ADS_Ao_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float3x4 g__matrixPalette[59];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm3;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__matrixPalette         c0     177
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__texXfm3               c188     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c177, 2, -1, 255, 0.5
    def c186, 1, 0, 3, 0.00999999978
    def c187, 31.875, 0, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6,9>
    dcl_texcoord v3  // IN<10,11>
    dcl_texcoord1 v4  // IN<12,13>
    dcl_texcoord3 v5  // IN<14,15>
    dcl_texcoord5 v6  // IN<16,17,18,19>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord4 o6

#line 165 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_palettemesh_SL_ADS_Ao_VtxAtm_WPos_VNorm_8DL.final"
    mad r0.xyz, v1, c177.x, c177.y  // ::g__vertexNormal<0,1,2>
    mad r0.w, v2.w, c177.z, c177.w
    frc r1.x, r0.w
    add r1.y, r0.w, -r1.x
    slt r0.w, r0.w, -r0.w
    slt r1.x, -r1.x, r1.x
    mad r0.w, r0.w, r1.x, r1.y  // ::g__indices<0>

#line 132
    mad r1.xyz, v3.xyxw, c186.xxyw, c186.yyxw
    dp3 o4.x, c182, r1  // ::main<16>
    dp3 o4.y, c183, r1  // ::main<17>
    mad r1.xyz, v4.xyxw, c186.xxyw, c186.yyxw
    dp3 o4.z, c184, r1  // ::main<18>
    dp3 o4.w, c185, r1  // ::main<19>
    mad r1.xyz, v5.xyxw, c186.xxyw, c186.yyxw
    dp3 o5.z, c188, r1  // ::main<22>
    dp3 o5.w, c189, r1  // ::main<23>

#line 189
    mul r1.xyz, v6.w, v6

#line 212
    mul r0.w, r0.w, c186.z
    mova a0.x, r0.w

#line 355
    mov r2, c1[a0.x]  // ::g__matrixPalette<4,5,6,7>
    mul r3, r2, c179.x
    mov r4, c0[a0.x]  // ::g__matrixPalette<0,1,2,3>
    mad r3, r4, c178.x, r3
    mov r5, c2[a0.x]  // ::g__matrixPalette<8,9,10,11>
    mad r3, r5, c180.x, r3
    mov r6.xy, c186
    mad r3, c181.x, r6.yyyx, r3  // ::worldMatrix<0,4,8,12>
    mul r7, r2, c179.y
    mad r7, r4, c178.y, r7
    mad r7, r5, c180.y, r7
    mad r7, c181.y, r6.yyyx, r7  // ::worldMatrix<1,5,9,13>
    mul r8, r2, c179.z
    mad r8, r4, c178.z, r8
    mad r8, r5, c180.z, r8
    mad r8, c181.z, r6.yyyx, r8  // ::worldMatrix<2,6,10,14>
    mul r2, r2, c179.w
    mad r2, r4, c178.w, r2
    mad r2, r5, c180.w, r2
    mad r2, c181.w, r6.yyyx, r2  // ::worldMatrix<3,7,11,15>
    mad r4, v0.xyzx, c186.xxxy, c186.yyyx
    dp4 r5.x, r4, r3  // ::g__worldPos<0>
    dp4 r5.y, r4, r7  // ::g__worldPos<1>
    dp4 r5.z, r4, r8  // ::g__worldPos<2>
    dp4 r5.w, r4, r2  // ::g__worldPos<3>
    dp3 r2.x, r0, r3  // ::g__worldNormal<0>
    dp3 r2.y, r0, r7  // ::g__worldNormal<1>
    dp3 r2.z, r0, r8  // ::g__worldNormal<2>

#line 239
    add r0.xyz, -r5, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 247
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r3.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 298
    dp3_sat r0.x, r2, r0  // calcLambert::Qd<0>

#line 324
    mul r0.xyz, r3, r0.x  // ::Ir<0,1,2>
    if b13

#line 239
      add r3.xyz, -r5, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r1.w, -c212.x
      max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c212.w
      mad r0.w, r0.w, c212.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r2, r3  // calcLambert::Qd<0>

#line 329
      mad r0.xyz, r0.w, r4, r0  // ::Ir<0,1,2>

#line 325
    endif

#line 331
    if b14

#line 239
      add r3.xyz, -r5, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r1.w, -c215.x
      max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c215.w
      mad r0.w, r0.w, c215.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r2, r3  // calcLambert::Qd<0>

#line 335
      mad r3.xyz, r0.w, r4, r0  // ::Ir<0,1,2>

#line 239
      add r4.xyz, -r5, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r1.w, -c218.x
      max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c218.w
      mad r0.w, r0.w, c218.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r6.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r2, r4  // calcLambert::Qd<0>

#line 338
      mad r0.xyz, r0.w, r6, r3  // ::Ir<0,1,2>

#line 331
    endif

#line 340
    if b15

#line 239
      add r3.xyz, -r5, c220  // ::lightVec<0,1,2>
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r1.w, -c221.x
      max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c221.w
      mad r0.w, r0.w, c221.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r4.xyz, r0.w, c219  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r2, r3  // calcLambert::Qd<0>

#line 344
      mad r3.xyz, r0.w, r4, r0  // ::Ir<0,1,2>

#line 239
      add r4.xyz, -r5, c223  // ::lightVec<0,1,2>
      dp3 r0.w, r4, r4
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 247
      add r0.w, r1.w, -c224.x
      max r0.w, r0.w, c186.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c224.w
      mad r0.w, r0.w, c224.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r6.xyz, r0.w, c222  // getDynamicPointLight::color<0,1,2>

#line 298
      dp3_sat r0.w, r2, r4  // calcLambert::Qd<0>

#line 347
      mad r0.xyz, r0.w, r6, r3  // ::Ir<0,1,2>

#line 340
    endif

#line 365
    mad o6.xyz, r1, c187.x, r0  // ::main<24,25,26>
    mul r0, r5.y, c240
    mad r0, r5.x, c239, r0
    mad r0, r5.z, c241, r0
    mad o0, r5.w, c242, r0  // ::main<0,1,2,3>

#line 167
    mov o1, c197  // ::main<4,5,6,7>

#line 357
    mov o2.w, v2.x  // ::main<11>
    mov o2.xyz, r2  // ::main<8,9,10>
    mov o3, r5  // ::main<12,13,14,15>

#line 370
    mov o5.xy, c186.y  // ::main<20,21>

#line 365
    mov o6.w, -c177.y  // ::main<27>

// approximately 154 instruction slots used
