//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_AD_Dn_Ao_VtxAtm_WPos_VNorm_inst.vso
//
//
// Parameters:
//
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm4;
//   row_major float4x4 g__viewProjMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__texXfm0        c182     2
//   g__texXfm1        c184     2
//   g__texXfm4        c190     2
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c0, 2, -1, 1, 0
    def c1, 0.159154937, 0.5, 6.28318548, -3.14159274
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6>
    dcl_texcoord v3  // IN<10,11>
    dcl_texcoord1 v4  // IN<12,13>
    dcl_texcoord4 v5  // IN<14,15>
    dcl_texcoord5 v6  // IN<16,17,18,19>
    dcl_tangent v7  // IN<20,21,22,23>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord3 o6
    dcl_texcoord4 o7
    dcl_texcoord6 o8

#line 132 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_AD_Dn_Ao_VtxAtm_WPos_VNorm_inst.final"
    mad r0.xyz, v3.xyxw, c0.zzww, c0.wwzw
    dp3 o7.x, c182, r0  // ::main<28>
    dp3 o7.y, c183, r0  // ::main<29>
    mad r0.xyz, v4.xyxw, c0.zzww, c0.wwzw
    dp3 o7.z, c184, r0  // ::main<30>
    dp3 o7.w, c185, r0  // ::main<31>
    mad r0.xyz, v5.xyxw, c0.zzww, c0.wwzw
    dp3 o8.x, c190, r0  // ::main<32>
    dp3 o8.y, c191, r0  // ::main<33>

#line 367
    mov r0.xyz, v0
    mov r0.w, v6.y
    dp4 r0.y, r0.ywzx, c0.zzww  // ::g__worldPos<1>

#line 370
    mul r1, r0.y, c240

#line 367
    mov r2.z, v6.x

#line 196
    mad r0.w, v6.w, c1.x, c1.y
    frc r0.w, r0.w
    mad r0.w, r0.w, c1.z, c1.w
    sincos r3.xy, r0.w  // ::sinCos<1,0>

#line 367
    mov r2.xy, r3
    mul r3.xy, r2.yxzw, c0.yzzw
    mad r4.xyz, v0.xzxw, c0.zzww, c0.wwzw
    dp3 r0.x, r4, r2  // ::g__worldPos<0>

#line 370
    mad r1, r0.x, c239, r1

#line 367
    mov r3.z, v6.z
    dp3 r0.z, r4, r3  // ::g__worldPos<2>

#line 370
    mad r1, r0.z, c241, r1

#line 367
    mov o3.xyz, r0  // ::main<12,13,14>

#line 370
    add o0, r1, c242  // ::main<0,1,2,3>
    mov r2.w, c0.w

#line 191
    mad r0, v7, c0.x, c0.y  // ::g__vertexTangent<0,1,2,3>
    nrm r1.xyz, r0  // ::g__vertexTangent<0,1,2>

#line 378
    dp3 o4.x, r1.xzyw, r2.xyww  // ::main<16>

#line 368
    mov r3.w, c0.w

#line 378
    dp3 o6.x, r1.xzyw, r3.xyww  // ::main<24>

#line 168
    mad r0.xyz, v1, c0.x, c0.y  // ::g__vertexNormal<0,1,2>

#line 193
    mul r4.xyz, r1.yzxw, r0.zxyw
    mad r1.xzw, r0.yyzx, r1.zyxy, -r4.xyyz
    mov o5.x, r1.y  // ::main<20>
    mul r1.xyz, r0.w, r1.xzww  // ::g__vertexBinormal<0,1,2>

#line 379
    dp3 o4.y, r1.xzyw, r2.xyww  // ::main<17>

#line 368
    dp3 r2.x, r0.xzyw, r2.xyww  // ::g__worldNormal<0>
    dp3 r2.z, r0.xzyw, r3.xyww  // ::g__worldNormal<2>

#line 379
    dp3 o6.y, r1.xzyw, r3.xyww  // ::main<25>

#line 192
    mov o5.y, r1.y  // ::main<21>

#line 169
    mov o1, c197  // ::main<4,5,6,7>

#line 368
    mov o2.w, v2.x  // ::main<11>
    mad r2.y, v1.y, c0.x, c0.y
    mov o2.xyz, r2  // ::main<8,9,10>

#line 378
    mul o6.zw, r2.xyzx, c0  // ::main<26,27>

#line 192
    mul o5.zw, r2.xyyx, c0  // ::main<22,23>

#line 378
    mul o4.zw, r2.x, c0  // ::main<18,19>

#line 367
    mov o3.w, c0.z  // ::main<15>

#line 132
    mov o8.zw, c0.w  // ::main<34,35>

// approximately 62 instruction slots used
