//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Lit_A_VNorm_WPos_VtxAtm.vso
//
//
// Parameters:
//
//   float4 g__mtlColor;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__worldMatrix    c178     4
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c0, 2, -1, 1, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_texcoord v2  // IN<6,7>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord4 o5

#line 157 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Lit_A_VNorm_WPos_VtxAtm.final"
    mad r0.xyz, v1, c0.x, c0.y  // ::g__vertexNormal<0,1,2>

#line 347
    mul r1.xyz, r0.y, c179
    mad r0.xyw, r0.x, c178.xyzz, r1.xyzz
    mad o2.xyz, r0.z, c180, r0.xyww  // ::main<8,9,10>
    mul r0, c179, v0.y
    mad r0, v0.x, c178, r0
    mad r0, v0.z, c180, r0
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>

#line 349
    mul r1, r0.y, c240
    mad r1, r0.x, c239, r1
    mad r1, r0.z, c241, r1
    mad o0, r0.w, c242, r1  // ::main<0,1,2,3>

#line 346
    mov o3, r0  // ::main<11,12,13,14>

#line 158
    mov o1, c197  // ::main<4,5,6,7>

#line 367
    mul o4, c0.zzww, v2.xyxx  // ::main<15,16,17,18>

#line 355
    mov o5, c0.wwwz  // ::main<19,20,21,22>

// approximately 16 instruction slots used
