//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_palettemesh_SL_ADNS_Ao_VtxAtm_WPos_VNorm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   row_major float3x4 g__matrixPalette[59];
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm2;
//   row_major float2x4 g__texXfm3;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__matrixPalette         c0     177
//   g__worldMatrix           c178     4
//   g__texXfm0               c182     2
//   g__texXfm1               c184     2
//   g__texXfm2               c186     2
//   g__texXfm3               c188     2
//   g__mtlColor              c197     1
//   g__dynamicLightingLights c207    18
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c177, 2, -1, 255, 0.5
    def c190, 1, 0, 3, 0.00999999978
    def c191, 31.875, 0, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color1 v2  // IN<6,9>
    dcl_texcoord v3  // IN<10,11>
    dcl_texcoord1 v4  // IN<12,13>
    dcl_texcoord2 v5  // IN<14,15>
    dcl_texcoord3 v6  // IN<16,17>
    dcl_texcoord5 v7  // IN<18,19,20,21>
    dcl_tangent v8  // IN<22,23,24,25>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord3 o6
    dcl_texcoord4 o7
    dcl_texcoord5 o8

#line 169 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_palettemesh_SL_ADNS_Ao_VtxAtm_WPos_VNorm_8DL.final"
    mad r0.xyz, v1, c177.x, c177.y  // ::g__vertexNormal<0,1,2>
    mad r0.w, v2.w, c177.z, c177.w
    frc r1.x, r0.w
    add r1.y, r0.w, -r1.x
    slt r0.w, r0.w, -r0.w
    slt r1.x, -r1.x, r1.x
    mad r0.w, r0.w, r1.x, r1.y  // ::g__indices<0>

#line 132
    mad r1.xyz, v3.xyxw, c190.xxyw, c190.yyxw
    dp3 o7.x, c182, r1  // ::main<28>
    dp3 o7.y, c183, r1  // ::main<29>
    mad r1.xyz, v4.xyxw, c190.xxyw, c190.yyxw
    dp3 o7.z, c184, r1  // ::main<30>
    dp3 o7.w, c185, r1  // ::main<31>
    mad r1.xyz, v5.xyxw, c190.xxyw, c190.yyxw
    dp3 o8.x, c186, r1  // ::main<32>
    dp3 o8.y, c187, r1  // ::main<33>
    mad r1.xyz, v6.xyxw, c190.xxyw, c190.yyxw
    dp3 o8.z, c188, r1  // ::main<34>
    dp3 o8.w, c189, r1  // ::main<35>

#line 193
    mad r1, v8, c177.x, c177.y  // ::g__vertexTangent<0,1,2,3>
    nrm r2.xyz, r1  // ::g__vertexTangent<0,1,2>
    mul r1.xyz, r0.zxyw, r2.yzxw
    mad r1.xyz, r0.yzxw, r2.zxyw, -r1
    mul r1.xyz, r1.w, r1  // ::g__vertexBinormal<0,1,2>
    mul r3.xyz, v7.w, v7

#line 219
    mul r0.w, r0.w, c190.z
    mova a0.x, r0.w

#line 362
    mov r4, c1[a0.x]  // ::g__matrixPalette<4,5,6,7>
    mul r5, r4, c179.x
    mov r6, c0[a0.x]  // ::g__matrixPalette<0,1,2,3>
    mad r5, r6, c178.x, r5
    mov r7, c2[a0.x]  // ::g__matrixPalette<8,9,10,11>
    mad r5, r7, c180.x, r5
    mov r8.xy, c190
    mad r5, c181.x, r8.yyyx, r5  // ::worldMatrix<0,4,8,12>
    mul r9, r4, c179.y
    mad r9, r6, c178.y, r9
    mad r9, r7, c180.y, r9
    mad r9, c181.y, r8.yyyx, r9  // ::worldMatrix<1,5,9,13>
    mul r10, r4, c179.z
    mad r10, r6, c178.z, r10
    mad r10, r7, c180.z, r10
    mad r10, c181.z, r8.yyyx, r10  // ::worldMatrix<2,6,10,14>
    mul r4, r4, c179.w
    mad r4, r6, c178.w, r4
    mad r4, r7, c180.w, r4
    mad r4, c181.w, r8.yyyx, r4  // ::worldMatrix<3,7,11,15>
    mad r6, v0.xyzx, c190.xxxy, c190.yyyx
    dp4 r7.x, r6, r5  // ::g__worldPos<0>
    dp4 r7.y, r6, r9  // ::g__worldPos<1>
    dp4 r7.z, r6, r10  // ::g__worldPos<2>
    dp4 r7.w, r6, r4  // ::g__worldPos<3>
    dp3 r4.x, r0, r5  // ::g__worldNormal<0>
    dp3 r4.y, r0, r9  // ::g__worldNormal<1>
    dp3 r4.z, r0, r10  // ::g__worldNormal<2>

#line 246
    add r0.xyz, -r7, c208  // ::lightVec<0,1,2>
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::lightVecLen<0>
    mul r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 254
    add r0.w, r1.w, -c209.x
    max r0.w, r0.w, c190.w  // ::lightVecLenPrime<0>
    mul r1.w, r0.w, r0.w
    mul r1.w, r1.w, c209.w
    mad r0.w, r0.w, c209.z, r1.w
    rcp_sat r0.w, r0.w  // ::attenuation<0>
    mul r6.xyz, r0.w, c207  // getDynamicPointLight::color<0,1,2>

#line 305
    dp3_sat r0.x, r4, r0  // calcLambert::Qd<0>

#line 331
    mul r0.xyz, r6, r0.x  // ::Ir<0,1,2>
    if b13

#line 246
      add r6.xyz, -r7, c211  // ::lightVec<0,1,2>
      dp3 r0.w, r6, r6
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 254
      add r0.w, r1.w, -c212.x
      max r0.w, r0.w, c190.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c212.w
      mad r0.w, r0.w, c212.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r8.xyz, r0.w, c210  // getDynamicPointLight::color<0,1,2>

#line 305
      dp3_sat r0.w, r4, r6  // calcLambert::Qd<0>

#line 336
      mad r0.xyz, r0.w, r8, r0  // ::Ir<0,1,2>

#line 332
    endif

#line 338
    if b14

#line 246
      add r6.xyz, -r7, c214  // ::lightVec<0,1,2>
      dp3 r0.w, r6, r6
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 254
      add r0.w, r1.w, -c215.x
      max r0.w, r0.w, c190.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c215.w
      mad r0.w, r0.w, c215.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r8.xyz, r0.w, c213  // getDynamicPointLight::color<0,1,2>

#line 305
      dp3_sat r0.w, r4, r6  // calcLambert::Qd<0>

#line 342
      mad r6.xyz, r0.w, r8, r0  // ::Ir<0,1,2>

#line 246
      add r8.xyz, -r7, c217  // ::lightVec<0,1,2>
      dp3 r0.w, r8, r8
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r8.xyz, r8, r0.w  // ::lightVec<0,1,2>

#line 254
      add r0.w, r1.w, -c218.x
      max r0.w, r0.w, c190.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c218.w
      mad r0.w, r0.w, c218.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r11.xyz, r0.w, c216  // getDynamicPointLight::color<0,1,2>

#line 305
      dp3_sat r0.w, r4, r8  // calcLambert::Qd<0>

#line 345
      mad r0.xyz, r0.w, r11, r6  // ::Ir<0,1,2>

#line 338
    endif

#line 347
    if b15

#line 246
      add r6.xyz, -r7, c220  // ::lightVec<0,1,2>
      dp3 r0.w, r6, r6
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 254
      add r0.w, r1.w, -c221.x
      max r0.w, r0.w, c190.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c221.w
      mad r0.w, r0.w, c221.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r8.xyz, r0.w, c219  // getDynamicPointLight::color<0,1,2>

#line 305
      dp3_sat r0.w, r4, r6  // calcLambert::Qd<0>

#line 351
      mad r6.xyz, r0.w, r8, r0  // ::Ir<0,1,2>

#line 246
      add r8.xyz, -r7, c223  // ::lightVec<0,1,2>
      dp3 r0.w, r8, r8
      rsq r0.w, r0.w
      rcp r1.w, r0.w  // ::lightVecLen<0>
      mul r8.xyz, r8, r0.w  // ::lightVec<0,1,2>

#line 254
      add r0.w, r1.w, -c224.x
      max r0.w, r0.w, c190.w  // ::lightVecLenPrime<0>
      mul r1.w, r0.w, r0.w
      mul r1.w, r1.w, c224.w
      mad r0.w, r0.w, c224.z, r1.w
      rcp_sat r0.w, r0.w  // ::attenuation<0>
      mul r11.xyz, r0.w, c222  // getDynamicPointLight::color<0,1,2>

#line 305
      dp3_sat r0.w, r4, r8  // calcLambert::Qd<0>

#line 354
      mad r0.xyz, r0.w, r11, r6  // ::Ir<0,1,2>

#line 347
    endif

#line 372
    mad r0.xyz, r3, c191.x, r0  // ::Ir<0,1,2>
    mul r3, r7.y, c240
    mad r3, r7.x, c239, r3
    mad r3, r7.z, c241, r3
    mad o0, r7.w, c242, r3  // ::main<0,1,2,3>

#line 382
    dp3 o4.x, r2, r5  // ::main<16>
    dp3 o5.x, r2, r9  // ::main<20>
    dp3 o6.x, r2, r10  // ::main<24>
    dp3 o4.y, r1, r5  // ::main<17>
    dp3 o5.y, r1, r9  // ::main<21>
    dp3 o6.y, r1, r10  // ::main<25>

#line 171
    mov o1, c197  // ::main<4,5,6,7>

#line 364
    mov o2.w, v2.x  // ::main<11>
    mov o2.xyz, r4  // ::main<8,9,10>
    mov o3, r7  // ::main<12,13,14,15>

#line 382
    mov o4.z, r4.x  // ::main<18>
    mov o4.w, r0.x  // ::main<19>
    mov o5.z, r4.y  // ::main<22>
    mov o5.w, r0.y  // ::main<23>
    mov o6.z, r4.z  // ::main<26>
    mov o6.w, r0.z  // ::main<27>

// approximately 174 instruction slots used
