//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Water_A_T1_T2_T3_T4_WPos_ProjPos_VNorm_VtxAtm_8DL.vso
//
//
// Parameters:
//
//   bool g__dynamicLightingBools[4];
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__gerstnerWaveAmplitude;
//   float4 g__gerstnerWaveLength;
//   float4 g__gerstnerWavePhase;
//   float4 g__gerstnerWaveSel;
//   float4 g__gerstnerWaveVectors[2];
//   float4 g__time;
//   row_major float4x4 g__viewProjMatrix;
//   float4 g__waterUvOffsets[2];
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__dynamicLightingBools  b12      4
//   g__worldMatrix           c178     4
//   g__time                  c196     1
//   g__dynamicLightingLights c207    18
//   g__gerstnerWaveVectors   c231     2
//   g__gerstnerWaveAmplitude c233     1
//   g__gerstnerWaveLength    c234     1
//   g__gerstnerWavePhase     c235     1
//   g__gerstnerWaveSel       c236     1
//   g__waterUvOffsets        c237     2
//   g__viewProjMatrix        c239     4
//

    vs_3_0
    def c0, 6.28318548, 61.5752144, 0.159154937, 0.25
    def c1, 0.159154937, 0.5, 6.28318548, -3.14159274
    def c2, -2.52398507e-007, 2.47609005e-005, -0.00138883968, 0.0416666418
    def c3, 1, -1, 0, 0.00999999978
    dcl_position v0  // IN<0,1,2>
    dcl_texcoord v1  // IN<3,4>
    dcl_texcoord1 v2  // IN<5,6>
    dcl_texcoord2 v3  // IN<7,8>
    dcl_texcoord3 v4  // IN<9,10>
    dcl_texcoord4 v5  // IN<11,12>
    dcl_position o0
    dcl_texcoord o1
    dcl_texcoord1 o2
    dcl_texcoord2 o3
    dcl_texcoord3 o4
    dcl_texcoord4 o5
    dcl_texcoord5 o6.xy
    dcl_texcoord6 o7
    dcl_texcoord9 o8

#line 385 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Water_A_T1_T2_T3_T4_WPos_ProjPos_VNorm_VtxAtm_8DL.final"
    mul r0, c179, v0.y
    mad r0, v0.x, c178, r0
    mad r0, v0.z, c180, r0
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>

#line 350
    rcp r1.x, c234.x
    rcp r1.y, c234.y
    rcp r1.z, c234.z
    rcp r1.w, c234.w
    mul r2, r1, c0.x  // ::k<0,1,2,3>
    mul r1, r1, c0.y
    rsq r1.x, r1.x
    rsq r1.y, r1.y
    rsq r1.z, r1.z
    rsq r1.w, r1.w
    rcp r3.x, r1.x  // ::w<0>
    rcp r3.y, r1.y  // ::w<1>
    rcp r3.z, r1.z  // ::w<2>
    rcp r3.w, r1.w  // ::w<3>

#line 355
    mul r1, r0.xzxz, c231
    add r1.xy, r1.ywzw, r1.xzzw  // ::theta<0,1>
    mul r4, r0.xzxz, c232
    add r1.zw, r4.xyyw, r4.xyxz  // ::theta<2,3>
    mov r4.y, c196.y  // ::g__time<1>
    mad r3, r3, r4.y, c235
    add r1, r1, -r3  // ::theta<0,1,2,3>
    mad r3, r1, c0.z, c0.w
    mad r1, r1, c1.x, c1.y
    frc r3, r3
    frc r1, r1
    mad r3, r3, c1.z, c1.w
    mad r1, r1, c1.z, c1.w
    mul r3, r3, r3
    mul r1, r1, r1
    mad r4, r3, c2.x, c2.y
    mad r5, r1, c2.x, c2.y
    mad r4, r3, r4, c2.z
    mad r5, r1, r5, c2.z
    mad r4, r3, r4, c2.w
    mad r5, r1, r5, c2.w
    mad r4, r3, r4, -c1.y
    mad r5, r1, r5, -c1.y
    mad r3, r3, r4, c3.x  // ::sinTheta<0,1,2,3>
    mad r1, r1, r5, c3.x  // ::cosTheta<0,1,2,3>
    mul r3, r3, c236  // ::sinTheta<0,1,2,3>
    mul r1, r1, c236  // ::cosTheta<0,1,2,3>

#line 337
    rcp r2.x, r2.x
    mul r4.xy, r2.x, c231
    mul r4.xy, r4, c233.x
    mul r5.xz, r3.x, r4.xyyw  // ::waveContrib<0,2>
    rcp r2.x, r2.y
    mul r2.xy, r2.x, c231.zwzw
    mul r2.xy, r2, c233.y
    mul r6.xz, r3.y, r2.xyyw  // ::waveContrib<0,2>
    mul r7, r1.xzyw, c233.xzyw  // ::waveContrib<1,1,1,1>

#line 365
    mov r5.y, r7.x
    mov r6.y, r7.z
    add r5.xyz, r5, r6  // ::cumaliativeWavePos<0,1,2>

#line 337
    rcp r2.z, r2.z
    mul r4.zw, r2.z, c232.xyxy
    mul r4.zw, r4, c233.z
    mul r7.xz, r3.z, r4.zyww  // ::waveContrib<0,2>

#line 366
    add r5.xyz, r5, r7  // ::cumaliativeWavePos<0,1,2>

#line 337
    rcp r2.z, r2.w
    mul r2.zw, r2.z, c232
    mul r2.zw, r2, c233.w
    mul r7.xz, r3.w, r2.zyww  // ::waveContrib<0,2>

#line 367
    add r5.xyz, r5, r7.xwzw  // ::cumaliativeWavePos<0,1,2>

#line 344
    mul r4.xy, r4, c231
    mul r6.xz, r1.x, r4.xyyw  // ::waveContrib<0,2>
    mov r7, c233  // ::g__gerstnerWaveAmplitude<0,1,2,3>
    mul r8, r7.xxyy, c231
    mul r2.xy, r2, c231.zwzw
    mul r9.xz, r1.y, r2.xyyw  // ::waveContrib<0,2>
    mul r8, -r3.xxyy, r8  // ::waveContrib<1,3,1,3>

#line 370
    mov r6.yw, r8.xxzy
    mov r9.yw, r8.xzzw
    add r6, r6, r9  // ::cumaliativeWaveDeriv<0,1,2,3>

#line 344
    mul r1.xy, r4.zwzw, c232
    mul r4.xz, r1.z, r1.xyyw  // ::waveContrib<0,2>
    mul r7, r7.zzww, c232
    mul r3, -r3.zwzw, r7.xzyw  // ::waveContrib<1,1,3,3>

#line 371
    mov r4.yw, r3.xxzz
    add r4, r6, r4  // ::cumaliativeWaveDeriv<0,1,2,3>

#line 344
    mul r1.xy, r2.zwzw, c232.zwzw
    mul r3.xz, r1.w, r1.xyyw  // ::waveContrib<0,2>

#line 372
    add r1, r4, r3  // ::cumaliativeWaveDeriv<0,1,2,3>
    add r2.xz, r0, -r5  // ::perturbedPos<0,2>
    add r2.y, r0.y, r5.y  // ::perturbedPos<1>

#line 391
    mad r0.xyz, r1.zwww, c3.yzxw, c3.xzzw
    dp3 r1.z, r0, r0
    rsq r1.z, r1.z
    mul r3.xyz, r0.yxzw, r1.z  // ::gerstnerTangent<0,2,1>
    mad r0.xyz, r1.ywxw, c3.xzyw, c3.zzxw
    dp3 r1.x, r0, r0
    rsq r1.x, r1.x
    mul r1.xyz, r0.yzxw, r1.x  // ::gerstnerBinormal<2,0,1>
    mul r0.xyz, r3.yxzw, r1.zxyw
    mad r0.xyz, r3.zyxw, r1, -r0
    nrm r4.xyz, r0  // ::g__worldNormal<0,1,2>

#line 222
    add r0.xyz, -r2, c208  // ::lightVec<0,1,2>
    dp3 r2.w, r0, r0
    rsq r2.w, r2.w
    rcp r4.w, r2.w  // ::lightVecLen<0>
    mul r0.xyz, r0, r2.w  // ::lightVec<0,1,2>

#line 230
    add r2.w, r4.w, -c209.x
    max r2.w, r2.w, c3.w  // ::lightVecLenPrime<0>
    mul r4.w, r2.w, r2.w
    mul r4.w, r4.w, c209.w
    mad r2.w, r2.w, c209.z, r4.w
    rcp_sat r2.w, r2.w  // ::attenuation<0>
    mul r5.xyz, r2.w, c207  // getDynamicPointLight::color<0,1,2>

#line 281
    dp3_sat r0.x, r4, r0  // calcLambert::Qd<0>

#line 307
    mul r5.xyz, r5, r0.x  // ::Ir<0,1,2>
    if b13

#line 222
      add r0.xyz, -r2, c211  // ::lightVec<0,1,2>
      dp3 r2.w, r0, r0
      rsq r2.w, r2.w
      rcp r4.w, r2.w  // ::lightVecLen<0>
      mul r0.xyz, r0, r2.w  // ::lightVec<0,1,2>

#line 230
      add r2.w, r4.w, -c212.x
      max r2.w, r2.w, c3.w  // ::lightVecLenPrime<0>
      mul r4.w, r2.w, r2.w
      mul r4.w, r4.w, c212.w
      mad r2.w, r2.w, c212.z, r4.w
      rcp_sat r2.w, r2.w  // ::attenuation<0>
      mul r6.xyz, r2.w, c210  // getDynamicPointLight::color<0,1,2>

#line 281
      dp3_sat r0.x, r4, r0  // calcLambert::Qd<0>

#line 312
      mad r5.xyz, r0.x, r6, r5  // ::Ir<0,1,2>

#line 308
    endif

#line 314
    if b14

#line 222
      add r0.xyz, -r2, c214  // ::lightVec<0,1,2>
      dp3 r2.w, r0, r0
      rsq r2.w, r2.w
      rcp r4.w, r2.w  // ::lightVecLen<0>
      mul r0.xyz, r0, r2.w  // ::lightVec<0,1,2>

#line 230
      add r2.w, r4.w, -c215.x
      max r2.w, r2.w, c3.w  // ::lightVecLenPrime<0>
      mul r4.w, r2.w, r2.w
      mul r4.w, r4.w, c215.w
      mad r2.w, r2.w, c215.z, r4.w
      rcp_sat r2.w, r2.w  // ::attenuation<0>
      mul r6.xyz, r2.w, c213  // getDynamicPointLight::color<0,1,2>

#line 281
      dp3_sat r0.x, r4, r0  // calcLambert::Qd<0>

#line 318
      mad r0.xyz, r0.x, r6, r5  // ::Ir<0,1,2>

#line 222
      add r6.xyz, -r2, c217  // ::lightVec<0,1,2>
      dp3 r2.w, r6, r6
      rsq r2.w, r2.w
      rcp r4.w, r2.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r2.w  // ::lightVec<0,1,2>

#line 230
      add r2.w, r4.w, -c218.x
      max r2.w, r2.w, c3.w  // ::lightVecLenPrime<0>
      mul r4.w, r2.w, r2.w
      mul r4.w, r4.w, c218.w
      mad r2.w, r2.w, c218.z, r4.w
      rcp_sat r2.w, r2.w  // ::attenuation<0>
      mul r7.xyz, r2.w, c216  // getDynamicPointLight::color<0,1,2>

#line 281
      dp3_sat r2.w, r4, r6  // calcLambert::Qd<0>

#line 321
      mad r5.xyz, r2.w, r7, r0  // ::Ir<0,1,2>

#line 314
    endif

#line 323
    if b15

#line 222
      add r0.xyz, -r2, c220  // ::lightVec<0,1,2>
      dp3 r2.w, r0, r0
      rsq r2.w, r2.w
      rcp r4.w, r2.w  // ::lightVecLen<0>
      mul r0.xyz, r0, r2.w  // ::lightVec<0,1,2>

#line 230
      add r2.w, r4.w, -c221.x
      max r2.w, r2.w, c3.w  // ::lightVecLenPrime<0>
      mul r4.w, r2.w, r2.w
      mul r4.w, r4.w, c221.w
      mad r2.w, r2.w, c221.z, r4.w
      rcp_sat r2.w, r2.w  // ::attenuation<0>
      mul r6.xyz, r2.w, c219  // getDynamicPointLight::color<0,1,2>

#line 281
      dp3_sat r0.x, r4, r0  // calcLambert::Qd<0>

#line 327
      mad r0.xyz, r0.x, r6, r5  // ::Ir<0,1,2>

#line 222
      add r6.xyz, -r2, c223  // ::lightVec<0,1,2>
      dp3 r2.w, r6, r6
      rsq r2.w, r2.w
      rcp r4.w, r2.w  // ::lightVecLen<0>
      mul r6.xyz, r6, r2.w  // ::lightVec<0,1,2>

#line 230
      add r2.w, r4.w, -c224.x
      max r2.w, r2.w, c3.w  // ::lightVecLenPrime<0>
      mul r4.w, r2.w, r2.w
      mul r4.w, r4.w, c224.w
      mad r2.w, r2.w, c224.z, r4.w
      rcp_sat r2.w, r2.w  // ::attenuation<0>
      mul r7.xyz, r2.w, c222  // getDynamicPointLight::color<0,1,2>

#line 281
      dp3_sat r2.w, r4, r6  // calcLambert::Qd<0>

#line 330
      mad r5.xyz, r2.w, r7, r0  // ::Ir<0,1,2>

#line 323
      mov r1.x, r5.y  // ::Ir<1>
      mov r3.x, r5.z  // ::Ir<2>
    else
      mov r1.x, r5.y  // ::Ir<1>
      mov r3.x, r5.z  // ::Ir<2>
    endif

#line 399
    mul r6, r2.y, c240
    mad r6, r2.x, c239, r6
    mad r6, r2.z, c241, r6
    mad r6, r0.w, c242, r6  // ::OUT<0,1,2,3>

#line 402
    add o4.xy, c237, v1  // ::main<16,17>
    add o4.zw, c237, v2.xyxy  // ::main<18,19>

#line 407
    add o5.xy, c238, v3  // ::main<20,21>
    add o5.zw, c238, v4.xyxy  // ::main<22,23>

#line 399
    mov o0, r6  // ::main<0,1,2,3>

#line 391
    mov r5.y, c3.z
    mov r5.z, r1.y
    mov r5.w, r4.x
    mov o1, r5.yzwx  // ::main<4,5,6,7>
    mov r1.y, r3.z
    mov r1.w, r4.y
    mov o2, r1.yzwx  // ::main<8,9,10,11>
    mov r3.z, c3.z
    mov r3.w, r4.z
    mov o3, r3.yzwx  // ::main<12,13,14,15>

#line 435
    mov o6.xy, v5  // ::main<24,25>

#line 374
    mov o7.w, r0.w  // ::main<29>
    mov o7.xyz, r2  // ::main<26,27,28>

#line 399
    mov o8, r6  // ::main<30,31,32,33>

// approximately 225 instruction slots used
