//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_2DNorm_T0.vso
//
//
// Parameters:
//
//   float4 g__invViewport;
//   float4 g__viewPort;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g__viewPort    c247     1
//   g__invViewport c248     1
//

    vs_3_0
    def c0, 0.5, -0.5, 0, 1
    dcl_position v0  // IN<0,1>
    dcl_texcoord v1  // IN<3,4>
    dcl_position o0
    dcl_texcoord o1.xy

#line 318 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_2DNorm_T0.final"
    mad r0.xy, v0, c0, c0.x  // ::uvPos<0,1>
    mov r1.y, c0.y
    mad r0.xy, r0, c247.zwzw, r1.y  // ::offsetScreenScaledPos<0,1>
    mad o0.xy, r0, c248, c248.zwzw  // ::main<0,1>
    mov o0.zw, c0  // ::main<2,3>

#line 335
    mov o1.xy, v1  // ::main<4,5>

// approximately 6 instruction slots used
