//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_ADS_Dn_Vd_Ao_VtxAtm_WPos_VNorm_inst.vso
//
//
// Parameters:
//
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm3;
//   row_major float2x4 g__texXfm4;
//   row_major float4x4 g__viewProjMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__texXfm0        c182     2
//   g__texXfm1        c184     2
//   g__texXfm3        c188     2
//   g__texXfm4        c190     2
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c0, 0.159154937, 0.5, 6.28318548, -3.14159274
    def c1, 2, -1, 1, 0
    dcl_position v0  // IN<0,1,2>
    dcl_normal v1  // IN<3,4,5>
    dcl_color v2  // IN<6,7,8,9>
    dcl_color1 v3  // IN<10>
    dcl_texcoord v4  // IN<14,15>
    dcl_texcoord1 v5  // IN<16,17>
    dcl_texcoord3 v6  // IN<18,19>
    dcl_texcoord4 v7  // IN<20,21>
    dcl_texcoord5 v8  // IN<22,23,24,25>
    dcl_tangent v9  // IN<26,27,28,29>
    dcl_position o0
    dcl_color o1
    dcl_normal o2
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord3 o6
    dcl_texcoord4 o7
    dcl_texcoord5 o8
    dcl_texcoord6 o9

#line 173 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_ADS_Dn_Vd_Ao_VtxAtm_WPos_VNorm_inst.final"
    mul o1, c197, v2  // ::main<4,5,6,7>

#line 132
    mad r0.xyz, v4.xyxw, c1.zzww, c1.wwzw
    dp3 o7.x, c182, r0  // ::main<28>
    dp3 o7.y, c183, r0  // ::main<29>
    mad r0.xyz, v5.xyxw, c1.zzww, c1.wwzw
    dp3 o7.z, c184, r0  // ::main<30>
    dp3 o7.w, c185, r0  // ::main<31>
    mad r0.xyz, v6.xyxw, c1.zzww, c1.wwzw
    dp3 o8.z, c188, r0  // ::main<34>
    dp3 o8.w, c189, r0  // ::main<35>
    mad r0.xyz, v7.xyxw, c1.zzww, c1.wwzw
    dp3 o9.x, c190, r0  // ::main<36>
    dp3 o9.y, c191, r0  // ::main<37>

#line 371
    mov r0.xyz, v0
    mov r0.w, v8.y
    dp4 r0.y, r0.ywzx, c1.zzww  // ::g__worldPos<1>

#line 374
    mul r1, r0.y, c240

#line 371
    mov r2.z, v8.x

#line 200
    mad r0.w, v8.w, c0.x, c0.y
    frc r0.w, r0.w
    mad r0.w, r0.w, c0.z, c0.w
    sincos r3.xy, r0.w  // ::sinCos<1,0>

#line 371
    mov r2.xy, r3
    mul r3.xy, r2.yxzw, c1.yzzw
    mad r4.xyz, v0.xzxw, c1.zzww, c1.wwzw
    dp3 r0.x, r4, r2  // ::g__worldPos<0>

#line 374
    mad r1, r0.x, c239, r1

#line 371
    mov r3.z, v8.z
    dp3 r0.z, r4, r3  // ::g__worldPos<2>

#line 374
    mad r1, r0.z, c241, r1

#line 371
    mov o3.xyz, r0  // ::main<12,13,14>

#line 374
    add o0, r1, c242  // ::main<0,1,2,3>
    mov r2.w, c1.w

#line 195
    mad r0, v9, c1.x, c1.y  // ::g__vertexTangent<0,1,2,3>
    nrm r1.xyz, r0  // ::g__vertexTangent<0,1,2>

#line 384
    dp3 o4.x, r1.xzyw, r2.xyww  // ::main<16>

#line 372
    mov r3.w, c1.w

#line 384
    dp3 o6.x, r1.xzyw, r3.xyww  // ::main<24>

#line 171
    mad r0.xyz, v1, c1.x, c1.y  // ::g__vertexNormal<0,1,2>

#line 197
    mul r4.xyz, r1.yzxw, r0.zxyw
    mad r1.xzw, r0.yyzx, r1.zyxy, -r4.xyyz
    mov o5.x, r1.y  // ::main<20>
    mul r1.xyz, r0.w, r1.xzww  // ::g__vertexBinormal<0,1,2>

#line 385
    dp3 o4.y, r1.xzyw, r2.xyww  // ::main<17>

#line 372
    dp3 r2.x, r0.xzyw, r2.xyww  // ::g__worldNormal<0>
    dp3 r2.z, r0.xzyw, r3.xyww  // ::g__worldNormal<2>

#line 385
    dp3 o6.y, r1.xzyw, r3.xyww  // ::main<25>

#line 196
    mov o5.y, r1.y  // ::main<21>

#line 372
    mov o2.w, v3.x  // ::main<11>
    mad r2.y, v1.y, c1.x, c1.y
    mov o2.xyz, r2  // ::main<8,9,10>

#line 384
    mul o6.zw, r2.xyzx, c1  // ::main<26,27>

#line 196
    mul o5.zw, r2.xyyx, c1  // ::main<22,23>

#line 384
    mul o4.zw, r2.x, c1  // ::main<18,19>

#line 371
    mov o3.w, c1.z  // ::main<15>

#line 377
    mov o8.xy, c1.w  // ::main<32,33>

#line 132
    mov o9.zw, c1.w  // ::main<38,39>

// approximately 66 instruction slots used
