//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Z_SpeedTree_LeafCard_A.vso
//
//
// Parameters:
//
//   float2 g__leafAngleVec[2];
//   float4 g__speedTreeAlphaRefs;
//   float4 g__sunDir;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float3x4 g__windMat[3];
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   g__windMat            c0       9
//   g__leafAngleVec       c9       1
//   g__speedTreeAlphaRefs c23      1
//   g__worldMatrix        c178     4
//   g__viewProjMatrix     c239     4
//   g__sunDir             c251     1
//

    vs_3_0
    def c15, 255, 0.00784313772, 0.00392156886, 0.333333343
    def c16, 3, 0.0159154944, 0.5, 0
    def c17, 6.28318548, -3.14159274, -1, 0
    def c11, 1, 0, 0, 0
    def c12, 0, 1, 0, 0
    def c13, 0, 0, 1, 0
    def c14, 0, 0, 0, 1
    dcl_position v0  // IN<0,1,2>
    dcl_color v1  // IN<6>
    dcl_blendindices v2  // IN<7,9>
    dcl_texcoord v3  // IN<11,12>
    dcl_binormal v4  // IN<13,14,15>
    dcl_position o0
    dcl_texcoord o1

#line 168 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Z_SpeedTree_LeafCard_A.final"
    slt r0.x, v2.z, -v2.z
    frc r0.y, v2.z
    add r0.z, -r0.y, v2.z
    slt r0.y, -r0.y, r0.y
    mad r0.x, r0.x, r0.y, r0.z  // ::g__indices<0>

#line 312
    mul r0.x, r0.x, c15.w
    frc r0.y, r0_abs.x
    sge r0.x, r0.x, -r0.x
    lrp r1.x, r0.x, r0.y, -r0.y
    mul r0.x, r1.x, c16.x
    frc r0.y, r0.x
    add r0.z, r0.x, -r0.y
    slt r0.x, r0.x, -r0.x
    slt r0.y, -r0.y, r0.y
    mad r0.x, r0.x, r0.y, r0.z  // ::modInd<0>
    mul r0.x, r0.x, c16.x
    mova a0.x, r0.x

#line 320
    mul r0.xyz, c179, v0.y
    mad r0.xyz, v0.x, c178, r0
    mad r0.xyz, v0.z, c180, r0  // ::g__worldPos<0,1,2>

#line 313
    mul r1.xyz, r0.y, c1[a0.x]
    mad r1.xyz, r0.x, c0[a0.x], r1
    mad r1.xyz, r0.z, c2[a0.x], r1  // ::windPos<0,1,2>

#line 167
    mul r0.w, v2.x, c15.z  // ::g__weights<0>

#line 314
    lrp r2.xyz, r0.w, r1, r0  // ::windEffect<0,1,2>

#line 327
    add r0.xyz, r2, c181  // ::g__worldPos<0,1,2>

#line 330
    mov r1.xyz, c251  // ::g__sunDir<0,1,2>
    mul r2.xyz, r1.zxyw, c17.zwww
    mad r1.xyz, r1.yzxw, c17.wwzw, -r2
    nrm r2.xyz, r1  // ::camRight<0,1,2>
    mul r1.xyz, r2.zxyw, -c251.yzxw
    mad r1.xyz, r2.yzxw, -c251.zxyw, -r1
    nrm r3.xyz, r1  // ::camUp<0,1,2>
    mul r1.xyz, r3, v4.y
    mad r1.xyz, v4.x, r2, r1
    mad r1.xyz, v4.z, -c251, r1  // ::offset<0,1,2>

#line 180
    mov r2.yz, c16
    mad r2.xy, c9.yxzw, r2.y, r2.z
    frc r2.xy, r2
    mad r2.xy, r2, c17.x, c17.y
    sincos r3.xy, r2.y  // ::sinCos<1,0>

#line 186
    sincos r4.xy, r2.x  // ::sinCos<1,0>

#line 334
    mov r2.y, r3.x

#line 326
    mul r5.xy, r3, r4  // ::rockRustleMat<0,7>

#line 334
    mov r2.z, r5.y

#line 326
    mul r2.x, -r3.y, r4.x  // ::rockRustleMat<1>

#line 334
    dp3 r2.y, r1, r2  // ::offset<1>

#line 326
    mul r5.z, r3.x, -r4.y  // ::rockRustleMat<6>

#line 334
    mul r3.xzw, r4.yyyx, c11.xyyx
    dp3 r2.z, r1, r3.xzww  // ::offset<2>
    mov r5.w, r3.y
    dp3 r2.x, r1.xzyw, r5.xzww  // ::offset<0>
    add r0.xyz, r0, r2  // ::g__worldPos<0,1,2>
    mul r1, r0.y, c240
    mad r1, r0.x, c239, r1
    mad r0, r0.z, c241, r1
    add o0, r0, c242  // ::main<0,1,2,3>

#line 161
    mad r0.x, v1.w, c15.x, c15.y  // ::g__vertexDiffuse<3>

#line 340
    frc r0.y, r0.x
    add r0.x, r0.x, -r0.y
    mova a0.x, r0.x
    mov r0, c23  // ::g__speedTreeAlphaRefs<0,1,2,3>
    dp4 o1.w, r0, c11[a0.x]  // ::main<7>

#line 352
    mov o1.xyz, v3.xyxw  // ::main<4,5,6>

// approximately 82 instruction slots used
