//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Norm_Vd.vso
//
//
// Parameters:
//
//   float4 g__mtlColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   g__mtlColor  c197     1
//

    vs_3_0
    def c0, 1, 0, 0, 0
    dcl_position v0  // IN<0,1>
    dcl_color v1  // IN<3,4,5,6>
    dcl_position o0
    dcl_color o1
    dcl_texcoord3 o2

#line 155 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Norm_Vd.final"
    mul o1, c197, v1  // ::main<4,5,6,7>

#line 360
    mad o0, v0.xyxx, c0.xxyy, c0.yyyx  // ::main<0,1,2,3>

#line 348
    mov o2, c0.yyyx  // ::main<8,9,10,11>

// approximately 3 instruction slots used
