//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_strauss_skinned_Morphable_ADNS_Dn_VtxAtm_WPos_VNorm.vso
//
//
// Parameters:
//
//   row_major float3x4 g__matrixPalette[59];
//   row_major float2x4 g__morphing;
//   float4 g__mtlColor;
//   row_major float2x4 g__texXfm0;
//   row_major float2x4 g__texXfm1;
//   row_major float2x4 g__texXfm2;
//   row_major float2x4 g__texXfm3;
//   row_major float2x4 g__texXfm4;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__matrixPalette  c0     177
//   g__worldMatrix    c178     4
//   g__texXfm0        c182     2
//   g__texXfm1        c184     2
//   g__texXfm2        c186     2
//   g__texXfm3        c188     2
//   g__texXfm4        c190     2
//   g__morphing       c194     2
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c177, 2, -1, 1, 0
    def c192, 3, 0, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_blendweight v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,7,8,9>
    dcl_normal v3  // IN<10,11,12>
    dcl_position1 v4  // IN<13,14,15>
    dcl_normal1 v5  // IN<16,17,18>
    dcl_texcoord v6  // IN<19,20>
    dcl_texcoord1 v7  // IN<21,22>
    dcl_texcoord2 v8  // IN<23,24>
    dcl_texcoord3 v9  // IN<25,26>
    dcl_tangent v10  // IN<27,28,29,30>
    dcl_position o0
    dcl_color o1
    dcl_normal o2.xyz
    dcl_texcoord o3
    dcl_texcoord1 o4
    dcl_texcoord2 o5
    dcl_texcoord3 o6
    dcl_texcoord4 o7
    dcl_texcoord5 o8
    dcl_texcoord6 o9

#line 199 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_strauss_skinned_Morphable_ADNS_Dn_VtxAtm_WPos_VNorm.final"
    mov r0.z, c177.z
    add r1, r0.z, -c194

#line 185
    mul r2, r1.xxyy, v6.xyxy
    mad r2, c194.xxyy, v7.xyxy, r2  // ::albedoMapUVStart<0,1>, ::detailMapUVStart<0,1>
    mul r3, r1.xxyy, v8.xyxy
    mad r3, c194.xxyy, v9.xyxy, r3  // ::albedoMapUVEnd<0,1>, ::detailMapUVEnd<0,1>
    lrp r4, c195.w, r3, r2  // ::albedoMapUV<0,1>, ::detailMapUV<0,1>

#line 132
    mad r0.xyw, r4.xyzx, c177.zzzw, c177.wwzz
    mad r2.xyz, r4.zwxw, c177.zzww, c177.wwzw
    dp3 o7.x, c182, r0.xyww  // ::main<27>
    dp3 o7.y, c183, r0.xyww  // ::main<28>
    dp3 o7.z, c184, r2  // ::main<29>
    dp3 o7.w, c185, r2  // ::main<30>

#line 199
    mul r2, r1.zzww, v6.xyxy
    mul r1, r1.zzww, v8.xyxy
    mad r1, c194.zzww, v9.xyxy, r1  // ::normalMapUVEnd<0,1>, ::specMapUVEnd<0,1>
    mad r2, c194.zzww, v7.xyxy, r2  // ::normalMapUVStart<0,1>, ::specMapUVStart<0,1>
    lrp r3, c195.w, r1, r2  // ::normalMapUV<0,1>, ::specMapUV<0,1>

#line 132
    mad r0.xyw, r3.xyzx, c177.zzzw, c177.wwzz
    mad r1.xyz, r3.zwxw, c177.zzww, c177.wwzw
    dp3 o8.x, c186, r0.xyww  // ::main<31>
    dp3 o8.y, c187, r0.xyww  // ::main<32>
    dp3 o8.z, c188, r1  // ::main<33>
    dp3 o8.w, c189, r1  // ::main<34>

#line 206
    add r0.x, r0.z, -c195.x
    mul r0.yz, r0.x, v6.xxyw
    mul r0.xw, r0.x, v8.xyzy
    mad r0.xw, c195.x, v9.xyzy, r0  // ::detailNormalMapUVEnd<0,1>
    mad r0.yz, c195.x, v7.xxyw, r0  // ::detailNormalMapUVStart<0,1>
    lrp r1.xy, c195.w, r0.xwzw, r0.yzzw  // ::detailNormalMapUV<0,1>

#line 132
    mov r1.z, c177.z
    dp3 o9.x, c190, r1  // ::main<35>
    dp3 o9.y, c191, r1  // ::main<36>

#line 225
    add r0.x, c177.z, -v1.x
    add r0.x, r0.x, -v1.y
    add r0.x, r0.x, -v1.z  // ::w<3>

#line 174
    slt r1, v2, -v2
    frc r2, v2
    add r3, -r2, v2
    slt r2, -r2, r2
    mad r1, r1, r2, r3  // ::g__indices<0,1,2,3>

#line 230
    mul r1, r1, c192.x
    mova a0, r1
    mul r1, v1.y, c1[a0.y]
    mad r1, c1[a0.x], v1.x, r1  // ::skinMatrix<4,5,6,7>
    mad r1, c1[a0.z], v1.z, r1  // ::skinMatrix<4,5,6,7>
    mad r1, c1[a0.w], r0.x, r1  // ::skinMatrix<4,5,6,7>

#line 171
    mov r2.xyz, v0  // IN<0,1,2>
    add r0.yzw, -r2.xxyz, v4.xxyz
    mad r2.xyz, c195.w, r0.yzww, v0  // ::g__vertexPos<0,1,2>

#line 371
    mov r2.w, c177.z
    dp4 r0.y, r2, r1  // ::localPos<1>
    mul r3, r0.y, c179

#line 230
    mul r4, v1.y, c0[a0.y]
    mad r4, c0[a0.x], v1.x, r4  // ::skinMatrix<0,1,2,3>
    mad r4, c0[a0.z], v1.z, r4  // ::skinMatrix<0,1,2,3>
    mad r4, c0[a0.w], r0.x, r4  // ::skinMatrix<0,1,2,3>

#line 371
    dp4 r0.y, r2, r4  // ::localPos<0>
    mad r3, r0.y, c178, r3

#line 230
    mul r5, v1.y, c2[a0.y]
    mad r5, c2[a0.x], v1.x, r5  // ::skinMatrix<8,9,10,11>
    mad r5, c2[a0.z], v1.z, r5  // ::skinMatrix<8,9,10,11>
    mad r0, c2[a0.w], r0.x, r5  // ::skinMatrix<8,9,10,11>

#line 371
    dp4 r0.w, r2, r0  // ::localPos<2>
    mad r2, r0.w, c180, r3
    add r2, r2, c181  // ::g__worldPos<0,1,2,3>
    mul r3, r2.y, c240
    mad r3, r2.x, c239, r3
    mad r3, r2.z, c241, r3
    mad o0, r2.w, c242, r3  // ::main<0,1,2,3>
    mov o3, r2  // ::main<11,12,13,14>

#line 175
    mov o1, c197  // ::main<4,5,6,7>

#line 172
    mad r2.xyz, v3, c177.x, c177.y
    mad r3.xyz, v5, c177.x, c177.y
    lrp r5.xyz, c195.w, r3, r2  // ::g__vertexNormal<0,1,2>

#line 372
    dp3 r0.w, r5, r1  // ::g__worldNormal<1>
    mul r2.xyz, r0.w, c179
    dp3 r0.w, r5, r4  // ::g__worldNormal<0>
    mad r2.xyz, r0.w, c178, r2
    dp3 r0.w, r5, r0  // ::g__worldNormal<2>
    mad r2.xyz, r0.w, c180, r2  // ::g__worldNormal<0,1,2>
    mov o2.xyz, r2  // ::main<8,9,10>

#line 211
    mad r3, v10, c177.x, c177.y  // ::g__vertexTangent<0,1,2,3>
    nrm r6.xyz, r3  // ::g__vertexTangent<0,1,2>

#line 386
    dp3 r0.w, r6, r1  // ::worldTangent<1>
    mul r3.xyz, r0.w, c179
    dp3 r0.w, r6, r4  // ::worldTangent<0>
    mad r3.xyz, r0.w, c178, r3
    dp3 r0.w, r6, r0  // ::worldTangent<2>
    mad r3.xyz, r0.w, c180, r3  // ::worldTangent<0,1,2>
    mul o4.xw, r3.x, c177.zyzw  // ::main<15,18>

#line 213
    mul r7.xyz, r5.zxyw, r6.yzxw
    mad r5.xyz, r5.yzxw, r6.zxyw, -r7
    mul r5.xyz, r3.w, r5  // ::g__vertexBinormal<0,1,2>

#line 387
    dp3 r0.w, r5, r4  // ::worldBinormal<0>
    dp3 r1.x, r5, r1  // ::worldBinormal<1>
    dp3 r0.x, r5, r0  // ::worldBinormal<2>
    mul r1.xyz, r1.x, c179
    mad r0.yzw, r0.w, c178.xxyz, r1.xxyz
    mad r0.xyz, r0.x, c180, r0.yzww  // ::worldBinormal<0,1,2>
    mov o4.y, r0.x  // ::main<16>
    mov o4.z, r2.x  // ::main<17>
    mul o5.xw, r3.yyzx, c177.zyzw  // ::main<19,22>
    mul o6.xw, r3.zyzx, c177.zyzw  // ::main<23,26>
    mov o5.y, r0.y  // ::main<20>
    mov o6.y, r0.z  // ::main<24>
    mov o5.z, r2.y  // ::main<21>
    mov o6.z, r2.z  // ::main<25>

#line 132
    mov o9.zw, c177.w  // ::main<37,38>

// approximately 111 instruction slots used
