//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Z_skinned_TexTransform.vso
//
//
// Parameters:
//
//   row_major float3x4 g__matrixPalette[59];
//   row_major float4x4 g__zWorldMatrix;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   g__matrixPalette c0     177
//   g__zWorldMatrix  c198     4
//

    vs_3_0
    def c177, 1, 3, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_blendweight v1  // IN<3,4,5>
    dcl_blendindices v2  // IN<6,7,8,9>
    dcl_position o0

#line 190 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Z_skinned_TexTransform.final"
    add r0.x, c177.x, -v1.x
    add r0.x, r0.x, -v1.y
    add r0.x, r0.x, -v1.z  // ::w<3>

#line 157
    slt r1, v2, -v2
    frc r2, v2
    add r3, -r2, v2
    slt r2, -r2, r2
    mad r1, r1, r2, r3  // ::g__indices<0,1,2,3>

#line 195
    mul r1, r1, c177.y
    mova a0, r1
    mul r1, v1.y, c1[a0.y]
    mad r1, c1[a0.x], v1.x, r1  // ::skinMatrix<4,5,6,7>
    mad r1, c1[a0.z], v1.z, r1  // ::skinMatrix<4,5,6,7>
    mad r1, c1[a0.w], r0.x, r1  // ::skinMatrix<4,5,6,7>

#line 336
    mad r2, v0.xyzx, c177.xxxz, c177.zzzx
    dp4 r0.y, r2, r1  // ::localPos<1>

#line 340
    mul r1, r0.y, c199

#line 195
    mul r3, v1.y, c0[a0.y]
    mad r3, c0[a0.x], v1.x, r3  // ::skinMatrix<0,1,2,3>
    mad r3, c0[a0.z], v1.z, r3  // ::skinMatrix<0,1,2,3>
    mad r3, c0[a0.w], r0.x, r3  // ::skinMatrix<0,1,2,3>

#line 336
    dp4 r0.y, r2, r3  // ::localPos<0>

#line 340
    mad r1, r0.y, c198, r1

#line 195
    mul r3, v1.y, c2[a0.y]
    mad r3, c2[a0.x], v1.x, r3  // ::skinMatrix<8,9,10,11>
    mad r3, c2[a0.z], v1.z, r3  // ::skinMatrix<8,9,10,11>
    mad r0, c2[a0.w], r0.x, r3  // ::skinMatrix<8,9,10,11>

#line 336
    dp4 r0.x, r2, r0  // ::localPos<2>

#line 340
    mad r0, r0.x, c200, r1
    add o0, r0, c201  // ::main<0,1,2,3>

// approximately 30 instruction slots used
