//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\Mg_VP_Z_Terrain.vso
//
//
// Parameters:
//
//   float4 g__mtlColor;
//   row_major float4x4 g__viewProjMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    dcl_position v0  // IN<0,1,2>
    dcl_position o0
    dcl_color o1

#line 344 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_VP_Z_Terrain.final"
    mul r0, c240, v0.y
    mad r0, v0.x, c239, r0
    mad r0, v0.z, c241, r0
    add o0, r0, c242  // ::main<0,1,2,3>

#line 152
    mov o1, c197  // ::main<4,5,6,7>

// approximately 5 instruction slots used
