//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\MgVP_Scaleform_GlyphVShaderSzcText.vso
//
//
// Parameters:
//
//   float4 mvp[4];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   mvp          c0       2
//

    vs_3_0
    dcl_position v0  // pos<0,1,2,3>
    dcl_texcoord v1  // tc0<0,1>
    dcl_color v2  // color<0,1,2,3>
    dcl_position o0
    dcl_texcoord o1.xy
    dcl_color o2

#line 5 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgVP_Scaleform_GlyphVShaderSzcText.final"
    dp4 o0.x, v0, c0  // opos<0>
    dp4 o0.y, v0, c1  // opos<1>
    mov o0.zw, v0  // opos<2,3>
    mov o1.xy, v1  // otc0<0,1>
    mov o2, v2  // ocolor<0,1,2,3>

// approximately 5 instruction slots used
