//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\MgVP3D_T2.vso
//
//
// Parameters:
//
//   float4 g__mtlColor;
//   row_major float4x4 g__viewProjMatrix;
//   row_major float4x4 g__worldMatrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__worldMatrix    c178     4
//   g__mtlColor       c197     1
//   g__viewProjMatrix c239     4
//

    vs_3_0
    def c0, 0, 1, 0, 0
    dcl_position v0  // IN<0,1,2>
    dcl_texcoord v1  // IN<3,4>
    dcl_texcoord1 v2  // IN<5,6>
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2
    dcl_texcoord3 o3

#line 344 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgVP3D_T2.final"
    mul r0, c179, v0.y
    mad r0, v0.x, c178, r0
    mad r0, v0.z, c180, r0
    add r0, r0, c181  // ::g__worldPos<0,1,2,3>

#line 347
    mul r1, r0.y, c240
    mad r1, r0.x, c239, r1
    mad r1, r0.z, c241, r1
    mad o0, r0.w, c242, r1  // ::main<0,1,2,3>

#line 156
    mov o1, c197  // ::main<4,5,6,7>

#line 363
    mov o2.xy, v1  // ::main<8,9>
    mov o2.zw, v2.xyxy  // ::main<10,11>

#line 351
    mov o3, c0.xxxy  // ::main<12,13,14,15>

// approximately 12 instruction slots used
