//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\vertex_shaders\MgVP_Scaleform_StripVShaderXY16iCF32_T2Text.vso
//
//
// Parameters:
//
//   float4 mvp[4];
//   float4 texgen[4];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   mvp          c0       2
//   texgen       c4       4
//

    vs_3_0
    dcl_position v0  // pos<0,1,2,3>
    dcl_color v1  // color<0,1,2,3>
    dcl_color1 v2  // factor<0,1,2,3>
    dcl_position o0
    dcl_color o1
    dcl_color1 o2
    dcl_texcoord o3.xy
    dcl_texcoord1 o4.xy

#line 6 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgVP_Scaleform_StripVShaderXY16iCF32_T2Text.final"
    dp4 o0.x, v0, c0  // opos<0>
    dp4 o0.y, v0, c1  // opos<1>
    dp4 o3.x, v0, c4  // otc0<0>
    dp4 o3.y, v0, c5  // otc0<1>
    dp4 o4.x, v0, c6  // otc1<0>
    dp4 o4.y, v0, c7  // otc1<1>

#line 6
    mov o0.zw, v0  // opos<2,3>

#line 12
    mov o1, v1  // ocolor<0,1,2,3>
    mov o2, v2  // ofactor<0,1,2,3>

// approximately 9 instruction slots used
