//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_A_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_1DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__straussParms;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     3
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 4, 0.00999999978, 0, 0
    def c4, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3.xy  // IN<16,17>
    dcl_texcoord4 v4.xyz  // IN<20,21,22>
    dcl vFace  // IN<24>
    dcl_2d s0
    dcl_2d s5
    dcl_cube s6

#line 948 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_A_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_1DL.final"
    texld_pp r0, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r1, c5, v0

#line 516
    mad_pp r2.x, r0.w, -r1.w, c4.x

#line 949
    mul_pp r0, r0, r1  // ::diffuseSampl<0,1,2,3>

#line 516
    mad_pp oC0.w, c8.w, r2.x, r0.w  // ::main<3>

#line 296
    add r1.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r1  // ::lightSpacePos<3>
    add r1.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r2, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r2, r1.x, r2, c24  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.y, c26, r2  // ::scaleOffset<0,1,2,3>
    cmp r1, r1.z, c27, r2  // ::scaleOffset<0,1,2,3>

#line 299
    mul r2.xyz, c21, v2.y
    mad r2.xyz, v2.x, c20, r2
    mad r2.xyz, v2.z, c22, r2
    mad r2.xyz, v2.w, c23, r2  // ::lightSpacePos<0,1,2>

#line 304
    mad r1.xy, r2, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r1.zw, r2.z, c4.xyxz, c4.xyzx
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r1.x, c4.x  // ::shadowValue<0>
    max_sat_pp r1.x, r0.w, c30.x  // ::calcShadow<0>

#line 978
    mul_pp r1.xyz, r1.x, c2

#line 347
    cmp r0.w, vFace, c4.x, c4.y  // IN<24>
    cmp r0.w, -r0.w, c4.z, c4.x
    cmp r1.w, vFace, c4.w, c4.y
    add_pp r0.w, r0.w, r1.w  // ::g__face<0>

#line 344
    nrm_pp r2.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 963
    mul_pp r2.xyz, -r0.w, r2  // ::worldNormal<0,1,2>

#line 762
    dp3_pp r0.w, r2, c3  // ::ndotl<0>

#line 782
    add r3.xyz, r2, r2
    mad_pp r4.xyz, r3, r0.w, -c3  // ::RVec<0,1,2>

#line 763
    mov_sat_pp r0.w, r0.w  // ::ndotl_satd<0>
    mul_pp r5.xyz, r0, r0.w  // calcStrauss::Qd<0,1,2>

#line 778
    add_pp r6.xyz, c10, -v2
    nrm_pp r7.xyz, r6  // ::viewVec<0,1,2>

#line 783
    dp3_sat_pp r0.w, r7, r4  // ::vdotr<0>

#line 956
    mul_pp r1.w, c66.w, c66.y  // ::specSampl<3>
    max_pp r2.w, r1.w, c0.x  // ::specSampl<3>

#line 785
    pow_pp r1.w, r0.w, r2.w  // ::rs<0>
    mov r4.xy, c4
    mad_pp r4.yzw, v0.xxyz, c6.xxyz, r4.y  // ::Cs<0,1,2>
    mad_pp r4.xyz, r4.yzww, c66.x, r4.x  // ::Cs<0,1,2>
    mul_pp r4.xyz, r4, c6.w  // ::Cs<0,1,2>
    mul_pp r6.xyz, r1.w, r4  // calcStrauss::Qs<0,1,2>

#line 641
    mad_sat_pp r8.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 808
    mul_pp r6.xyz, r6, r8.y  // calcStrauss::Qs<0,1,2>

#line 978
    mad_pp r5.xyz, r5, r8.x, r6

#line 629
    texld_pp r6, r2, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r2, r2
    mul_pp r6.xyz, r6, r0.w  // ::amb<0,1,2>
    mul_pp r6.xyz, r6, c1.w  // ::amb<0,1,2>
    mov_pp r8.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r6.xyz, r6, c72, r8  // ::amb<0,1,2>

#line 769
    mul_pp r6.xyz, r0, r6  // calcStrauss::Qa<0,1,2>

#line 806
    mul_pp r6.xyz, r6, v1.w  // calcStrauss::Qa<0,1,2>

#line 978
    mad_pp r1.xyz, r1, r5, r6  // ::Ir<0,1,2>

#line 515
    mad_pp r5.xyz, r1, c7.w, c7
    lrp_pp r6.xyz, c8.z, r5, r1  // ::outCol<0,1,2>

#line 984
    mul_pp r1.xyz, r0, v4
    mad_pp r1.xyz, r1, r0.w, r6  // ::Ir<0,1,2>

#line 823
    add_pp r5.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r5, r5
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r5.xyz, r5, r0.w  // ::lightVec<0,1,2>

#line 831
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c0.y  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r6.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 762
    dp3_pp r0.w, r2, r5  // ::ndotl<0>

#line 782
    mad_pp r2.xyz, r3, r0.w, -r5  // ::RVec<0,1,2>

#line 763
    mov_sat_pp r0.w, r0.w  // ::ndotl_satd<0>

#line 783
    dp3_sat_pp r1.w, r7, r2  // ::vdotr<0>
    pow_pp r3.x, r1.w, r2.w  // ::rs<0>

#line 791
    mul_pp r2.xyz, r4, r3.x  // calcStrauss::Qs<0,1,2>

#line 866
    mad_pp r0.xyz, r0, r0.w, r2  // ::Qd<0,1,2>

#line 987
    mad_pp oC0.xyz, r0, r6, r1  // ::main<0,1,2>

// approximately 89 instruction slots used (3 texture, 86 arithmetic)
