//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_T1_Em_WPos_VNorm_Shdw_VtxAtm_4DL.pso
//
//
// Parameters:
//
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__waterFresnelParams;
//   sampler2D g__waterNormalMap1;
//   float4 g__waterNormalScale;
//   float4 g__waterParams[2];
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__waterFresnelParams    c57      1
//   g__waterParams           c59      1
//   g__waterNormalScale      c62      1
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100    12
//   g__waterNormalMap1       s1       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 2, -1, 1, 64
    def c4, 0.5, 1, 0, 0.00999999978
    def c6, 0.200000003, 0, 0, 0
    dcl_texcoord v0.xyz  // IN<4,5,6>
    dcl_texcoord1 v1.xyz  // IN<8,9,10>
    dcl_texcoord2 v2.xyz  // IN<12,13,14>
    dcl_texcoord3 v3.zw  // IN<18,19>
    dcl_texcoord6 v4  // IN<20,21,22,23>
    dcl_2d s1
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 884 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_T1_Em_WPos_VNorm_Shdw_VtxAtm_4DL.final"
    add_pp r0.xyz, c110, -v4  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 892
    add_pp r0.w, r1.x, -c111.x
    max_pp r1.x, r0.w, c4.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c111.w
    mad_pp r0.w, r1.x, c111.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c109  // getDynamicPointLight::color<0,1,2>

#line 884
    add_pp r2.xyz, c107, -v4  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 892
    add_pp r0.w, r1.w, -c108.x
    max_pp r1.w, r0.w, c4.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r1.w, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 884
    add_pp r4.xyz, c101, -v4  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 892
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c4.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 884
    add_pp r6.xyz, c104, -v4  // ::lightVec<0,1,2>
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 892
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c4.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r7.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 657
    texld_pp r8, v3.zwzw, s1  // ::sampl<0,1>
    mad_pp r8.xy, r8, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r0.w, r8, -r8, c0.z

#line 1346
    mul_pp r8.xy, r8, c62.x  // ::normSmpl<0,1>

#line 659
    rsq_pp r0.w, r0.w
    rcp_pp r8.z, r0.w  // ::sampl<2>

#line 1352
    nrm_pp r9.xyz, r8  // ::combSampl<0,1,2>

#line 341
    nrm_pp r8.xyz, v0  // ::g__bx<0,1,2>

#line 1354
    dp3_pp r10.x, r8, r9  // ::worldNormal<0>

#line 631
    mov_pp r8.x, r8.z

#line 342
    nrm_pp r11.xyz, v1  // ::g__by<0,1,2>

#line 1354
    dp3_pp r10.y, r11, r9  // ::worldNormal<1>

#line 631
    mov_pp r8.y, r11.z

#line 343
    nrm_pp r11.xyz, v2  // ::g__bz<0,1,2>

#line 1354
    dp3_pp r10.z, r11, r9  // ::worldNormal<2>

#line 631
    mov_pp r8.z, r11.z
    dp3_sat_pp r0.w, r10, r8

#line 771
    dp3_sat_pp r1.w, r10, r6
    mul_pp r6.xyz, r1.w, c5  // calcLambert::Qd<0,1,2>

#line 915
    mul_pp r6.xyz, r7, r6  // ::Qd<0,1,2>

#line 771
    dp3_sat_pp r1.w, r10, r4
    mul_pp r4.xyz, r1.w, c5  // calcLambert::Qd<0,1,2>

#line 916
    mad_pp r4.xyz, r4, r5, r6  // ::Ir<0,1,2>

#line 771
    dp3_sat_pp r1.w, r10, r2
    mul_pp r2.xyz, r1.w, c5  // calcLambert::Qd<0,1,2>

#line 920
    mad_pp r2.xyz, r2, r3, r4  // ::Ir<0,1,2>

#line 771
    dp3_sat_pp r0.x, r10, r0
    mul_pp r0.xyz, r0.x, c5  // calcLambert::Qd<0,1,2>

#line 924
    mad_pp r0.xyz, r0, r1, r2  // ::Ir<0,1,2>

#line 300
    add r1.xyz, -c10, v4  // ::delta<0,1,2>
    dp3 r1.x, c11, r1  // ::lightSpacePos<3>
    add r1.yzw, r1.x, -c28  // ::delta<0,1,2>

#line 315
    add r1.x, -r1.x, c30.z

#line 305
    mov r2, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r2, r1.y, r2, c24  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.z, c26, r2  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.w, c27, r2  // ::scaleOffset<0,1,2,3>

#line 303
    mul r1.yzw, c21.xxyz, v4.y
    mad r1.yzw, v4.x, c20.xxyz, r1
    mad r1.yzw, v4.z, c22.xxyz, r1
    mad r1.yzw, v4.w, c23.xxyz, r1  // ::lightSpacePos<0,1,2>

#line 308
    mad r2.xy, r1.yzzw, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r2.zw, r1.w, c4.xyyz, c4.xyzy
    texldp r2, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r1.x, r1.x, r2.x, c0.z  // ::shadowValue<0>
    max_sat_pp r2.x, r1.x, c30.x  // ::calcShadow<0>

#line 1366
    mul_pp r1.xyz, r2.x, c2

#line 781
    add_pp r2.xyz, c10, -v4
    dp3_pp r1.w, r2, r2
    rsq_pp r1.w, r1.w

#line 785
    mad_pp r3.xyz, r2, r1.w, c3

#line 781
    mul_pp r2.xyz, r2, r1.w  // ::viewVec<0,1,2>

#line 785
    nrm_pp r4.xyz, r3  // ::HVec<0,1,2>
    dp3_sat_pp r1.w, r10, r4  // ::ndoth<0>
    pow_pp r2.w, r1.w, c0.w  // ::rs<0>

#line 771
    dp3_pp r1.w, r10, c3  // ::ndotl<0>
    mov_sat_pp r3.x, r1.w

#line 808
    mad_pp r1.w, r1.w, c4.x, c4.x

#line 1366
    mad_pp r3.xyz, r3.x, c5, r2.w

#line 630
    texld_pp r4, r10, s6  // ::amb<0,1,2>
    mul_pp r4.xyz, r0.w, r4  // ::amb<0,1,2>
    mul_pp r4.xyz, r4, c1.w  // ::amb<0,1,2>
    mov_pp r5.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r4.xyz, r4, c72, r5  // ::amb<0,1,2>

#line 797
    mul_pp r4.xyz, r4, c5  // calcLambert::Qa<0,1,2>

#line 1366
    mad_pp r1.xyz, r1, r3, r4  // ::Ir<0,1,2>

#line 1371
    add_pp r0.xyz, r0, r1  // ::Ir<0,1,2>

#line 805
    dp3_pp r0.w, -r2, r10
    add_pp r0.w, r0.w, r0.w
    mad_pp r1.xyz, r0.w, -r10, -r2  // ::reflectionVec<0,1,2>

#line 1381
    dp3_sat_pp r0.w, r2, r10
    pow_pp r2.x, r0.w, c57.y
    mad_sat_pp r0.w, c57.x, r2.x, c57.z  // ::fresnelTerm<0>

#line 1392
    add r0.w, -r0.w, c0.z
    max r2.x, c6.x, r0.w
    min_pp oC0.w, r2.x, c0.z  // ::main<3>

#line 644
    texld_pp r2, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r0.w, r2.w, c68.x, c68.y
    exp_pp r0.w, r0.w  // ::f<0>
    mul_pp r1.xyz, r2, r0.w
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 808
    mul_pp r1.xyz, r1.w, r1  // calcLambert::Qe<0,1,2>

#line 1387
    mul_pp r1.xyz, r1, c59.w
    mad_pp oC0.xyz, r0, c59.z, r1  // ::main<0,1,2>

// approximately 147 instruction slots used (4 texture, 143 arithmetic)
