//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_A_T1_T2_T3_Em_WPos_VNorm_Shdw_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__waterFresnelParams;
//   sampler2D g__waterNormalMap1;
//   sampler2D g__waterNormalMap2;
//   sampler2D g__waterNormalMap3;
//   float4 g__waterNormalScale;
//   float4 g__waterParams[2];
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__sunDir              c3       1
//   g__diffColor           c5       1
//   g__cameraPos           c10      1
//   g__cameraFront         c11      1
//   g__shadowMatrices      c20      4
//   g__shadowScaleOffset   c24      4
//   g__shadowDistances     c28      1
//   g__shadowMisc          c30      1
//   g__waterFresnelParams  c57      1
//   g__waterParams         c59      1
//   g__waterNormalScale    c62      1
//   g__hdrTexParms         c68      1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__waterNormalMap1     s1       1
//   g__waterNormalMap2     s2       1
//   g__waterNormalMap3     s3       1
//   g__shadowMap           s5       1
//   g__ambientMap          s6       1
//   g__envMap              s8       1
//

    ps_3_0
    def c0, 2, -1, 1, 64
    def c4, 0.5, 1, 0, 0.200000003
    dcl_texcoord v0.xyz  // IN<4,5,6>
    dcl_texcoord1 v1.xyz  // IN<8,9,10>
    dcl_texcoord2 v2.xyz  // IN<12,13,14>
    dcl_texcoord3 v3  // IN<16,17,18,19>
    dcl_texcoord4 v4  // IN<20,21,22,23>
    dcl_texcoord6 v5  // IN<24,25,26,27>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 300 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_A_T1_T2_T3_Em_WPos_VNorm_Shdw_VtxAtm.final"
    add r0.xyz, -c10, v5  // ::delta<0,1,2>
    dp3 r0.x, c11, r0  // ::lightSpacePos<3>
    add r0.yzw, r0.x, -c28  // ::delta<0,1,2>

#line 315
    add r0.x, -r0.x, c30.z

#line 305
    mov r1, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r1, r0.y, r1, c24  // ::scaleOffset<0,1,2,3>
    cmp r1, r0.z, c26, r1  // ::scaleOffset<0,1,2,3>
    cmp r1, r0.w, c27, r1  // ::scaleOffset<0,1,2,3>

#line 303
    mul r0.yzw, c21.xxyz, v5.y
    mad r0.yzw, v5.x, c20.xxyz, r0
    mad r0.yzw, v5.z, c22.xxyz, r0
    mad r0.yzw, v5.w, c23.xxyz, r0  // ::lightSpacePos<0,1,2>

#line 308
    mad r1.xy, r0.yzzw, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r1.zw, r0.w, c4.xyyz, c4.xyzy
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r0.x, r0.x, r1.x, c0.z  // ::shadowValue<0>
    max_sat_pp r1.x, r0.x, c30.x  // ::calcShadow<0>

#line 1342
    mul_pp r0.xyz, r1.x, c2

#line 664
    texld_pp r1, v3.zwzw, s1  // ::sampl<0,1>
    mad_pp r1.xy, r1, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r0.w, r1, -r1, c0.z

#line 1322
    mul_pp r1.xy, r1, c62.x  // ::normSmpl<0,1>

#line 666
    rsq_pp r0.w, r0.w
    rcp_pp r1.z, r0.w  // ::sampl<2>
    texld_pp r2, v4, s2  // ::sampl<0,1>
    mad_pp r2.xy, r2, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r0.w, r2, -r2, c0.z

#line 1323
    mul_pp r2.xy, r2, c62.y  // ::normSmpl<3,4>

#line 666
    rsq_pp r0.w, r0.w
    rcp_pp r2.z, r0.w  // ::sampl<2>

#line 1328
    add_pp r1.xyz, r1, r2

#line 664
    texld_pp r2, v4.zwzw, s3  // ::sampl<0,1>
    mad_pp r2.xy, r2, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r0.w, r2, -r2, c0.z

#line 1324
    mul_pp r2.xy, r2, c62.z  // ::normSmpl<6,7>

#line 666
    rsq_pp r0.w, r0.w
    rcp_pp r2.z, r0.w  // ::sampl<2>

#line 1328
    add_pp r1.xyz, r1, r2
    nrm_pp r2.xyz, r1  // ::combSampl<0,1,2>

#line 345
    nrm_pp r1.xyz, v0  // ::g__bx<0,1,2>

#line 1330
    dp3_pp r3.x, r1, r2  // ::worldNormal<0>

#line 638
    mov_pp r1.x, r1.z

#line 346
    nrm_pp r4.xyz, v1  // ::g__by<0,1,2>

#line 1330
    dp3_pp r3.y, r4, r2  // ::worldNormal<1>

#line 638
    mov_pp r1.y, r4.z

#line 347
    nrm_pp r4.xyz, v2  // ::g__bz<0,1,2>

#line 1330
    dp3_pp r3.z, r4, r2  // ::worldNormal<2>

#line 638
    mov_pp r1.z, r4.z
    dp3_sat_pp r0.w, r3, r1
    texld_pp r1, r3, s6  // ::amb<0,1,2>
    mul_pp r1.xyz, r0.w, r1  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c1.w  // ::amb<0,1,2>
    mov_pp r2.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.xyz, r1, c72, r2  // ::amb<0,1,2>

#line 1311
    texld_pp r2, v3, s0  // ::diffuseSampl<0,1,2>
    mul_pp r2.xyz, r2, c5  // ::diffuseSampl<0,1,2>

#line 804
    mul_pp r1.xyz, r1, r2  // calcLambert::Qa<0,1,2>

#line 788
    add_pp r4.xyz, c10, -v5
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w

#line 792
    mad_pp r5.xyz, r4, r0.w, c3

#line 788
    mul_pp r4.xyz, r4, r0.w  // ::viewVec<0,1,2>

#line 792
    nrm_pp r6.xyz, r5  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r3, r6  // ::ndoth<0>
    pow_pp r1.w, r0.w, c0.w  // ::rs<0>

#line 778
    dp3_pp r0.w, r3, c3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w

#line 815
    mad_pp r0.w, r0.w, c4.x, c4.x

#line 1342
    mad_pp r2.xyz, r2.w, r2, r1.w
    mad_pp r0.xyz, r0, r2, r1  // ::Ir<0,1,2>

#line 812
    dp3_pp r1.x, -r4, r3
    add_pp r1.x, r1.x, r1.x
    mad_pp r1.xyz, r1.x, -r3, -r4  // ::reflectionVec<0,1,2>

#line 1353
    dp3_sat_pp r1.w, r4, r3
    pow_pp r2.x, r1.w, c57.y
    mad_sat_pp r1.w, c57.x, r2.x, c57.z  // ::fresnelTerm<0>

#line 1364
    add r1.w, -r1.w, c0.z
    max r2.x, c4.w, r1.w
    min_pp oC0.w, r2.x, c0.z  // ::main<3>

#line 651
    texld_pp r1, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r1.w, r1.w, c68.x, c68.y
    exp_pp r1.w, r1.w  // ::f<0>
    mul_pp r1.xyz, r1, r1.w
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 815
    mul_pp r1.xyz, r0.w, r1  // calcLambert::Qe<0,1,2>

#line 1359
    mul_pp r1.xyz, r1, c59.w
    mad_pp oC0.xyz, r0, c59.z, r1  // ::main<0,1,2>

// approximately 104 instruction slots used (7 texture, 97 arithmetic)
