//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Fx_A_Vd_Ao_WPos_Shdw_VNorm_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   bool g__receiveShadows;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__receiveShadows        b4       1
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__diffColor             c5       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__ambientCubeMapColor   c72      1
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3.xy  // IN<16,17>
    dcl vFace  // IN<24>
    dcl_2d s0
    dcl_2d s5
    dcl_cube s6

#line 347 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Fx_A_Vd_Ao_WPos_Shdw_VNorm_VtxAtm.final"
    cmp r0.x, vFace, c0.x, c0.y  // IN<24>

#line 344
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 347
    cmp r0.x, -r0.x, c0.z, c0.x
    cmp r0.y, vFace, c0.w, c0.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 1018
    texld_pp r2, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r3, r2, v0  // ::diffuseSampl<0,1,2,3>
    mul_pp r0.xyz, r1, -r0.x  // ::g__vertexNormal<0,1,2>

#line 629
    texld_pp r1, r0, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r0, r0
    mul_pp r1.xyz, r1, r0.w  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c1.w  // ::amb<0,1,2>
    mov_pp r2.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.xyz, r1, c72, r2  // ::amb<0,1,2>

#line 1034
    add_pp r1.xyz, r1, c0.y
    mov r2.x, c0.x
    mad_pp r1.xyz, c5.x, r1, r2.x
    mul_pp r1.xyz, r3, r1  // ::Qa<0,1,2>
    add_pp r2.xyz, c10, -v2
    nrm_pp r4.xyz, r2  // ::viewVec<0,1,2>

#line 640
    mad_sat_pp r0.w, v1.w, c200.x, c200.y  // ::ao<1>

#line 1043
    mul_pp r1.xyz, r1, v1.w  // ::Qa<0,1,2>
    mul_pp r2.xyz, r3, r0.w  // ::Qd<0,1,2>
    dp3_pp r0.x, r4, r0  // ::dot_viewNrm<0>
    abs_sat_pp r0.x, r0.x
    pow_pp r1.w, r0.x, c5.y  // ::edge<0>

#line 1061
    if b4

#line 296
      add r0.xyz, -c10, v2  // ::delta<0,1,2>
      dp3 r0.x, c11, r0  // ::lightSpacePos<3>
      add r0.yzw, r0.x, -c28  // ::delta<0,1,2>
      mul r3.xyz, c21, v2.y
      mad r3.xyz, v2.x, c20, r3
      mad r3.xyz, v2.z, c22, r3
      mad r3.xyz, v2.w, c23, r3  // ::lightSpacePos<0,1,2>
      mov r4, c25  // ::g__shadowScaleOffset<4,5,6,7>
      cmp r4, r0.y, r4, c24  // ::scaleOffset<0,1,2,3>
      cmp r4, r0.z, c26, r4  // ::scaleOffset<0,1,2,3>
      cmp r4, r0.w, c27, r4  // ::scaleOffset<0,1,2,3>
      mad r4.xy, r3, r4, r4.zwzw  // ::lightSpacePos<0,1>

#line 267
      mad r4.zw, r3.z, c0.xyxz, c0.xyzx
      texldp r4, r4, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
      add r0.x, -r0.x, c30.z
      cmp r0.x, r0.x, r4.x, c0.x  // ::shadowValue<0>
      max_sat_pp r3.x, r0.x, c30.x  // ::calcShadow<0>

#line 1061
    else
      mov r3.x, c0.x  // ::shadow<0>
    endif

#line 1065
    mul_pp r0.xyz, r3.x, c2
    mad_pp r0.xyz, r0, r2, r1  // ::Ir<0,1,2>
    mul_pp r0.w, r3.w, r1.w
    mad_pp r1.x, r2.w, v0.w, -r0.w
    mad_pp r0.w, c5.w, r1.x, r0.w  // ::Ir<3>

#line 515
    mad_pp r1.xyz, r0, c7.w, c7
    add_pp r1.xyz, -r0, r1
    mad_pp oC0.xyz, c8.z, r1, r0  // ::main<0,1,2>
    add_pp r0.x, -r0.w, c0.x
    mad_pp oC0.w, c8.w, r0.x, r0.w  // ::main<3>

// approximately 65 instruction slots used (3 texture, 62 arithmetic)
