//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_AD_Dn_Vd_WPos_Shdw_VNorm_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   bool g__detailBools[2];
//   sampler2D g__detailMap;
//   sampler2D g__detailNormalMap;
//   float4 g__detailSelect;
//   float4 g__detailVariation;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__straussParms;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__detailBools         b0       1
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__sunDir              c3       1
//   g__diffColor           c5       1
//   g__specColor           c6       1
//   g__emissiveColor       c7       1
//   g__emissiveParms       c8       1
//   g__cameraPos           c10      1
//   g__cameraFront         c11      1
//   g__shadowMatrices      c20      4
//   g__shadowScaleOffset   c24      4
//   g__shadowDistances     c28      1
//   g__shadowMisc          c30      1
//   g__straussParms        c66      1
//   g__detailSelect        c69      1
//   g__ambientCubeMapColor c72      1
//   g__detailVariation     c87      1
//   g__albedoMap           s0       1
//   g__detailMap           s1       1
//   g__detailNormalMap     s4       1
//   g__shadowMap           s5       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 4, 2, -1, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord2 v4  // IN<19,20,21,22>
    dcl_texcoord3 v5  // IN<23,24,25,26>
    dcl_texcoord4 v6  // IN<27,28,29,30>
    dcl_texcoord6 v7.xy  // IN<31,32>
    dcl vFace  // IN<35>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6

#line 357 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_AD_Dn_Vd_WPos_Shdw_VNorm_VtxAtm.final"
    cmp r0.x, vFace, c0.x, c0.y  // IN<35>

#line 351
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>
    nrm_pp r2.xyz, v3  // ::g__bx<0,1,2>
    nrm_pp r3.xyz, v4  // ::g__by<0,1,2>
    nrm_pp r4.xyz, v5  // ::g__bz<0,1,2>

#line 357
    cmp r0.x, -r0.x, c0.z, c0.x
    cmp r0.y, vFace, c0.w, c0.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 906
    texld_pp r5, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r6, c5, v0
    mul_pp r7, r5, r6  // ::diffuseSampl<0,1,2,3>

#line 914
    mul_pp r0.y, c66.w, c66.y  // ::specSampl<3>
    max_pp r1.w, r0.y, c4.x  // ::specSampl<3>

#line 666
    texld_pp r8, v7, s4  // ::sampl<0,1,3>
    mad_pp r8.xy, r8, c4.y, c4.z  // ::sampl<0,1>
    dp2add_pp r0.y, r8, -r8, c0.x
    rsq_pp r0.y, r0.y
    rcp_pp r8.z, r0.y  // ::sampl<2>
    mul_pp r0.yzw, -r0.x, r8.xxyz  // ::sampl<0,1,2>

#line 921
    dp3_pp r2.x, r2, r0.yzww  // ::worldNormal<0>
    dp3_pp r2.y, r3, r0.yzww  // ::worldNormal<1>
    dp3_pp r2.z, r4, r0.yzww  // ::worldNormal<2>

#line 924
    mul_pp r0.yzw, -r0.x, r2.xxyz  // ::worldNormal<0,1,2>
    mul_pp r1.xyz, r1, -r0.x  // ::g__vertexNormal<0,1,2>

#line 585
    texld_pp r2, v6.zwzw, s1  // ::detailSampl<0,1,2,3>
    dp4_pp r0.x, r2, c69
    lrp_pp r3.xyz, c87.x, r0.x, r2  // ::detailSampl<0,1,2>
    if b0
      mad_pp r2.xyz, r5, r6, r3  // ::col<0,1,2>
    else

#line 594
      mul_pp r2.xyz, r7, r3  // ::col<0,1,2>

#line 588
    endif

#line 763
    dp3_pp r0.x, r0.yzww, c3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.x  // ::ndotl_satd<0>

#line 639
    texld_pp r3, r0.yzww, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.x, r0.yzww, r1
    mul_pp r3.xyz, r3, r1.x  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r4  // ::amb<0,1,2>

#line 770
    mul_pp r3.xyz, r2, r3  // calcStrauss::Qa<0,1,2>

#line 779
    add_pp r4.xyz, c10, -v2
    nrm_pp r5.xyz, r4  // ::viewVec<0,1,2>

#line 783
    mul r0.xyz, r0.yzww, r0.x
    mov r1.y, c4.y
    mad_pp r0.xyz, r0, r1.y, -c3  // ::RVec<0,1,2>
    dp3_sat_pp r0.x, r5, r0  // ::vdotr<0>
    pow_pp r3.w, r0.x, r1.w  // ::rs<0>
    mov r0.xy, c0
    mad_pp r0.yzw, v0.xxyz, c6.xxyz, r0.y  // ::Cs<0,1,2>
    mad_pp r0.xyz, r0.yzww, c66.x, r0.x  // ::Cs<0,1,2>
    mul_pp r0.xyz, r0, c6.w  // ::Cs<0,1,2>
    mul_pp r0.xyz, r3.w, r0  // calcStrauss::Qs<0,1,2>

#line 296
    add r1.yzw, -c10.xxyz, v2.xxyz  // ::delta<0,1,2>
    dp3 r0.w, c11, r1.yzww  // ::lightSpacePos<3>
    add r1.yzw, r0.w, -c28  // ::delta<0,1,2>
    mul r4.xyz, c21, v2.y
    mad r4.xyz, v2.x, c20, r4
    mad r4.xyz, v2.z, c22, r4
    mad r4.xyz, v2.w, c23, r4  // ::lightSpacePos<0,1,2>
    mov r9, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r9, r1.y, r9, c24  // ::scaleOffset<0,1,2,3>
    cmp r9, r1.z, c26, r9  // ::scaleOffset<0,1,2,3>
    cmp r9, r1.w, c27, r9  // ::scaleOffset<0,1,2,3>
    mad r9.xy, r4, r9, r9.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r9.zw, r4.z, c0.xyxz, c0.xyzx
    texldp r4, r9, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    add r0.w, -r0.w, c30.z
    cmp r0.w, r0.w, r4.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.y, r0.w, c30.x  // ::calcShadow<0>

#line 943
    mul_pp r1.yzw, r1.y, c2.xxyz
    mad_pp r0.xyz, r2, r2.w, r0
    mad_pp r0.xyz, r1.yzww, r0, r3  // ::Ir<0,1,2>

#line 525
    mad_pp r1.yzw, r0.xxyz, c7.w, c7.xxyz
    mul_pp r0.w, r8.w, c8.z
    lrp_pp r3.xyz, r0.w, r1.yzww, r0  // ::outCol<0,1,2>
    mad_pp r0.x, r5.w, -r6.w, r8.w
    mad_pp oC0.w, c8.w, r0.x, r7.w  // ::main<3>

#line 949
    mov r0.x, v3.w
    mov r0.y, v4.w
    mov r0.z, v5.w
    mul_pp r0.xyz, r2, r0
    mad_pp oC0.xyz, r0, r1.x, r3  // ::main<0,1,2>

// approximately 98 instruction slots used (5 texture, 93 arithmetic)
