//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Terrain_AN_WPos_Shdw_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   sampler2D g__maskMap;
//   sampler2D g__normalMap;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__sunDir              c3       1
//   g__diffColor           c5       1
//   g__cameraPos           c10      1
//   g__cameraFront         c11      1
//   g__shadowMatrices      c20      4
//   g__shadowScaleOffset   c24      4
//   g__shadowDistances     c28      1
//   g__shadowMisc          c30      1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__normalMap           s2       1
//   g__maskMap             s4       1
//   g__shadowMap           s5       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 2, -1, 0, 0
    dcl_texcoord v0  // IN<8,9,10,11>
    dcl_texcoord1 v1  // IN<12,13,14,15>
    dcl_texcoord2 v2  // IN<16,17,18,19>
    dcl_texcoord3 v3  // IN<20,21,22,23>
    dcl_texcoord4 v4.xy  // IN<24,25>
    dcl_texcoord5 v5.xy  // IN<28,29>
    dcl_texcoord6 v6.xy  // IN<32,33>
    dcl vFace  // IN<36>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6

#line 296 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Terrain_AN_WPos_Shdw_VtxAtm.final"
    add r0.xyz, -c10, v0  // ::delta<0,1,2>
    dp3 r0.x, c11, r0  // ::lightSpacePos<3>
    add r0.yzw, r0.x, -c28  // ::delta<0,1,2>

#line 311
    add r0.x, -r0.x, c30.z

#line 301
    mov r1, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r1, r0.y, r1, c24  // ::scaleOffset<0,1,2,3>
    cmp r1, r0.z, c26, r1  // ::scaleOffset<0,1,2,3>
    cmp r1, r0.w, c27, r1  // ::scaleOffset<0,1,2,3>

#line 299
    mul r0.yzw, c21.xxyz, v0.y
    mad r0.yzw, v0.x, c20.xxyz, r0
    mad r0.yzw, v0.z, c22.xxyz, r0
    mad r0.yzw, v0.w, c23.xxyz, r0  // ::lightSpacePos<0,1,2>

#line 304
    mad r1.xy, r0.yzzw, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r1.zw, r0.w, c0.xyxz, c0.xyzx
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.x, r0.x, r1.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.x, r0.x, c30.x  // ::calcShadow<0>

#line 347
    dp4 r0.x, v3, v3
    rsq r0.x, r0.x
    mul_pp r0.xyz, r0.x, v3  // ::g__vertexNormal<0,1,2>

#line 344
    mov r2.x, v1.x
    mov r2.y, v2.x
    mov r2.z, v3.x
    nrm_pp r3.xyz, r2  // ::g__bx<0,1,2>

#line 350
    cmp r0.w, vFace, c0.x, c0.y  // IN<36>
    cmp r0.w, -r0.w, c0.z, c0.x
    cmp r1.y, vFace, c0.w, c0.y
    add_pp r0.w, r0.w, r1.y  // ::g__face<0>

#line 659
    texld_pp r2, v5, s2  // ::sampl<0,1>
    mad_pp r2.xy, r2, c4.x, c4.y  // ::sampl<0,1>
    dp2add_pp r1.y, r2, -r2, c0.x
    rsq_pp r1.y, r1.y
    rcp_pp r2.z, r1.y  // ::sampl<2>
    mul_pp r1.yzw, -r0.w, r2.xxyz  // ::sampl<0,1,2>

#line 1160
    dp3_pp r2.x, r3, r1.yzww  // ::worldNormal<0>

#line 345
    mov r3.x, v1.y
    mov r3.y, v2.y
    mov r3.z, v3.y
    nrm_pp r4.xyz, r3  // ::g__by<0,1,2>

#line 1160
    dp3_pp r2.y, r4, r1.yzww  // ::worldNormal<1>

#line 346
    mov r3.x, v1.z
    mov r3.y, v2.z
    mov r3.z, v3.z
    nrm_pp r4.xyz, r3  // ::g__bz<0,1,2>

#line 1160
    dp3_pp r2.z, r4, r1.yzww  // ::worldNormal<2>

#line 633
    dp3_sat_pp r0.x, r2, r0
    texld_pp r3, r2, s6  // ::amb<0,1,2>

#line 1165
    dp3_sat_pp r0.y, r2, c3

#line 633
    mul_pp r0.xzw, r0.x, r3.xyyz  // ::amb<0,1,2>
    mul_pp r0.xzw, r0, c1.w  // ::amb<0,1,2>
    mov_pp r2.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r0.xzw, r0, c72.xyyz, r2.xyyz  // ::amb<0,1,2>

#line 1152
    texld_pp r2, v4, s0  // ::diffuseSampl<0,1,2>
    mul_pp r1.yzw, r2.xxyz, c5.xxyz  // ::diffuseSampl<0,1,2>

#line 1167
    mul_pp r0.xzw, r0, r1.yyzw  // ::Qa<0,1,2>
    mul_pp r2.xyz, r0.y, r1.yzww  // ::Qd<0,1,2>

#line 1168
    mul_pp r2.xyz, r2, c2
    mad_pp r0.xyz, r2, r1.x, r0.xzww  // ::Ir<0,1,2>
    mov r2.x, v1.w
    mov r2.y, v2.w
    mov r2.z, v3.w
    mad_pp oC0.xyz, r2, r1.yzww, r0  // ::main<0,1,2>

#line 1142
    texld_pp r0, v6, s4  // ::maskSampl<3>

#line 1169
    mov_pp oC0.w, r0.w  // ::main<3>

// approximately 71 instruction slots used (5 texture, 66 arithmetic)
