//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_Refraction_Em_WPos_ProjPos_VNorm_Shdw_VtxAtm_4DL.pso
//
//
// Parameters:
//
//   float4 g__RT;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   sampler2D g__backBufferMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__deepWaterColor;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   row_major float4x4 g__invViewProjMatrix;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__viewPort;
//   float4 g__waterFresnelParams;
//   float4 g__waterParams[2];
//   float4 g__waterRefractionParams;
//   sampler2D g__zMap;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__viewPort              c38      1
//   g__RT                    c41      1
//   g__invViewProjMatrix     c47      4
//   g__waterFresnelParams    c57      1
//   g__waterRefractionParams c58      1
//   g__waterParams           c59      2
//   g__deepWaterColor        c61      1
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100    12
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__zMap                  s7       1
//   g__envMap                s8       1
//   g__backBufferMap         s11      1
//

    ps_3_0
    def c0, 0.00999999978, 0.5, -0.5, 1.44269502
    def c4, 64, 0.5, 1, 0
    dcl_normal v0.xyz  // IN<4,5,6>
    dcl_texcoord6 v1  // IN<7,8,9,10>
    dcl_texcoord9 v2  // IN<11,12,13,14>
    dcl_2d s5
    dcl_cube s6
    dcl_2d s7
    dcl_cube s8
    dcl_2d s11

#line 878 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_Refraction_Em_WPos_ProjPos_VNorm_Shdw_VtxAtm_4DL.final"
    add_pp r0.xyz, c110, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 886
    add_pp r0.w, r1.x, -c111.x
    max_pp r1.x, r0.w, c0.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c111.w
    mad_pp r0.w, r1.x, c111.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c109  // getDynamicPointLight::color<0,1,2>

#line 878
    add_pp r2.xyz, c107, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 886
    add_pp r0.w, r1.w, -c108.x
    max_pp r1.w, r0.w, c0.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r1.w, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 878
    add_pp r4.xyz, c101, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 886
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c0.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 878
    add_pp r6.xyz, c104, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 886
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c0.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r7.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 338
    nrm_pp r8.xyz, v0  // ::g__vertexNormal<0,1,2>

#line 765
    dp3_sat_pp r0.w, r8, r6
    mul_pp r6.xyz, r0.w, c5  // calcLambert::Qd<0,1,2>

#line 909
    mul_pp r6.xyz, r7, r6  // ::Qd<0,1,2>

#line 765
    dp3_sat_pp r0.w, r8, r4
    mul_pp r4.xyz, r0.w, c5  // calcLambert::Qd<0,1,2>

#line 910
    mad_pp r4.xyz, r4, r5, r6  // ::Ir<0,1,2>

#line 765
    dp3_sat_pp r0.w, r8, r2
    mul_pp r2.xyz, r0.w, c5  // calcLambert::Qd<0,1,2>

#line 914
    mad_pp r2.xyz, r2, r3, r4  // ::Ir<0,1,2>

#line 765
    dp3_sat_pp r0.x, r8, r0
    mul_pp r0.xyz, r0.x, c5  // calcLambert::Qd<0,1,2>

#line 918
    mad_pp r0.xyz, r0, r1, r2  // ::Ir<0,1,2>

#line 303
    mul r1.xyz, c21, v1.y
    mad r1.xyz, v1.x, c20, r1
    mad r1.xyz, v1.z, c22, r1
    mad r1.xyz, v1.w, c23, r1  // ::lightSpacePos<0,1,2>

#line 300
    add r2.xyz, -c10, v1  // ::delta<0,1,2>
    dp3 r0.w, c11, r2  // ::lightSpacePos<3>

#line 686
    nrm_pp r3.xyz, r2  // ::eyeVec<0,1,2>

#line 302
    add r2.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 315
    add r0.w, -r0.w, c30.z

#line 305
    mov r4, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r4, r2.x, r4, c24  // ::scaleOffset<0,1,2,3>
    cmp r4, r2.y, c26, r4  // ::scaleOffset<0,1,2,3>
    cmp r2, r2.z, c27, r4  // ::scaleOffset<0,1,2,3>
    mad r2.xy, r1, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r2.zw, r1.z, c4, c4.xywz
    texldp r1, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r0.w, r0.w, r1.x, c4.z  // ::shadowValue<0>
    max_sat_pp r1.x, r0.w, c30.x  // ::calcShadow<0>

#line 1334
    mul_pp r1.xyz, r1.x, c2

#line 775
    add_pp r2.xyz, c10, -v1
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w

#line 779
    mad_pp r4.xyz, r2, r0.w, c3

#line 775
    mul_pp r2.xyz, r2, r0.w  // ::viewVec<0,1,2>

#line 779
    nrm_pp r5.xyz, r4  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r8, r5  // ::ndoth<0>
    pow_pp r1.w, r0.w, c4.x  // ::rs<0>

#line 765
    dp3_pp r0.w, r8, c3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w

#line 802
    mad_pp r0.w, r0.w, c4.y, c4.y

#line 1334
    mad_pp r4.xyz, r2.w, c5, r1.w

#line 624
    texld_pp r5, r8, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.w, r8, r8
    mul_pp r5.xyz, r5, r1.w  // ::amb<0,1,2>
    mul_pp r5.xyz, r5, c1.w  // ::amb<0,1,2>
    mov_pp r6.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r5.xyz, r5, c72, r6  // ::amb<0,1,2>

#line 791
    mul_pp r5.xyz, r5, c5  // calcLambert::Qa<0,1,2>

#line 1334
    mad_pp r1.xyz, r1, r4, r5  // ::Ir<0,1,2>

#line 1339
    add_pp r0.xyz, r0, r1  // ::Ir<0,1,2>

#line 799
    dp3_pp r1.x, -r2, r8
    add_pp r1.x, r1.x, r1.x
    mad_pp r1.xyz, r1.x, -r8, -r2  // ::reflectionVec<0,1,2>

#line 1349
    dp3_sat_pp r1.w, r2, r8
    pow_pp r2.x, r1.w, c57.y
    mad_sat_pp r1.w, c57.x, r2.x, c57.z  // ::fresnelTerm<0>

#line 638
    texld_pp r2, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r1.x, r2.w, c68.x, c68.y
    exp_pp r1.x, r1.x  // ::f<0>
    mul_pp r1.xyz, r2, r1.x
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 802
    mul_pp r1.xyz, r0.w, r1  // calcLambert::Qe<0,1,2>

#line 1355
    mul_pp r1.xyz, r1, c59.w
    mad_pp r0.xyz, r0, c59.z, r1  // ::reflectCol<0,1,2>

#line 689
    mul_pp r1.xyz, c58, c58
    dp3_pp r0.w, r3, r8
    mad_pp r2.x, r0.w, -r0.w, c4.z
    mad_pp r1.xyz, r1, -r2.x, c4.z
    cmp_pp r2.xyz, r1, c4.z, c4.w
    mul_pp r1.xyz, r1, r2
    mul_pp r2.xyz, r2, c58
    rsq_pp r1.y, r1.y
    rcp_pp r1.y, r1.y
    mad_pp r1.y, r2.y, r0.w, r1.y
    mul_pp r4.xyz, r8, r1.y
    mad_pp r4.xyz, r2.y, r3, -r4  // ::refractVecG<0,1,2>

#line 693
    dp3_sat_pp r1.y, r3, r4  // ::refractedAngleOffsetScale<0>

#line 697
    abs_pp r4, c60.xyxy
    add_pp r4, -r4, c4.z

#line 700
    mad_pp r2.yw, r4.xxzy, -c4.y, c4.z
    mul_pp r4, r4, c0.yyyz  // ::indexScaler<0,1,0,1>
    cmp_pp r2.yw, c60.xxzy, r4.xxzy, r2  // ::indexOffset<0,1>

#line 704
    rcp r3.w, v2.w
    mul_pp r4.xy, r3.w, v2  // ::projPos<0,1>
    mad_pp r2.yw, r4.xxzy, r4.xzzw, r2  // ::refractedUvBase<0,1>

#line 708
    mad_pp r4.zw, c60.xyxy, r1.y, r2.xyyw  // ::refractedUvG<0,1>

#line 702
    rcp r5.x, c41.x
    rcp r5.y, c41.y
    mul_pp r5, r5.xyxy, c38.zwxy  // ::viewportRatio<0,1>, ::viewportOffset<0,1>

#line 710
    mad_pp r4.zw, r4, r5.xyxy, r5  // ::refractedUvG<0,1>

#line 714
    texld_pp r6, r4.zwzw, s11  // ::refractObjCol<1>

#line 689
    rsq_pp r1.y, r1.z
    rsq_pp r1.x, r1.x
    rcp_pp r1.x, r1.x
    mad_pp r1.x, r2.x, r0.w, r1.x
    mul_pp r7.xyz, r8, r1.x
    mad_pp r7.xyz, r2.x, r3, -r7  // ::refractVec<0,1,2>

#line 691
    dp3_sat_pp r1.x, r3, r7  // ::refractedAngleOffsetScale<0>

#line 706
    mad_pp r1.xz, c60.xyyw, r1.x, r2.yyww  // ::refractedUv<0,1>
    mad_pp r1.xz, r1, r5.xyyw, r5.zyww  // ::refractedUv<0,1>

#line 689
    rcp_pp r1.y, r1.y
    mad_pp r0.w, r2.z, r0.w, r1.y
    mul_pp r7.xyz, r8, r0.w
    mad_pp r7.xyz, r2.z, r3, -r7  // ::refractVecB<0,1,2>

#line 695
    dp3_sat_pp r0.w, r3, r7  // ::refractedAngleOffsetScale<0>

#line 709
    mad_pp r2.xy, c60, r0.w, r2.ywzw  // ::refractedUvB<0,1>
    mad_pp r2.xy, r2, r5, r5.zwzw  // ::refractedUvB<0,1>

#line 715
    texld_pp r2, r2, s11  // ::refractObjCol<2>

#line 719
    mov_pp r6.z, r2.z

#line 713
    texld r2, r1.xzzw, s7  // ::refractObjDepth<0>
    texld_pp r5, r1.xzzw, s11  // ::refractObjCol<0>

#line 719
    mov_pp r6.x, r5.x
    mad r0.w, v2.z, r3.w, -r2.x
    mov r6.w, r2.x

#line 716
    mad_pp r1.xy, r4, c0.yzzw, c0.y  // ::nonRefractedUv<0,1>
    texld_pp r2, r1, s11  // ::nonRefractObjCol<0,1,2>
    texld r3, r1, s7  // ::nonRefractObjDepth<0>
    mov r2.w, r3.x
    cmp r2, r0.w, r6, r2  // ::refractObjCol<0,1,2>, ::refractObjDepth<0>

#line 725
    mul r3, r4.y, c48
    mad r3, r4.x, c47, r3
    mad r3, r2.w, c49, r3
    add r3, r3, c50  // ::objWorldCoord<0,1,2,3>
    rcp r0.w, r3.w
    mad r1.xyz, r3, r0.w, -v1  // ::underwaterRefractedVec<0,1,2>
    dp3 r0.w, r1, r1
    rsq r0.w, r0.w
    rcp r1.x, r0.w  // ::distance<0>
    mul r0.w, r1.y, r0.w
    mul r0.w, r1.x, r0_abs.w

#line 735
    mul r1.x, r1.x, -c59.x
    mul r1.x, r1.x, c0.w
    exp r1.x, r1.x

#line 730
    max r1.y, r0.w, c4.z  // calcWaterRefractionColor::worldDepth<0>
    mul r0.w, r1.y, c59.y
    max r1.y, r0.w, c4.z  // ::deepWaterPow<0>
    log r3.x, c61.x
    log r3.y, c61.y
    log r3.z, c61.z
    mul r3.xyz, r1.y, r3
    exp_pp r4.x, r3.x  // ::deepWaterCol<0>
    exp_pp r4.y, r3.y  // ::deepWaterCol<1>
    exp_pp r4.z, r3.z  // ::deepWaterCol<2>
    mad r2.xyz, r4, -c61.w, r2
    mul_pp r3.xyz, r4, c61.w  // ::deepWaterCol<0,1,2>
    mad_pp r1.xyz, r1.x, r2, r3  // ::calcWaterRefractionColor<0,1,2>

#line 1360
    add_pp r1.xyz, -r0, r1
    mad_pp oC0.xyz, r1.w, r1, r0  // ::main<0,1,2>
    mov_pp oC0.w, c4.z  // ::main<3>

// approximately 210 instruction slots used (9 texture, 201 arithmetic)
