//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_Refraction_T1_T2_T3_T4_Em_WPos_ProjPos_VNorm_Shdw_VtxAtm.pso
//
//
// Parameters:
//
//   float4 g__RT;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   sampler2D g__backBufferMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__deepWaterColor;
//   float4 g__diffColor;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   row_major float4x4 g__invViewProjMatrix;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__viewPort;
//   float4 g__waterFoamColor;
//   sampler2D g__waterFoamMap;
//   float4 g__waterFoamUvScroll[2];
//   float4 g__waterFresnelParams;
//   sampler2D g__waterNormalMap1;
//   sampler2D g__waterNormalMap2;
//   sampler2D g__waterNormalMap3;
//   float4 g__waterNormalScale;
//   float4 g__waterParams[2];
//   float4 g__waterRefractionParams;
//   sampler2D g__zMap;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__viewPort              c38      1
//   g__RT                    c41      1
//   g__invViewProjMatrix     c47      4
//   g__waterFresnelParams    c57      1
//   g__waterRefractionParams c58      1
//   g__waterParams           c59      2
//   g__deepWaterColor        c61      1
//   g__waterNormalScale      c62      1
//   g__waterFoamColor        c63      1
//   g__waterFoamUvScroll     c64      2
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__waterNormalMap1       s1       1
//   g__waterNormalMap2       s2       1
//   g__waterNormalMap3       s3       1
//   g__waterFoamMap          s4       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__zMap                  s7       1
//   g__envMap                s8       1
//   g__backBufferMap         s11      1
//

    ps_3_0
    def c0, 0.5, 1, 0, -0.5
    def c4, 1.44269502, 0, 0, 0
    def c6, 2, -1, 1, 64
    dcl_texcoord v0.xyz  // IN<4,5,6>
    dcl_texcoord1 v1.xyz  // IN<8,9,10>
    dcl_texcoord2 v2.xyz  // IN<12,13,14>
    dcl_texcoord3 v3.zw  // IN<18,19>
    dcl_texcoord4 v4  // IN<20,21,22,23>
    dcl_texcoord5 v5.xy  // IN<24,25>
    dcl_texcoord6 v6  // IN<26,27,28,29>
    dcl_texcoord9 v7  // IN<30,31,32,33>
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6
    dcl_2d s7
    dcl_cube s8
    dcl_2d s11

#line 303 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_Refraction_T1_T2_T3_T4_Em_WPos_ProjPos_VNorm_Shdw_VtxAtm.final"
    mul r0.xyz, c21, v6.y
    mad r0.xyz, v6.x, c20, r0
    mad r0.xyz, v6.z, c22, r0
    mad r0.xyz, v6.w, c23, r0  // ::lightSpacePos<0,1,2>

#line 300
    add r1.xyz, -c10, v6  // ::delta<0,1,2>
    dp3 r0.w, c11, r1  // ::lightSpacePos<3>

#line 702
    nrm_pp r2.xyz, r1  // ::eyeVec<0,1,2>

#line 302
    add r1.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 315
    add r0.w, -r0.w, c30.z

#line 305
    mov r3, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r3, r1.x, r3, c24  // ::scaleOffset<0,1,2,3>
    cmp r3, r1.y, c26, r3  // ::scaleOffset<0,1,2,3>
    cmp r1, r1.z, c27, r3  // ::scaleOffset<0,1,2,3>
    mad r1.xy, r0, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r1.zw, r0.z, c0.xyyz, c0.xyzy
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r0.x, r0.w, r1.x, c6.z  // ::shadowValue<0>
    max_sat_pp r1.x, r0.x, c30.x  // ::calcShadow<0>

#line 1337
    mul_pp r0.xyz, r1.x, c2

#line 667
    texld_pp r1, v3.zwzw, s1  // ::sampl<0,1>
    mad_pp r1.xy, r1, c6.x, c6.y  // ::sampl<0,1>
    dp2add_pp r0.w, r1, -r1, c6.z

#line 1312
    mul_pp r1.xy, r1, c62.x  // ::normSmpl<0,1>

#line 669
    rsq_pp r0.w, r0.w
    rcp_pp r1.z, r0.w  // ::sampl<2>
    texld_pp r3, v4, s2  // ::sampl<0,1>
    mad_pp r3.xy, r3, c6.x, c6.y  // ::sampl<0,1>
    dp2add_pp r0.w, r3, -r3, c6.z

#line 1313
    mul_pp r3.xy, r3, c62.y  // ::normSmpl<3,4>

#line 669
    rsq_pp r0.w, r0.w
    rcp_pp r3.z, r0.w  // ::sampl<2>

#line 1318
    add_pp r1.xyz, r1, r3

#line 667
    texld_pp r3, v4.zwzw, s3  // ::sampl<0,1,3>
    mad_pp r3.xy, r3, c6.x, c6.y  // ::sampl<0,1>
    dp2add_pp r0.w, r3, -r3, c6.z

#line 1314
    mul_pp r3.xy, r3, c62.z  // ::normSmpl<6,7>

#line 669
    rsq_pp r0.w, r0.w
    rcp_pp r3.z, r0.w  // ::sampl<2>

#line 1318
    add_pp r1.xyz, r1, r3
    nrm_pp r3.xyz, r1  // ::combSampl<0,1,2>

#line 347
    nrm_pp r1.xyz, v0  // ::g__bx<0,1,2>

#line 1320
    dp3_pp r4.x, r1, r3  // ::worldNormal<0>

#line 641
    mov_pp r1.x, r1.z

#line 348
    nrm_pp r5.xyz, v1  // ::g__by<0,1,2>

#line 1320
    dp3_pp r4.y, r5, r3  // ::worldNormal<1>

#line 641
    mov_pp r1.y, r5.z

#line 349
    nrm_pp r5.xyz, v2  // ::g__bz<0,1,2>

#line 1320
    dp3_pp r4.z, r5, r3  // ::worldNormal<2>

#line 641
    mov_pp r1.z, r5.z
    dp3_sat_pp r0.w, r4, r1
    texld_pp r1, r4, s6  // ::amb<0,1,2>
    mul_pp r1.xyz, r0.w, r1  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c1.w  // ::amb<0,1,2>
    mov_pp r3.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.xyz, r1, c72, r3  // ::amb<0,1,2>

#line 807
    mul_pp r1.xyz, r1, c5  // calcLambert::Qa<0,1,2>

#line 791
    add_pp r3.xyz, c10, -v6
    dp3_pp r0.w, r3, r3
    rsq_pp r0.w, r0.w

#line 795
    mad_pp r5.xyz, r3, r0.w, c3

#line 791
    mul_pp r3.xyz, r3, r0.w  // ::viewVec<0,1,2>

#line 795
    nrm_pp r6.xyz, r5  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r4, r6  // ::ndoth<0>
    pow_pp r1.w, r0.w, c6.w  // ::rs<0>

#line 781
    dp3_pp r0.w, r4, c3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w

#line 818
    mad_pp r0.w, r0.w, c0.x, c0.x

#line 1337
    mad_pp r5.xyz, r2.w, c5, r1.w
    mad_pp r0.xyz, r0, r5, r1  // ::Ir<0,1,2>

#line 815
    dp3_pp r1.x, -r3, r4
    add_pp r1.x, r1.x, r1.x
    mad_pp r1.xyz, r1.x, -r4, -r3  // ::reflectionVec<0,1,2>

#line 1348
    dp3_sat_pp r1.w, r3, r4
    pow_pp r2.w, r1.w, c57.y
    mad_sat_pp r1.w, c57.x, r2.w, c57.z  // ::fresnelTerm<0>

#line 654
    texld_pp r3, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r1.x, r3.w, c68.x, c68.y
    exp_pp r1.x, r1.x  // ::f<0>
    mul_pp r1.xyz, r3, r1.x
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 818
    mul_pp r1.xyz, r0.w, r1  // calcLambert::Qe<0,1,2>

#line 1354
    mul_pp r1.xyz, r1, c59.w
    mad_pp r0.xyz, r0, c59.z, r1  // ::reflectCol<0,1,2>

#line 703
    dp3_pp r0.w, r2, r4
    mad_pp r1.x, r0.w, -r0.w, c6.z
    mul_pp r3.xyz, c58, c58
    mad_pp r1.xyz, r3, -r1.x, c6.z
    cmp_pp r3.xyz, r1, c0.y, c0.z
    mul_pp r1.xyz, r1, r3
    mul_pp r3.xyz, r3, c58
    rsq_pp r1.y, r1.y
    rcp_pp r1.y, r1.y
    mad_pp r1.y, r3.y, r0.w, r1.y
    mul_pp r5.xyz, r4, r1.y
    mad_pp r5.xyz, r3.y, r2, -r5  // ::refractVecG<0,1,2>

#line 709
    dp3_sat_pp r1.y, r2, r5  // ::refractedAngleOffsetScale<0>

#line 713
    abs_pp r5, c60.xyxy
    add_pp r5, -r5, c6.z

#line 716
    mad_pp r3.yw, r5.xxzy, -c0.x, c0.y
    mul_pp r5, r5, c0.xxxw  // ::indexScaler<0,1,0,1>
    cmp_pp r3.yw, c60.xxzy, r5.xxzy, r3  // ::indexOffset<0,1>

#line 720
    rcp r2.w, v7.w
    mul_pp r5.xy, r2.w, v7  // ::projPos<0,1>
    mad_pp r3.yw, r5.xxzy, r5.xzzw, r3  // ::refractedUvBase<0,1>

#line 724
    mad_pp r5.zw, c60.xyxy, r1.y, r3.xyyw  // ::refractedUvG<0,1>

#line 718
    rcp r6.x, c41.x
    rcp r6.y, c41.y
    mul_pp r6, r6.xyxy, c38.zwxy  // ::viewportRatio<0,1>, ::viewportOffset<0,1>

#line 726
    mad_pp r5.zw, r5, r6.xyxy, r6  // ::refractedUvG<0,1>

#line 730
    texld_pp r7, r5.zwzw, s11  // ::refractObjCol<1>

#line 705
    rsq_pp r1.y, r1.z
    rsq_pp r1.x, r1.x
    rcp_pp r1.x, r1.x
    mad_pp r1.x, r3.x, r0.w, r1.x
    mul_pp r8.xyz, r4, r1.x
    mad_pp r8.xyz, r3.x, r2, -r8  // ::refractVec<0,1,2>

#line 707
    dp3_sat_pp r1.x, r2, r8  // ::refractedAngleOffsetScale<0>

#line 722
    mad_pp r1.xz, c60.xyyw, r1.x, r3.yyww  // ::refractedUv<0,1>
    mad_pp r1.xz, r1, r6.xyyw, r6.zyww  // ::refractedUv<0,1>

#line 705
    rcp_pp r1.y, r1.y
    mad_pp r0.w, r3.z, r0.w, r1.y
    mul_pp r4.xyz, r4, r0.w
    mad_pp r4.xyz, r3.z, r2, -r4  // ::refractVecB<0,1,2>

#line 711
    dp3_sat_pp r0.w, r2, r4  // ::refractedAngleOffsetScale<0>

#line 725
    mad_pp r2.xy, c60, r0.w, r3.ywzw  // ::refractedUvB<0,1>
    mad_pp r2.xy, r2, r6, r6.zwzw  // ::refractedUvB<0,1>

#line 731
    texld_pp r3, r2, s11  // ::refractObjCol<2>

#line 735
    mov_pp r7.z, r3.z

#line 729
    texld r3, r1.xzzw, s7  // ::refractObjDepth<0>
    texld_pp r4, r1.xzzw, s11  // ::refractObjCol<0>

#line 735
    mov_pp r7.x, r4.x
    mad r0.w, v7.z, r2.w, -r3.x
    mov r7.w, r3.x

#line 732
    mad_pp r1.xy, r5, c0.xwzw, c0.x  // ::nonRefractedUv<0,1>
    texld_pp r2, r1, s11  // ::nonRefractObjCol<0,1,2>
    texld r3, r1, s7  // ::nonRefractObjDepth<0>
    mov r2.w, r3.x
    cmp r2, r0.w, r7, r2  // ::refractObjCol<0,1,2>, ::refractObjDepth<0>

#line 741
    mul r3, r5.y, c48
    mad r3, r5.x, c47, r3
    mad r3, r2.w, c49, r3
    add r3, r3, c50  // ::objWorldCoord<0,1,2,3>
    rcp r0.w, r3.w
    mad r1.xyz, r3, r0.w, -v6  // ::underwaterRefractedVec<0,1,2>
    dp3 r0.w, r1, r1
    rsq r0.w, r0.w
    rcp r1.x, r0.w  // ::distance<0>
    mul r0.w, r1.y, r0.w
    mul r0.w, r1.x, r0_abs.w

#line 751
    mul r1.x, r1.x, -c59.x
    mul r1.x, r1.x, c4.x
    exp r1.x, r1.x

#line 746
    max r1.y, r0.w, c6.z  // calcWaterRefractionColor::worldDepth<0>
    mul r0.w, r1.y, c59.y

#line 1362
    mad_sat r1.y, c60.w, r1.y, c60.z
    add_pp r1.y, -r1.y, c6.z  // ::foamLerp<0>

#line 748
    max r1.z, r0.w, c6.z  // ::deepWaterPow<0>
    log r3.x, c61.x
    log r3.y, c61.y
    log r3.z, c61.z
    mul r3.xyz, r1.z, r3
    exp_pp r4.x, r3.x  // ::deepWaterCol<0>
    exp_pp r4.y, r3.y  // ::deepWaterCol<1>
    exp_pp r4.z, r3.z  // ::deepWaterCol<2>
    mad r2.xyz, r4, -c61.w, r2
    mul_pp r3.xyz, r4, c61.w  // ::deepWaterCol<0,1,2>
    mad_pp r2.xyz, r1.x, r2, r3  // ::calcWaterRefractionColor<0,1,2>

#line 1359
    lrp_pp r3.xyz, r1.w, r2, r0  // ::finalWaterCol<0,1,2>

#line 1366
    add_pp r0.xyz, -r3, c63

#line 1322
    add r1.xz, c64.xyyw, v5.xyyw
    texld_pp r2, r1.xzzw, s4  // ::foamSampl<0>
    add r1.xz, c64.zyww, v5.xyyw
    texld_pp r4, r1.xzzw, s4  // ::foamSampl<1>

#line 1363
    add_pp r0.w, r2.x, r4.y

#line 1324
    add r1.xz, c65.xyyw, v5.xyyw
    texld_pp r2, r1.xzzw, s4  // ::foamSampl<2>

#line 1363
    add_pp r0.w, r0.w, r2.z

#line 1325
    add r1.xz, c65.zyww, v5.xyyw
    texld_pp r2, r1.xzzw, s4  // ::foamSampl<3>

#line 1363
    add_pp r0.w, r0.w, r2.w  // ::foamDensity<0>
    min_pp r1.x, r0.w, c6.z  // ::foamDensity<0>
    mul_pp r0.w, r1.y, r1.x  // ::foamLerp<0>
    mad_pp oC0.xyz, r0.w, r0, r3  // ::main<0,1,2>
    mov_pp oC0.w, c6.z  // ::main<3>

// approximately 203 instruction slots used (16 texture, 187 arithmetic)
