//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_ADNS_Dn_Em_Vd_WPos_Shdw_VNorm_VtxAtm_Rim_2DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   bool g__detailBools[2];
//   sampler2D g__detailMap;
//   sampler2D g__detailNormalMap;
//   float4 g__detailSelect;
//   float4 g__detailVariation;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   sampler2D g__normalMap;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   sampler2D g__specularMap;
//   float4 g__straussParms;
//   float4 g__straussParms1;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__detailBools           b0       1
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__straussParms1         c67      1
//   g__hdrTexParms           c68      1
//   g__detailSelect          c69      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__detailVariation       c87      1
//   g__dynamicLightingLights c100     6
//   g__albedoMap             s0       1
//   g__detailMap             s1       1
//   g__normalMap             s2       1
//   g__specularMap           s3       1
//   g__detailNormalMap       s4       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 4, 2, -1, 1.04999995
    def c9, 0.5, 0.349999994, 0.00999999978, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord2 v4  // IN<19,20,21,22>
    dcl_texcoord3 v5  // IN<23,24,25,26>
    dcl_texcoord4 v6  // IN<27,28,29,30>
    dcl_texcoord5 v7  // IN<31,32,33,34>
    dcl_texcoord6 v8.xy  // IN<35,36>
    dcl vFace  // IN<39>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 362 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_ADNS_Dn_Em_Vd_WPos_Shdw_VNorm_VtxAtm_Rim_2DL.final"
    cmp r0.x, vFace, c0.x, c0.y  // IN<39>

#line 356
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>
    nrm_pp r2.xyz, v3  // ::g__bx<0,1,2>
    nrm_pp r3.xyz, v4  // ::g__by<0,1,2>
    nrm_pp r4.xyz, v5  // ::g__bz<0,1,2>

#line 362
    cmp r0.x, -r0.x, c0.z, c0.x
    cmp r0.y, vFace, c0.w, c0.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 973
    texld_pp r5, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r6, c5, v0
    mul_pp r7, r5, r6  // ::diffuseSampl<0,1,2,3>

#line 979
    texld_pp r8, v7.zwzw, s3  // ::specSampl<0,1,2,3>
    mul_pp r0.yzw, c6.xxyz, v0.xxyz
    mul_pp r9.xyz, r8, r0.yzww  // ::specSampl<0,1,2>
    add_pp r1.w, r8.w, -c66.y
    mov r10.xy, c66  // ::g__straussParms<0,1>
    mad_pp r1.w, c67.x, r1.w, r10.y  // ::specSampl<3>
    mul_pp r1.w, r1.w, c66.w  // ::specSampl<3>
    max_pp r2.w, r1.w, c4.x  // ::specSampl<3>

#line 671
    texld_pp r11, v7, s2  // ::sampl<0,1,3>
    mad_pp r11.xy, r11, c4.y, c4.z  // ::sampl<0,1>
    dp2add_pp r1.w, r11, -r11, c0.x
    rsq_pp r1.w, r1.w
    rcp_pp r11.z, r1.w  // ::sampl<2>
    mul_pp r10.yzw, -r0.x, r11.xxyz  // ::sampl<0,1,2>

#line 671
    texld_pp r12, v8, s4  // ::sampl<0,1,3>
    mad_pp r11.xy, r12, c4.y, c4.z  // ::sampl<0,1>
    dp2add_pp r1.w, r11, -r11, c0.x
    rsq_pp r1.w, r1.w
    rcp_pp r11.z, r1.w  // ::sampl<2>
    mul_pp r11.xyz, -r0.x, r11  // ::sampl<0,1,2>

#line 665
    mov_sat_pp r1.w, r10.w
    add_pp r1.w, -r1.w, c4.w  // ::w0<0>
    mov_sat_pp r3.w, r11.z
    add_pp r3.w, -r3.w, c0.x  // ::w1<0>
    mul_pp r11.xyz, r11, r3.w
    mad_pp r10.yzw, r10, r1.w, r11.xxyz
    nrm_pp r11.xyz, r10.yzww  // ::combineNormals<0,1,2>

#line 990
    dp3_pp r2.x, r2, r11  // ::worldNormal<0>
    dp3_pp r2.y, r3, r11  // ::worldNormal<1>
    dp3_pp r2.z, r4, r11  // ::worldNormal<2>

#line 993
    mul_pp r2.xyz, -r0.x, r2  // ::worldNormal<0,1,2>
    mul_pp r1.xyz, r1, -r0.x  // ::g__vertexNormal<0,1,2>

#line 590
    texld_pp r3, v6.zwzw, s1  // ::detailSampl<0,1,2,3>
    dp4_pp r0.x, r3, c69
    lrp_pp r4.xyz, c87.x, r0.x, r3  // ::detailSampl<0,1,2>
    if b0
      mad_pp r3.xyz, r5, r6, r4  // ::col<0,1,2>
    else

#line 599
      mul_pp r3.xyz, r7, r4  // ::col<0,1,2>

#line 593
    endif

#line 781
    dp3_pp r0.x, r2, c3  // ::ndotl<0>
    mov_sat_pp r1.w, r0.x  // ::ndotl_satd<0>

#line 644
    texld_pp r4, r2, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.x, r2, r1
    mul_pp r4.xyz, r4, r1.x  // ::amb<0,1,2>
    mul_pp r4.xyz, r4, c1.w  // ::amb<0,1,2>
    mov_pp r5.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r4.xyz, r4, c72, r5  // ::amb<0,1,2>

#line 797
    add_pp r5.xyz, c10, -v2
    nrm_pp r6.xyz, r5  // ::viewVec<0,1,2>

#line 801
    add r5.xyz, r2, r2
    mad_pp r7.xyz, r5, r0.x, -c3  // ::RVec<0,1,2>
    dp3_sat_pp r1.y, r6, r7  // ::vdotr<0>
    pow_pp r3.w, r1.y, r2.w  // ::rs<0>
    mad_pp r0.yzw, r8.xxyz, r0, c0.y  // ::Cs<0,1,2>
    mad_pp r0.yzw, r0, r10.x, c0.x  // ::Cs<0,1,2>
    mul_pp r0.yzw, r0, c6.w  // ::Cs<0,1,2>
    mul_pp r7.xyz, r3.w, r0.yzww  // calcStrauss::Qs<0,1,2>

#line 818
    dp3_pp r1.y, -r6, r2
    add_pp r1.y, r1.y, r1.y
    mad_pp r8.xyz, r1.y, -r2, -r6  // ::reflectionVec<0,1,2>

#line 658
    texld_pp r8, r8, s8  // ::sampl<0,1,2,3>
    mad_pp r1.y, r8.w, c68.x, c68.y
    exp_pp r1.y, r1.y  // ::f<0>
    mul_pp r8.xyz, r8, r1.y
    mul_pp r8.xyz, r8, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 820
    mul_pp r8.xyz, r9, r8  // ::envMapColor<0,1,2>
    mad_pp r0.x, r0.x, c9.x, c9.x
    mul_pp r8.xyz, r8, r0.x  // calcStrauss::Qe<0,1,2>

#line 536
    dp3_pp r0.x, r6, r2  // ::dot_viewNrm<0>
    mov_sat_pp r1.y, -r2.y
    add_pp r1.y, -r1.y, c0.x  // ::vertAtten<0>
    abs_sat_pp r0.x, r0.x
    add_pp r0.x, -r0.x, c0.x  // ::rim<0>
    pow_pp r1.z, r0.x, c70.w  // ::rim<0>
    mul_pp r0.x, r1.y, r1.y
    mul_pp r0.x, r1.z, r0.x  // ::rim<0>
    mov_pp r9.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r9.xyz, -r9, c71
    mad_pp r9.xyz, r0.x, r9, c70  // ::ret<0,1,2>

#line 829
    mul_pp r9.xyz, r3, r9  // calcStrauss::Qr<0,1,2>

#line 296
    add r10.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.x, c11, r10  // ::lightSpacePos<3>
    add r10.xyz, r0.x, -c28.yzww  // ::delta<0,1,2>
    mul r11.xyz, c21, v2.y
    mad r11.xyz, v2.x, c20, r11
    mad r11.xyz, v2.z, c22, r11
    mad r11.xyz, v2.w, c23, r11  // ::lightSpacePos<0,1,2>
    mov r12, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r12, r10.x, r12, c24  // ::scaleOffset<0,1,2,3>
    cmp r12, r10.y, c26, r12  // ::scaleOffset<0,1,2,3>
    cmp r10, r10.z, c27, r12  // ::scaleOffset<0,1,2,3>
    mad r10.xy, r11, r10, r10.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r10.zw, r11.z, c0.xyxz, c0.xyzx
    texldp r10, r10, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    add r0.x, -r0.x, c30.z
    cmp r0.x, r0.x, r10.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.y, r0.x, c30.x  // ::calcShadow<0>

#line 1012
    mul_pp r10.xyz, r1.y, c2
    mad_pp r7.xyz, r3, r1.w, r7
    max_pp r0.x, c9.y, r1.y
    mul_pp r1.yzw, r8.xxyz, r0.x
    mul_pp r1.yzw, r11.w, r1
    mad_pp r1.yzw, r10.xxyz, r7.xxyz, r1
    mad_pp r1.yzw, r3.xxyz, r4.xxyz, r1
    mad_pp r1.yzw, r9.xxyz, c2.xxyz, r1  // ::Ir<0,1,2>

#line 530
    mad_pp r4.xyz, r1.yzww, c7.w, c7
    mul_pp r0.x, r11.w, c8.z
    lrp_pp r7.xyz, r0.x, r4, r1.yzww  // ::outCol<0,1,2>
    mad_pp r0.x, r5.w, -r6.w, r11.w
    mad_pp oC0.w, c8.w, r0.x, r7.w  // ::main<3>

#line 1018
    mov r4.x, v3.w
    mov r4.y, v4.w
    mov r4.z, v5.w
    mul_pp r1.yzw, r3.xxyz, r4.xxyz
    mad_pp r1.xyz, r1.yzww, r1.x, r7  // ::Ir<0,1,2>

#line 839
    add_pp r4.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.x, r4, r4
    rsq_pp r0.x, r0.x
    rcp_pp r1.w, r0.x  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.x  // ::lightVec<0,1,2>

#line 847
    add_pp r0.x, r1.w, -c102.x
    max_pp r1.w, r0.x, c9.z  // ::lightVecLenPrime<0>
    mul_pp r0.x, r1.w, r1.w
    mul_pp r0.x, r0.x, c102.w
    mad_pp r0.x, r1.w, c102.z, r0.x
    rcp_sat_pp r0.x, r0.x  // ::attenuation<0>
    mul_pp r7.xyz, r0.x, c100  // getDynamicPointLight::color<0,1,2>

#line 781
    dp3_pp r0.x, r2, r4  // ::ndotl<0>
    mov_sat_pp r1.w, r0.x  // ::ndotl_satd<0>

#line 801
    mad_pp r4.xyz, r5, r0.x, -r4  // ::RVec<0,1,2>
    dp3_sat_pp r0.x, r6, r4  // ::vdotr<0>
    pow_pp r3.w, r0.x, r2.w  // ::rs<0>

#line 810
    mul_pp r4.xyz, r0.yzww, r3.w  // calcStrauss::Qs<0,1,2>

#line 886
    mad_pp r4.xyz, r3, r1.w, r4  // ::Qd<0,1,2>

#line 839
    add_pp r8.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.x, r8, r8
    rsq_pp r0.x, r0.x
    rcp_pp r1.w, r0.x  // ::lightVecLen<0>
    mul_pp r8.xyz, r8, r0.x  // ::lightVec<0,1,2>

#line 847
    add_pp r0.x, r1.w, -c105.x
    max_pp r1.w, r0.x, c9.z  // ::lightVecLenPrime<0>
    mul_pp r0.x, r1.w, r1.w
    mul_pp r0.x, r0.x, c105.w
    mad_pp r0.x, r1.w, c105.z, r0.x
    rcp_sat_pp r0.x, r0.x  // ::attenuation<0>
    mul_pp r9.xyz, r0.x, c103  // getDynamicPointLight::color<0,1,2>

#line 781
    dp3_pp r0.x, r2, r8  // ::ndotl<0>
    mov_sat_pp r1.w, r0.x  // ::ndotl_satd<0>

#line 801
    mad_pp r2.xyz, r5, r0.x, -r8  // ::RVec<0,1,2>
    dp3_sat_pp r0.x, r6, r2  // ::vdotr<0>
    pow_pp r3.w, r0.x, r2.w  // ::rs<0>

#line 810
    mul_pp r0.xyz, r0.yzww, r3.w  // calcStrauss::Qs<0,1,2>

#line 891
    mad_pp r0.xyz, r3, r1.w, r0  // ::Qd<0,1,2>
    mul_pp r0.xyz, r9, r0  // ::Qd<0,1,2>
    mad_pp r0.xyz, r4, r7, r0  // ::Ir<0,1,2>

#line 1021
    add_pp oC0.xyz, r1, r0  // ::main<0,1,2>

// approximately 192 instruction slots used (8 texture, 184 arithmetic)
