//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_VolumetricDepth_ProjPos.pso
//
//
// Parameters:
//
//   float4 g__RT;
//   sampler2D g__depthEncodeMap;
//   sampler2D g__specularMap;
//   float4 g__viewPort;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g__viewPort       c38      1
//   g__RT             c41      1
//   g__specularMap    s3       1
//   g__depthEncodeMap s9       1
//

    ps_3_0
    def c0, 1, 0.03125, 0.0009765625, 0.5
    def c1, 0, 0, 0, 0
    dcl_texcoord v0  // IN<8,9,10,11>
    dcl_texcoord2 v1.xyw  // IN<12,13,15>
    dcl_2d s3
    dcl_2d s9

#line 1139 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_VolumetricDepth_ProjPos.final"
    rcp r0.x, c41.x
    rcp r0.y, c41.y
    mul r0, r0.xyxy, c38.zwxy  // ::viewportRatio<0,1>, ::viewportOffset<0,1>

#line 1135
    rcp r1.x, v1.w
    mad r1.xy, v1, r1.x, c0.x  // ::screenUV<0,1>
    mul r1.x, r1.x, c0.w  // ::screenUV<0>

#line 1141
    mad r1.z, r1.y, -c0.w, c0.x
    mad r0.xy, r1.xzzw, r0, r0.zwzw  // ::screenUV<0,1>
    texld r0, r0, s3  // ::compareColor<0,1,2>
    dp3 r0.w, r0, c0  // ::depthCompare<0>

#line 1131
    texld r1, v0, s9  // ::color<0,1>
    texld r2, v0.zwzw, s9  // ::color<2>
    mov r1.z, r2.x
    dp3 r1.w, r1, c0  // ::depthCurrent<0>

#line 1145
    add r0.w, -r0.w, r1.w
    cmp_pp oC0.xyz, r0.w, r0, r1  // ::main<0,1,2>
    mov_pp oC0.w, c1.x  // ::main<3>

// approximately 17 instruction slots used (3 texture, 14 arithmetic)
