//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_SpeedTree_Branch_Lit_AD_Shdw_WPos_Vd_VNorm_VtxAtm_2DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   sampler2D g__detailMap;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     6
//   g__albedoMap             s0       1
//   g__detailMap             s1       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 1, 0, 0.00999999978, 0
    dcl_color v0.xyz  // IN<4,5,6>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord4 v4.xyz  // IN<19,20,21>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s5
    dcl_cube s6

#line 802 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_SpeedTree_Branch_Lit_AD_Shdw_WPos_Vd_VNorm_VtxAtm_2DL.final"
    add_pp r0.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 810
    add_pp r0.w, r1.x, -c102.x
    max_pp r1.x, r0.w, c0.z  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.x, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 802
    add_pp r2.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 810
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c0.z  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 990
    texld_pp r4, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r4, r4, c5  // ::diffuseSampl<0,1,2,3>
    mul_pp r5.xyz, r4, v0  // ::diffuseSampl<0,1,2>

#line 576
    texld_pp r6, v3.zwzw, s1  // ::detailSampl<0,1,2,3>

#line 580
    mad_pp r4.xyz, r4, -v0, r6
    mad_pp r4.xyz, r6.w, r4, r5  // ::col<0,1,2>

#line 1028
    mov_pp oC0.w, r4.w  // ::main<3>

#line 345
    nrm_pp r5.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 702
    dp3_sat_pp r0.w, r5, r2
    mul_pp r6.xyz, r4, r0.w  // calcLambert::Qd<0,1,2>

#line 713
    add_pp r7.xyz, c10, -v2
    dp3_pp r0.w, r7, r7
    rsq_pp r0.w, r0.w

#line 717
    mad_pp r2.xyz, r7, r0.w, r2
    nrm_pp r8.xyz, r2  // ::HVec<0,1,2>
    dp3_sat_pp r1.w, r5, r8  // ::ndoth<0>
    pow_pp r2.x, r1.w, c6.w  // ::rs<0>

#line 1005
    mul_pp r2.yzw, c6.xxyz, v0.xxyz  // ::specSampl<0,1,2>

#line 720
    mul_pp r8.xyz, r2.x, r2.yzww  // calcLambert::Qs<0,1,2>

#line 834
    mad_pp r6.xyz, r6, c7.w, r8  // ::Qd<0,1,2>
    mul_pp r3.xyz, r3, r6  // ::Qd<0,1,2>

#line 717
    mad_pp r6.xyz, r7, r0.w, r0

#line 702
    dp3_sat_pp r0.x, r5, r0
    mul_pp r0.xyz, r4, r0.x  // calcLambert::Qd<0,1,2>

#line 717
    mad_pp r7.xyz, r7, r0.w, c3
    nrm_pp r8.xyz, r7  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r5, r8  // ::ndoth<0>
    pow_pp r1.w, r0.w, c6.w  // ::rs<0>
    mul_pp r7.xyz, r2.yzww, r1.w  // calcLambert::Qs<0,1,2>

#line 717
    nrm_pp r8.xyz, r6  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r5, r8  // ::ndoth<0>
    pow_pp r1.w, r0.w, c6.w  // ::rs<0>
    mul_pp r2.xyz, r2.yzww, r1.w  // calcLambert::Qs<0,1,2>

#line 829
    mad_pp r0.xyz, r0, c7.w, r2  // ::Qd<0,1,2>

#line 836
    mad_pp r0.xyz, r0, r1, r3  // ::Ir<0,1,2>

#line 296
    add r1.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r1  // ::lightSpacePos<3>
    add r1.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r2, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r2, r1.x, r2, c24  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.y, c26, r2  // ::scaleOffset<0,1,2,3>
    cmp r1, r1.z, c27, r2  // ::scaleOffset<0,1,2,3>

#line 299
    mul r2.xyz, c21, v2.y
    mad r2.xyz, v2.x, c20, r2
    mad r2.xyz, v2.z, c22, r2
    mad r2.xyz, v2.w, c23, r2  // ::lightSpacePos<0,1,2>

#line 304
    mad r1.xy, r2, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r1.zw, r2.z, c0.xyxy, c0.xyyx
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r1.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.x, r0.w, c30.x  // ::calcShadow<0>

#line 1024
    mul_pp r1.xyz, r1.x, c2

#line 625
    texld_pp r2, r5, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r5, r5

#line 702
    dp3_sat_pp r1.w, r5, c3
    mul_pp r3.xyz, r4, r1.w  // calcLambert::Qd<0,1,2>

#line 1024
    mad_pp r3.xyz, r3, c7.w, r7

#line 626
    mul_pp r2.xyz, r2, r0.w  // ::amb<0,1,2>
    mul_pp r2.xyz, r2, c1.w  // ::amb<0,1,2>
    mov_pp r5.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r2.xyz, r2, c72, r5  // ::amb<0,1,2>
    mul_pp r2.xyz, r2, c7
    mul_pp r2.xyz, r4, r2

#line 729
    add_pp r2.xyz, r2, r2  // calcLambert::Qa<0,1,2>

#line 1024
    mad_pp r1.xyz, r1, r3, r2  // ::Ir<0,1,2>
    mad_pp r1.xyz, v4, r4, r1  // ::Ir<0,1,2>

#line 1028
    add_pp oC0.xyz, r0, r1  // ::main<0,1,2>

// approximately 106 instruction slots used (4 texture, 102 arithmetic)
