//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_AD_Vd_WPos_Shdw_VNorm_VtxAtm_Rim_3DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   bool g__detailBools[2];
//   sampler2D g__detailMap;
//   float4 g__detailSelect;
//   float4 g__detailVariation;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__straussParms;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__detailBools           b0       1
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__detailSelect          c69      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__detailVariation       c87      1
//   g__dynamicLightingLights c100     9
//   g__albedoMap             s0       1
//   g__detailMap             s1       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 4, 0.00999999978, 0, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord4 v4.xyz  // IN<19,20,21>
    dcl vFace  // IN<23>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s5
    dcl_cube s6

#line 348 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_AD_Vd_WPos_Shdw_VNorm_VtxAtm_Rim_3DL.final"
    cmp r0.x, vFace, c0.x, c0.y  // IN<23>

#line 345
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 348
    cmp r0.x, -r0.x, c0.z, c0.x
    cmp r0.y, vFace, c0.w, c0.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 948
    texld_pp r2, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r3, c5, v0
    mul_pp r4, r2, r3  // ::diffuseSampl<0,1,2,3>

#line 956
    mul_pp r0.y, c66.w, c66.y  // ::specSampl<3>
    max_pp r1.w, r0.y, c4.x  // ::specSampl<3>

#line 963
    mul_pp r0.xyz, r1, -r0.x  // ::worldNormal<0,1,2>

#line 576
    texld_pp r5, v3.zwzw, s1  // ::detailSampl<0,1,2,3>
    dp4_pp r0.w, r5, c69
    lrp_pp r1.xyz, c87.x, r0.w, r5  // ::detailSampl<0,1,2>
    if b0
      mad_pp r2.xyz, r2, r3, r1  // ::col<0,1,2>
    else

#line 585
      mul_pp r2.xyz, r4, r1  // ::col<0,1,2>

#line 579
    endif

#line 754
    dp3_pp r0.w, r0, c3  // ::ndotl<0>
    mov_sat_pp r1.x, r0.w  // ::ndotl_satd<0>

#line 630
    texld_pp r5, r0, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.y, r0, r0
    mul_pp r3.xyz, r5, r1.y  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r4  // ::amb<0,1,2>

#line 761
    mul_pp r3.xyz, r2, r3  // calcStrauss::Qa<0,1,2>

#line 770
    add_pp r4.xyz, c10, -v2
    nrm_pp r5.xyz, r4  // ::viewVec<0,1,2>

#line 774
    add r4.xyz, r0, r0
    mad_pp r6.xyz, r4, r0.w, -c3  // ::RVec<0,1,2>
    dp3_sat_pp r0.w, r5, r6  // ::vdotr<0>
    pow_pp r5.w, r0.w, r1.w  // ::rs<0>
    mov r6.xy, c0
    mad_pp r6.yzw, v0.xxyz, c6.xxyz, r6.y  // ::Cs<0,1,2>
    mad_pp r6.xyz, r6.yzww, c66.x, r6.x  // ::Cs<0,1,2>
    mul_pp r6.xyz, r6, c6.w  // ::Cs<0,1,2>
    mul_pp r7.xyz, r5.w, r6  // calcStrauss::Qs<0,1,2>

#line 522
    dp3_pp r0.w, r5, r0  // ::dot_viewNrm<0>
    mov_sat_pp r1.z, -r0.y
    add_pp r1.z, -r1.z, c0.x  // ::vertAtten<0>
    abs_sat_pp r0.w, r0.w
    add_pp r0.w, -r0.w, c0.x  // ::rim<0>
    pow_pp r5.w, r0.w, c70.w  // ::rim<0>
    mul_pp r0.w, r1.z, r1.z
    mul_pp r0.w, r5.w, r0.w  // ::rim<0>
    mov_pp r8.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r8.xyz, -r8, c71
    mad_pp r8.xyz, r0.w, r8, c70  // ::ret<0,1,2>

#line 795
    mul_pp r8.xyz, r2, r8  // calcStrauss::Qr<0,1,2>

#line 296
    add r9.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r9  // ::lightSpacePos<3>
    add r9.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>
    mul r10.xyz, c21, v2.y
    mad r10.xyz, v2.x, c20, r10
    mad r10.xyz, v2.z, c22, r10
    mad r10.xyz, v2.w, c23, r10  // ::lightSpacePos<0,1,2>
    mov r11, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r11, r9.x, r11, c24  // ::scaleOffset<0,1,2,3>
    cmp r11, r9.y, c26, r11  // ::scaleOffset<0,1,2,3>
    cmp r9, r9.z, c27, r11  // ::scaleOffset<0,1,2,3>
    mad r9.xy, r10, r9, r9.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r9.zw, r10.z, c0.xyxz, c0.xyzx
    texldp r9, r9, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    add r0.w, -r0.w, c30.z
    cmp r0.w, r0.w, r9.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.z, r0.w, c30.x  // ::calcShadow<0>

#line 982
    mul_pp r9.xyz, r1.z, c2
    mad_pp r7.xyz, r2, r1.x, r7
    mad_pp r3.xyz, r9, r7, r3
    mad_pp r3.xyz, r8, c2, r3  // ::Ir<0,1,2>

#line 516
    mad_pp r7.xyz, r3, c7.w, c7
    lrp_pp r8.xyz, c8.z, r7, r3  // ::outCol<0,1,2>
    mad_pp r0.w, r2.w, -r3.w, c0.x
    mad_pp oC0.w, c8.w, r0.w, r4.w  // ::main<3>

#line 988
    mul_pp r3.xyz, r2, v4
    mad_pp r1.xyz, r3, r1.y, r8  // ::Ir<0,1,2>

#line 805
    add_pp r3.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r3, r3
    rsq_pp r0.w, r0.w
    rcp_pp r2.w, r0.w  // ::lightVecLen<0>
    mul_pp r3.xyz, r3, r0.w  // ::lightVec<0,1,2>

#line 813
    add_pp r0.w, r2.w, -c102.x
    max_pp r2.w, r0.w, c4.y  // ::lightVecLenPrime<0>
    mul_pp r0.w, r2.w, r2.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r2.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r7.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 754
    dp3_pp r0.w, r0, r3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w  // ::ndotl_satd<0>

#line 774
    mad_pp r3.xyz, r4, r0.w, -r3  // ::RVec<0,1,2>
    dp3_sat_pp r0.w, r5, r3  // ::vdotr<0>
    pow_pp r3.x, r0.w, r1.w  // ::rs<0>

#line 783
    mul_pp r3.xyz, r6, r3.x  // calcStrauss::Qs<0,1,2>

#line 856
    mad_pp r3.xyz, r2, r2.w, r3  // ::Qd<0,1,2>

#line 805
    add_pp r8.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r8, r8
    rsq_pp r0.w, r0.w
    rcp_pp r2.w, r0.w  // ::lightVecLen<0>
    mul_pp r8.xyz, r8, r0.w  // ::lightVec<0,1,2>

#line 813
    add_pp r0.w, r2.w, -c105.x
    max_pp r2.w, r0.w, c4.y  // ::lightVecLenPrime<0>
    mul_pp r0.w, r2.w, r2.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r2.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r9.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 754
    dp3_pp r0.w, r0, r8  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w  // ::ndotl_satd<0>

#line 774
    mad_pp r8.xyz, r4, r0.w, -r8  // ::RVec<0,1,2>
    dp3_sat_pp r0.w, r5, r8  // ::vdotr<0>
    pow_pp r3.w, r0.w, r1.w  // ::rs<0>

#line 783
    mul_pp r8.xyz, r6, r3.w  // calcStrauss::Qs<0,1,2>

#line 861
    mad_pp r8.xyz, r2, r2.w, r8  // ::Qd<0,1,2>
    mul_pp r8.xyz, r9, r8  // ::Qd<0,1,2>
    mad_pp r3.xyz, r3, r7, r8  // ::Ir<0,1,2>

#line 805
    add_pp r7.xyz, c107, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r7, r7
    rsq_pp r0.w, r0.w
    rcp_pp r2.w, r0.w  // ::lightVecLen<0>
    mul_pp r7.xyz, r7, r0.w  // ::lightVec<0,1,2>

#line 813
    add_pp r0.w, r2.w, -c108.x
    max_pp r2.w, r0.w, c4.y  // ::lightVecLenPrime<0>
    mul_pp r0.w, r2.w, r2.w
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r2.w, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r8.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 754
    dp3_pp r0.x, r0, r7  // ::ndotl<0>
    mov_sat_pp r0.y, r0.x  // ::ndotl_satd<0>

#line 774
    mad_pp r0.xzw, r4.xyyz, r0.x, -r7.xyyz  // ::RVec<0,1,2>
    dp3_sat_pp r0.x, r5, r0.xzww  // ::vdotr<0>
    pow_pp r2.w, r0.x, r1.w  // ::rs<0>

#line 783
    mul_pp r0.xzw, r6.xyyz, r2.w  // calcStrauss::Qs<0,1,2>

#line 866
    mad_pp r0.xyz, r2, r0.y, r0.xzww  // ::Qd<0,1,2>
    mad_pp r0.xyz, r0, r8, r3  // ::Ir<0,1,2>

#line 991
    add_pp oC0.xyz, r1, r0  // ::main<0,1,2>

// approximately 155 instruction slots used (4 texture, 151 arithmetic)
