//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_Refraction_T1_T2_Em_WPos_ProjPos_VNorm_Shdw_VtxAtm_4DL.pso
//
//
// Parameters:
//
//   float4 g__RT;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   sampler2D g__backBufferMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__deepWaterColor;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   row_major float4x4 g__invViewProjMatrix;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__viewPort;
//   float4 g__waterFresnelParams;
//   sampler2D g__waterNormalMap1;
//   sampler2D g__waterNormalMap2;
//   float4 g__waterNormalScale;
//   float4 g__waterParams[2];
//   float4 g__waterRefractionParams;
//   sampler2D g__zMap;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__viewPort              c38      1
//   g__RT                    c41      1
//   g__invViewProjMatrix     c47      4
//   g__waterFresnelParams    c57      1
//   g__waterRefractionParams c58      1
//   g__waterParams           c59      2
//   g__deepWaterColor        c61      1
//   g__waterNormalScale      c62      1
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100    12
//   g__waterNormalMap1       s1       1
//   g__waterNormalMap2       s2       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__zMap                  s7       1
//   g__envMap                s8       1
//   g__backBufferMap         s11      1
//

    ps_3_0
    def c0, 0.5, 1, 0, 0.00999999978
    def c4, 2, -1, 1, 64
    def c6, 0.5, -0.5, 1.44269502, 0
    dcl_texcoord v0.xyz  // IN<4,5,6>
    dcl_texcoord1 v1.xyz  // IN<8,9,10>
    dcl_texcoord2 v2.xyz  // IN<12,13,14>
    dcl_texcoord3 v3.zw  // IN<18,19>
    dcl_texcoord4 v4.xy  // IN<20,21>
    dcl_texcoord6 v5  // IN<24,25,26,27>
    dcl_texcoord9 v6  // IN<28,29,30,31>
    dcl_2d s1
    dcl_2d s2
    dcl_2d s5
    dcl_cube s6
    dcl_2d s7
    dcl_cube s8
    dcl_2d s11

#line 889 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_Refraction_T1_T2_Em_WPos_ProjPos_VNorm_Shdw_VtxAtm_4DL.final"
    add_pp r0.xyz, c110, -v5  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 897
    add_pp r0.w, r1.x, -c111.x
    max_pp r1.x, r0.w, c0.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c111.w
    mad_pp r0.w, r1.x, c111.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c109  // getDynamicPointLight::color<0,1,2>

#line 889
    add_pp r2.xyz, c107, -v5  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 897
    add_pp r0.w, r1.w, -c108.x
    max_pp r1.w, r0.w, c0.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r1.w, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 889
    add_pp r4.xyz, c101, -v5  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 897
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c0.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 889
    add_pp r6.xyz, c104, -v5  // ::lightVec<0,1,2>
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 897
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c0.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r7.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 662
    texld_pp r8, v3.zwzw, s1  // ::sampl<0,1>
    mad_pp r8.xy, r8, c4.x, c4.y  // ::sampl<0,1>
    dp2add_pp r0.w, r8, -r8, c4.z

#line 1355
    mul_pp r8.xy, r8, c62.x  // ::normSmpl<0,1>

#line 664
    rsq_pp r0.w, r0.w
    rcp_pp r8.z, r0.w  // ::sampl<2>
    texld_pp r9, v4, s2  // ::sampl<0,1,3>
    mad_pp r9.xy, r9, c4.x, c4.y  // ::sampl<0,1>
    dp2add_pp r0.w, r9, -r9, c4.z

#line 1356
    mul_pp r9.xy, r9, c62.y  // ::normSmpl<3,4>

#line 664
    rsq_pp r0.w, r0.w
    rcp_pp r9.z, r0.w  // ::sampl<2>

#line 1361
    add_pp r8.xyz, r8, r9
    nrm_pp r9.xyz, r8  // ::combSampl<0,1,2>

#line 344
    nrm_pp r8.xyz, v0  // ::g__bx<0,1,2>

#line 1363
    dp3_pp r10.x, r8, r9  // ::worldNormal<0>

#line 636
    mov_pp r8.x, r8.z

#line 345
    nrm_pp r11.xyz, v1  // ::g__by<0,1,2>

#line 1363
    dp3_pp r10.y, r11, r9  // ::worldNormal<1>

#line 636
    mov_pp r8.y, r11.z

#line 346
    nrm_pp r11.xyz, v2  // ::g__bz<0,1,2>

#line 1363
    dp3_pp r10.z, r11, r9  // ::worldNormal<2>

#line 636
    mov_pp r8.z, r11.z
    dp3_sat_pp r0.w, r10, r8

#line 776
    dp3_sat_pp r1.w, r10, r6
    mul_pp r6.xyz, r1.w, c5  // calcLambert::Qd<0,1,2>

#line 920
    mul_pp r6.xyz, r7, r6  // ::Qd<0,1,2>

#line 776
    dp3_sat_pp r1.w, r10, r4
    mul_pp r4.xyz, r1.w, c5  // calcLambert::Qd<0,1,2>

#line 921
    mad_pp r4.xyz, r4, r5, r6  // ::Ir<0,1,2>

#line 776
    dp3_sat_pp r1.w, r10, r2
    mul_pp r2.xyz, r1.w, c5  // calcLambert::Qd<0,1,2>

#line 925
    mad_pp r2.xyz, r2, r3, r4  // ::Ir<0,1,2>

#line 776
    dp3_sat_pp r0.x, r10, r0
    mul_pp r0.xyz, r0.x, c5  // calcLambert::Qd<0,1,2>

#line 929
    mad_pp r0.xyz, r0, r1, r2  // ::Ir<0,1,2>

#line 303
    mul r1.xyz, c21, v5.y
    mad r1.xyz, v5.x, c20, r1
    mad r1.xyz, v5.z, c22, r1
    mad r1.xyz, v5.w, c23, r1  // ::lightSpacePos<0,1,2>

#line 300
    add r2.xyz, -c10, v5  // ::delta<0,1,2>
    dp3 r1.w, c11, r2  // ::lightSpacePos<3>

#line 697
    nrm_pp r3.xyz, r2  // ::eyeVec<0,1,2>

#line 302
    add r2.xyz, r1.w, -c28.yzww  // ::delta<0,1,2>

#line 315
    add r1.w, -r1.w, c30.z

#line 305
    mov r4, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r4, r2.x, r4, c24  // ::scaleOffset<0,1,2,3>
    cmp r4, r2.y, c26, r4  // ::scaleOffset<0,1,2,3>
    cmp r2, r2.z, c27, r4  // ::scaleOffset<0,1,2,3>
    mad r2.xy, r1, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r2.zw, r1.z, c0.xyyz, c0.xyzy
    texldp r2, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r1.x, r1.w, r2.x, c4.z  // ::shadowValue<0>
    max_sat_pp r2.x, r1.x, c30.x  // ::calcShadow<0>

#line 1375
    mul_pp r1.xyz, r2.x, c2

#line 786
    add_pp r2.xyz, c10, -v5
    dp3_pp r1.w, r2, r2
    rsq_pp r1.w, r1.w

#line 790
    mad_pp r4.xyz, r2, r1.w, c3

#line 786
    mul_pp r2.xyz, r2, r1.w  // ::viewVec<0,1,2>

#line 790
    nrm_pp r5.xyz, r4  // ::HVec<0,1,2>
    dp3_sat_pp r1.w, r10, r5  // ::ndoth<0>
    pow_pp r2.w, r1.w, c4.w  // ::rs<0>

#line 776
    dp3_pp r1.w, r10, c3  // ::ndotl<0>
    mov_sat_pp r3.w, r1.w

#line 813
    mad_pp r1.w, r1.w, c0.x, c0.x

#line 1375
    mad_pp r4.xyz, r3.w, c5, r2.w

#line 635
    texld_pp r5, r10, s6  // ::amb<0,1,2>
    mul_pp r5.xyz, r0.w, r5  // ::amb<0,1,2>
    mul_pp r5.xyz, r5, c1.w  // ::amb<0,1,2>
    mov_pp r6.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r5.xyz, r5, c72, r6  // ::amb<0,1,2>

#line 802
    mul_pp r5.xyz, r5, c5  // calcLambert::Qa<0,1,2>

#line 1375
    mad_pp r1.xyz, r1, r4, r5  // ::Ir<0,1,2>

#line 1380
    add_pp r0.xyz, r0, r1  // ::Ir<0,1,2>

#line 810
    dp3_pp r0.w, -r2, r10
    add_pp r0.w, r0.w, r0.w
    mad_pp r1.xyz, r0.w, -r10, -r2  // ::reflectionVec<0,1,2>

#line 1390
    dp3_sat_pp r0.w, r2, r10
    pow_pp r2.x, r0.w, c57.y
    mad_sat_pp r0.w, c57.x, r2.x, c57.z  // ::fresnelTerm<0>

#line 649
    texld_pp r2, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r1.x, r2.w, c68.x, c68.y
    exp_pp r1.x, r1.x  // ::f<0>
    mul_pp r1.xyz, r2, r1.x
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 813
    mul_pp r1.xyz, r1.w, r1  // calcLambert::Qe<0,1,2>

#line 1396
    mul_pp r1.xyz, r1, c59.w
    mad_pp r0.xyz, r0, c59.z, r1  // ::reflectCol<0,1,2>

#line 700
    mul_pp r1.xyz, c58, c58
    dp3_pp r1.w, r3, r10
    mad_pp r2.x, r1.w, -r1.w, c4.z
    mad_pp r1.xyz, r1, -r2.x, c4.z
    cmp_pp r2.xyz, r1, c0.y, c0.z
    mul_pp r1.xyz, r1, r2
    mul_pp r2.xyz, r2, c58
    rsq_pp r1.y, r1.y
    rcp_pp r1.y, r1.y
    mad_pp r1.y, r2.y, r1.w, r1.y
    mul_pp r4.xyz, r10, r1.y
    mad_pp r4.xyz, r2.y, r3, -r4  // ::refractVecG<0,1,2>

#line 704
    dp3_sat_pp r1.y, r3, r4  // ::refractedAngleOffsetScale<0>

#line 708
    abs_pp r4, c60.xyxy
    add_pp r4, -r4, c4.z

#line 711
    mad_pp r2.yw, r4.xxzy, -c0.x, c0.y
    mul_pp r4, r4, c6.xxxy  // ::indexScaler<0,1,0,1>
    cmp_pp r2.yw, c60.xxzy, r4.xxzy, r2  // ::indexOffset<0,1>

#line 715
    rcp r3.w, v6.w
    mul_pp r4.xy, r3.w, v6  // ::projPos<0,1>
    mad_pp r2.yw, r4.xxzy, r4.xzzw, r2  // ::refractedUvBase<0,1>

#line 719
    mad_pp r4.zw, c60.xyxy, r1.y, r2.xyyw  // ::refractedUvG<0,1>

#line 713
    rcp r5.x, c41.x
    rcp r5.y, c41.y
    mul_pp r5, r5.xyxy, c38.zwxy  // ::viewportRatio<0,1>, ::viewportOffset<0,1>

#line 721
    mad_pp r4.zw, r4, r5.xyxy, r5  // ::refractedUvG<0,1>

#line 725
    texld_pp r6, r4.zwzw, s11  // ::refractObjCol<1>

#line 700
    rsq_pp r1.y, r1.z
    rsq_pp r1.x, r1.x
    rcp_pp r1.x, r1.x
    mad_pp r1.x, r2.x, r1.w, r1.x
    mul_pp r7.xyz, r10, r1.x
    mad_pp r7.xyz, r2.x, r3, -r7  // ::refractVec<0,1,2>

#line 702
    dp3_sat_pp r1.x, r3, r7  // ::refractedAngleOffsetScale<0>

#line 717
    mad_pp r1.xz, c60.xyyw, r1.x, r2.yyww  // ::refractedUv<0,1>
    mad_pp r1.xz, r1, r5.xyyw, r5.zyww  // ::refractedUv<0,1>

#line 700
    rcp_pp r1.y, r1.y
    mad_pp r1.y, r2.z, r1.w, r1.y
    mul_pp r7.xyz, r10, r1.y
    mad_pp r7.xyz, r2.z, r3, -r7  // ::refractVecB<0,1,2>

#line 706
    dp3_sat_pp r1.y, r3, r7  // ::refractedAngleOffsetScale<0>

#line 720
    mad_pp r1.yw, c60.xxzy, r1.y, r2  // ::refractedUvB<0,1>
    mad_pp r1.yw, r1, r5.xxzy, r5.xzzw  // ::refractedUvB<0,1>

#line 726
    texld_pp r2, r1.ywzw, s11  // ::refractObjCol<2>

#line 730
    mov_pp r6.z, r2.z

#line 724
    texld r2, r1.xzzw, s7  // ::refractObjDepth<0>
    texld_pp r1, r1.xzzw, s11  // ::refractObjCol<0>

#line 730
    mov_pp r6.x, r1.x
    mad r1.x, v6.z, r3.w, -r2.x
    mov r6.w, r2.x

#line 727
    mad_pp r1.yz, r4.xxyw, c6.xxyw, c6.x  // ::nonRefractedUv<0,1>
    texld_pp r2, r1.yzzw, s11  // ::nonRefractObjCol<0,1,2>
    texld r3, r1.yzzw, s7  // ::nonRefractObjDepth<0>
    mov r2.w, r3.x
    cmp r1, r1.x, r6, r2  // ::refractObjCol<0,1,2>, ::refractObjDepth<0>

#line 736
    mul r2, r4.y, c48
    mad r2, r4.x, c47, r2
    mad r2, r1.w, c49, r2
    add r2, r2, c50  // ::objWorldCoord<0,1,2,3>
    rcp r1.w, r2.w
    mad r2.xyz, r2, r1.w, -v5  // ::underwaterRefractedVec<0,1,2>
    dp3 r1.w, r2, r2
    rsq r1.w, r1.w
    rcp r2.x, r1.w  // ::distance<0>
    mul r1.w, r2.y, r1.w
    mul r1.w, r2.x, r1_abs.w

#line 746
    mul r2.x, r2.x, -c59.x
    mul r2.x, r2.x, c6.z
    exp r2.x, r2.x

#line 741
    max r2.y, r1.w, c4.z  // calcWaterRefractionColor::worldDepth<0>
    mul r1.w, r2.y, c59.y
    max r2.y, r1.w, c4.z  // ::deepWaterPow<0>
    log r3.x, c61.x
    log r3.y, c61.y
    log r3.z, c61.z
    mul r2.yzw, r2.y, r3.xxyz
    exp_pp r3.x, r2.y  // ::deepWaterCol<0>
    exp_pp r3.y, r2.z  // ::deepWaterCol<1>
    exp_pp r3.z, r2.w  // ::deepWaterCol<2>
    mad r1.xyz, r3, -c61.w, r1
    mul_pp r2.yzw, r3.xxyz, c61.w  // ::deepWaterCol<0,1,2>
    mad_pp r1.xyz, r2.x, r1, r2.yzww  // ::calcWaterRefractionColor<0,1,2>

#line 1401
    add_pp r1.xyz, -r0, r1
    mad_pp oC0.xyz, r0.w, r1, r0  // ::main<0,1,2>
    mov_pp oC0.w, c4.z  // ::main<3>

// approximately 240 instruction slots used (11 texture, 229 arithmetic)
