//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_AD_Dn_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_2DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   bool g__detailBools[2];
//   sampler2D g__detailMap;
//   sampler2D g__detailNormalMap;
//   float4 g__detailSelect;
//   float4 g__detailVariation;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__straussParms;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__detailBools           b0       1
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__hdrTexParms           c68      1
//   g__detailSelect          c69      1
//   g__ambientCubeMapColor   c72      1
//   g__detailVariation       c87      1
//   g__dynamicLightingLights c100     6
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__detailMap             s1       1
//   g__detailNormalMap       s4       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 4, 2, -1, 0.5
    def c9, 0.349999994, 0.00999999978, 0, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3  // IN<16,17,18,19>
    dcl_texcoord2 v4  // IN<20,21,22,23>
    dcl_texcoord3 v5  // IN<24,25,26,27>
    dcl_texcoord4 v6  // IN<28,29,30,31>
    dcl_texcoord6 v7.xy  // IN<32,33>
    dcl vFace  // IN<36>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 358 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_AD_Dn_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_2DL.final"
    cmp r0.x, vFace, c0.x, c0.y  // IN<36>

#line 352
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>
    nrm_pp r2.xyz, v3  // ::g__bx<0,1,2>
    nrm_pp r3.xyz, v4  // ::g__by<0,1,2>
    nrm_pp r4.xyz, v5  // ::g__bz<0,1,2>

#line 358
    cmp r0.x, -r0.x, c0.z, c0.x
    cmp r0.y, vFace, c0.w, c0.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 984
    texld_pp r5, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r6, c5, v0
    mul_pp r7, r5, r6  // ::diffuseSampl<0,1,2,3>

#line 990
    mul_pp r0.yzw, c6.xxyz, v0.xxyz  // ::specSampl<0,1,2>
    mul_pp r1.w, c66.w, c66.y  // ::specSampl<3>
    max_pp r2.w, r1.w, c4.x  // ::specSampl<3>

#line 670
    texld_pp r8, v7, s4  // ::sampl<0,1,3>
    mad_pp r8.xy, r8, c4.y, c4.z  // ::sampl<0,1>
    dp2add_pp r1.w, r8, -r8, c0.x
    rsq_pp r1.w, r1.w
    rcp_pp r8.z, r1.w  // ::sampl<2>
    mul_pp r8.xyz, -r0.x, r8  // ::sampl<0,1,2>

#line 999
    dp3_pp r2.x, r2, r8  // ::worldNormal<0>
    dp3_pp r2.y, r3, r8  // ::worldNormal<1>
    dp3_pp r2.z, r4, r8  // ::worldNormal<2>

#line 1002
    mul_pp r2.xyz, -r0.x, r2  // ::worldNormal<0,1,2>
    mul_pp r1.xyz, r1, -r0.x  // ::g__vertexNormal<0,1,2>

#line 586
    texld_pp r3, v6.zwzw, s1  // ::detailSampl<0,1,2,3>
    dp4_pp r0.x, r3, c69
    lrp_pp r4.xyz, c87.x, r0.x, r3  // ::detailSampl<0,1,2>
    if b0
      mad_pp r3.xyz, r5, r6, r4  // ::col<0,1,2>
    else

#line 595
      mul_pp r3.xyz, r7, r4  // ::col<0,1,2>

#line 589
    endif

#line 781
    dp3_pp r0.x, r2, c3  // ::ndotl<0>
    mov_sat_pp r1.w, r0.x  // ::ndotl_satd<0>
    mul_pp r4.xyz, r3, r1.w  // calcStrauss::Qd<0,1,2>

#line 640
    texld_pp r9, r2, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.x, r2, r1
    mul_pp r1.yzw, r9.xxyz, r1.x  // ::amb<0,1,2>
    mul_pp r1.yzw, r1, c1.w  // ::amb<0,1,2>
    mov_pp r5.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.yzw, r1, c72.xxyz, r5.xxyz  // ::amb<0,1,2>

#line 788
    mul_pp r1.yzw, r3.xxyz, r1  // calcStrauss::Qa<0,1,2>

#line 797
    add_pp r5.xyz, c10, -v2
    nrm_pp r6.xyz, r5  // ::viewVec<0,1,2>

#line 801
    add r5.xyz, r2, r2
    mad_pp r7.xyz, r5, r0.x, -c3  // ::RVec<0,1,2>
    dp3_sat_pp r3.w, r6, r7  // ::vdotr<0>
    pow_pp r4.w, r3.w, r2.w  // ::rs<0>
    mov r7.xy, c0
    mad_pp r8.xyz, v0, c6, r7.y  // ::Cs<0,1,2>
    mad_pp r7.xyz, r8, c66.x, r7.x  // ::Cs<0,1,2>
    mul_pp r7.xyz, r7, c6.w  // ::Cs<0,1,2>
    mul_pp r8.xyz, r4.w, r7  // calcStrauss::Qs<0,1,2>

#line 818
    dp3_pp r3.w, -r6, r2
    add_pp r3.w, r3.w, r3.w
    mad_pp r9.xyz, r3.w, -r2, -r6  // ::reflectionVec<0,1,2>

#line 657
    texld_pp r9, r9, s8  // ::sampl<0,1,2,3>
    mad_pp r3.w, r9.w, c68.x, c68.y
    exp_pp r3.w, r3.w  // ::f<0>
    mul_pp r9.xyz, r9, r3.w
    mul_pp r9.xyz, r9, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 820
    mul_pp r0.yzw, r0, r9.xxyz  // ::envMapColor<0,1,2>
    mad_pp r0.x, r0.x, c4.w, c4.w
    mul_pp r0.xyz, r0.yzww, r0.x  // calcStrauss::Qe<0,1,2>

#line 652
    mad_sat_pp r9.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 834
    mul_pp r8.xyz, r8, r9.y  // calcStrauss::Qs<0,1,2>
    mul_pp r0.xyz, r0, r9.y  // calcStrauss::Qe<0,1,2>

#line 296
    add r9.yzw, -c10.xxyz, v2.xxyz  // ::delta<0,1,2>
    dp3 r0.w, c11, r9.yzww  // ::lightSpacePos<3>
    add r9.yzw, r0.w, -c28  // ::delta<0,1,2>
    mul r10.xyz, c21, v2.y
    mad r10.xyz, v2.x, c20, r10
    mad r10.xyz, v2.z, c22, r10
    mad r10.xyz, v2.w, c23, r10  // ::lightSpacePos<0,1,2>
    mov r11, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r11, r9.y, r11, c24  // ::scaleOffset<0,1,2,3>
    cmp r11, r9.z, c26, r11  // ::scaleOffset<0,1,2,3>
    cmp r11, r9.w, c27, r11  // ::scaleOffset<0,1,2,3>
    mad r11.xy, r10, r11, r11.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r11.zw, r10.z, c0.xyxz, c0.xyzx
    texldp r10, r11, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    add r0.w, -r0.w, c30.z
    cmp r0.w, r0.w, r10.x, c0.x  // ::shadowValue<0>
    max_sat_pp r3.w, r0.w, c30.x  // ::calcShadow<0>

#line 1021
    mul_pp r9.yzw, r3.w, c2.xxyz
    mad_pp r4.xyz, r4, r9.x, r8
    max_pp r0.w, c9.x, r3.w
    mul_pp r0.xyz, r0, r0.w
    mul_pp r0.xyz, r8.w, r0
    mad_pp r0.xyz, r9.yzww, r4, r0
    mad_pp r0.xyz, r1.yzww, v1.w, r0  // ::Ir<0,1,2>

#line 526
    mad_pp r1.yzw, r0.xxyz, c7.w, c7.xxyz
    mul_pp r0.w, r8.w, c8.z
    lrp_pp r4.xyz, r0.w, r1.yzww, r0  // ::outCol<0,1,2>
    mad_pp r0.x, r5.w, -r6.w, r8.w
    mad_pp oC0.w, c8.w, r0.x, r7.w  // ::main<3>

#line 1027
    mov r0.x, v3.w
    mov r0.y, v4.w
    mov r0.z, v5.w
    mul_pp r0.xyz, r3, r0
    mad_pp r0.xyz, r0, r1.x, r4  // ::Ir<0,1,2>

#line 850
    add_pp r1.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r1, r1
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r1.xyz, r1, r0.w  // ::lightVec<0,1,2>

#line 858
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c9.y  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r4.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 781
    dp3_pp r0.w, r2, r1  // ::ndotl<0>
    mov_sat_pp r1.w, r0.w  // ::ndotl_satd<0>

#line 801
    mad_pp r1.xyz, r5, r0.w, -r1  // ::RVec<0,1,2>
    dp3_sat_pp r0.w, r6, r1  // ::vdotr<0>
    pow_pp r1.x, r0.w, r2.w  // ::rs<0>

#line 810
    mul_pp r1.xyz, r7, r1.x  // calcStrauss::Qs<0,1,2>

#line 897
    mad_pp r1.xyz, r3, r1.w, r1  // ::Qd<0,1,2>

#line 850
    add_pp r8.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r8, r8
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r8.xyz, r8, r0.w  // ::lightVec<0,1,2>

#line 858
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c9.y  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r9.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 781
    dp3_pp r0.w, r2, r8  // ::ndotl<0>
    mov_sat_pp r1.w, r0.w  // ::ndotl_satd<0>

#line 801
    mad_pp r2.xyz, r5, r0.w, -r8  // ::RVec<0,1,2>
    dp3_sat_pp r0.w, r6, r2  // ::vdotr<0>
    pow_pp r3.w, r0.w, r2.w  // ::rs<0>

#line 810
    mul_pp r2.xyz, r7, r3.w  // calcStrauss::Qs<0,1,2>

#line 902
    mad_pp r2.xyz, r3, r1.w, r2  // ::Qd<0,1,2>
    mul_pp r2.xyz, r9, r2  // ::Qd<0,1,2>
    mad_pp r1.xyz, r1, r4, r2  // ::Ir<0,1,2>

#line 1030
    add_pp oC0.xyz, r0, r1  // ::main<0,1,2>

// approximately 162 instruction slots used (6 texture, 156 arithmetic)
