//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Lit_AN_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   sampler2D g__normalMap;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__normalMap             s2       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 2, -1, 0.5, 0.349999994
    def c4, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3  // IN<16,17,18,19>
    dcl_texcoord2 v4  // IN<20,21,22,23>
    dcl_texcoord3 v5  // IN<24,25,26,27>
    dcl_texcoord4 v6.xy  // IN<28,29>
    dcl_texcoord5 v7.xy  // IN<32,33>
    dcl vFace  // IN<36>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 990 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Lit_AN_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm.final"
    texld_pp r0, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r0, r0, c5  // ::diffuseSampl<0,1,2,3>

#line 668
    texld_pp r1, v7, s2  // ::sampl<0,1,3>

#line 525
    mad_pp r1.z, r0.w, -v0.w, r1.w

#line 992
    mul_pp r0, r0, v0  // ::diffuseSampl<0,1,2,3>

#line 525
    mad_pp oC0.w, c8.w, r1.z, r0.w  // ::main<3>

#line 296
    add r2.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r2  // ::lightSpacePos<3>
    add r2.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r3, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r3, r2.x, r3, c24  // ::scaleOffset<0,1,2,3>
    cmp r3, r2.y, c26, r3  // ::scaleOffset<0,1,2,3>
    cmp r2, r2.z, c27, r3  // ::scaleOffset<0,1,2,3>

#line 299
    mul r3.xyz, c21, v2.y
    mad r3.xyz, v2.x, c20, r3
    mad r3.xyz, v2.z, c22, r3
    mad r3.xyz, v2.w, c23, r3  // ::lightSpacePos<0,1,2>

#line 304
    mad r2.xy, r3, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r2.zw, r3.z, c4.xyxz, c4.xyzx
    texldp r2, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r2.x, c4.x  // ::shadowValue<0>
    max_sat_pp r1.z, r0.w, c30.x  // ::calcShadow<0>

#line 1021
    mul_pp r2.xyz, r1.z, c2
    max_pp r0.w, c0.w, r1.z

#line 351
    nrm_pp r3.xyz, v3  // ::g__bx<0,1,2>

#line 669
    mad_pp r1.xy, r1, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r2.w, r1, -r1, c4.x
    rsq_pp r2.w, r2.w
    rcp_pp r1.z, r2.w  // ::sampl<2>

#line 356
    cmp r2.w, vFace, c4.x, c4.y  // IN<36>
    cmp r2.w, -r2.w, c4.z, c4.x
    cmp r3.w, vFace, c4.w, c4.y
    add_pp r2.w, r2.w, r3.w  // ::g__face<0>

#line 671
    mul_pp r1.xyz, r1, -r2.w  // ::sampl<0,1,2>

#line 999
    dp3_pp r3.x, r3, r1  // ::worldNormal<0>

#line 352
    nrm_pp r4.xyz, v4  // ::g__by<0,1,2>

#line 999
    dp3_pp r3.y, r4, r1  // ::worldNormal<1>

#line 353
    nrm_pp r4.xyz, v5  // ::g__bz<0,1,2>

#line 999
    dp3_pp r3.z, r4, r1  // ::worldNormal<2>

#line 1002
    mul_pp r1.xyz, -r2.w, r3  // ::worldNormal<0,1,2>

#line 727
    add_pp r3.xyz, c10, -v2
    nrm_pp r4.xyz, r3  // ::viewVec<0,1,2>

#line 751
    dp3_pp r3.x, -r4, r1
    add_pp r3.x, r3.x, r3.x
    mad_pp r3.xyz, r3.x, -r1, -r4  // ::reflectionVec<0,1,2>

#line 655
    texld_pp r3, r3, s8  // ::sampl<0,1,2,3>
    mad_pp r3.w, r3.w, c68.x, c68.y
    exp_pp r3.w, r3.w  // ::f<0>
    mul_pp r3.xyz, r3, r3.w
    mul_pp r3.xyz, r3, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 1006
    mul_pp r4.xyz, c6, v0  // ::specSampl<0,1,2>

#line 753
    mul_pp r3.xyz, r3, r4  // ::envMapColor<0,1,2>

#line 717
    dp3_pp r3.w, r1, c3  // ::ndotl<0>

#line 754
    mad_pp r4.x, r3.w, c0.z, c0.z

#line 718
    mov_sat_pp r3.w, r3.w
    mul_pp r4.yzw, r0.xxyz, r3.w  // calcLambert::Qd<0,1,2>

#line 754
    mul_pp r3.xyz, r3, r4.x  // calcLambert::Qe<0,1,2>

#line 650
    mad_sat_pp r5.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 765
    mul_pp r3.xyz, r3, r5.y  // calcLambert::Qe<0,1,2>
    mul_pp r4.xyz, r4.yzww, r5.x  // calcLambert::Qd<0,1,2>

#line 1021
    mul_pp r3.xyz, r0.w, r3
    mul_pp r3.xyz, r1.w, r3

#line 524
    mul_pp r0.w, r1.w, c8.z

#line 1021
    mad_pp r2.xyz, r2, r4, r3

#line 350
    nrm_pp r3.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 1003
    mul_pp r3.xyz, -r2.w, r3  // ::g__vertexNormal<0,1,2>

#line 639
    dp3_sat_pp r1.w, r1, r3
    texld_pp r3, r1, s6  // ::amb<0,1,2>
    mul_pp r1.xyz, r1.w, r3  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c1.w  // ::amb<0,1,2>
    mov_pp r3.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.xyz, r1, c72, r3  // ::amb<0,1,2>

#line 743
    mul_pp r1.xyz, r0, r1  // calcLambert::Qa<0,1,2>

#line 1021
    mad_pp r1.xyz, r1, v1.w, r2  // ::Ir<0,1,2>

#line 524
    mad_pp r2.xyz, r1, c7.w, c7
    lrp_pp r3.xyz, r0.w, r2, r1  // ::outCol<0,1,2>

#line 1027
    mov r1.x, v3.w
    mov r1.y, v4.w
    mov r1.z, v5.w
    mul_pp r0.xyz, r0, r1
    mad_pp oC0.xyz, r0, r1.w, r3  // ::main<0,1,2>

// approximately 93 instruction slots used (5 texture, 88 arithmetic)
