//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Lit_AD_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   bool g__detailBools[2];
//   sampler2D g__detailMap;
//   float4 g__detailSelect;
//   float4 g__detailVariation;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__detailBools           b0       1
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__hdrTexParms           c68      1
//   g__detailSelect          c69      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__detailVariation       c87      1
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__detailMap             s1       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 0.5, 0.349999994, 0, 0
    def c4, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3  // IN<16,17,18,19>
    dcl_texcoord4 v4.xyz  // IN<20,21,22>
    dcl vFace  // IN<24>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 349 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Lit_AD_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim.final"
    cmp r0.x, vFace, c4.x, c4.y  // IN<24>

#line 346
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 349
    cmp r0.x, -r0.x, c4.z, c4.x
    cmp r0.y, vFace, c4.w, c4.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 984
    texld_pp r2, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r2, r2, c5  // ::diffuseSampl<0,1,2,3>
    mul_pp r3, r2, v0  // ::diffuseSampl<0,1,2,3>

#line 993
    mul_pp r0.xyz, r1.yxzw, -r0.x  // ::worldNormal<1,0,2>

#line 577
    texld_pp r1, v3.zwzw, s1  // ::detailSampl<0,1,2,3>
    dp4_pp r0.w, r1, c69
    lrp_pp r4.xyz, c87.x, r0.w, r1  // ::detailSampl<0,1,2>
    if b0
      mad_pp r1.xyz, r2, v0, r4  // ::col<0,1,2>
    else

#line 586
      mul_pp r1.xyz, r3, r4  // ::col<0,1,2>

#line 580
    endif

#line 1001
    mul_pp r2.xyz, c6, v0  // ::specSampl<0,1,2>

#line 710
    dp3_pp r0.w, r0.yxzw, c3  // ::ndotl<0>
    mov_sat_pp r1.w, r0.w
    mul_pp r3.xyz, r1, r1.w  // calcLambert::Qd<0,1,2>

#line 720
    add_pp r4.xyz, c10, -v2
    nrm_pp r5.xyz, r4  // ::viewVec<0,1,2>

#line 631
    texld_pp r4, r0.yxzw, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.w, r0, r0
    mul_pp r4.xyz, r4, r1.w  // ::amb<0,1,2>
    mul_pp r4.xyz, r4, c1.w  // ::amb<0,1,2>
    mov_pp r6.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r4.xyz, r4, c72, r6  // ::amb<0,1,2>

#line 736
    mul_pp r4.xyz, r1, r4  // calcLambert::Qa<0,1,2>

#line 744
    dp3_pp r4.w, -r5.yxzw, r0
    add_pp r4.w, r4.w, r4.w
    mad_pp r6.xyz, r4.w, -r0.yxzw, -r5  // ::reflectionVec<0,1,2>

#line 648
    texld_pp r6, r6, s8  // ::sampl<0,1,2,3>
    mad_pp r4.w, r6.w, c68.x, c68.y
    exp_pp r4.w, r4.w  // ::f<0>
    mul_pp r6.xyz, r6, r4.w
    mul_pp r6.xyz, r6, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 746
    mul_pp r2.xyz, r2, r6  // ::envMapColor<0,1,2>
    mad_pp r0.w, r0.w, c0.x, c0.x
    mul_pp r2.xyz, r2, r0.w  // calcLambert::Qe<0,1,2>

#line 643
    mad_sat_pp r6.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 757
    mul_pp r3.xyz, r3, r6.x  // calcLambert::Qd<0,1,2>
    mul_pp r2.xyz, r2, r6.y  // calcLambert::Qe<0,1,2>

#line 523
    dp3_pp r0.y, r5.yxzw, r0  // ::dot_viewNrm<0>
    mov_sat_pp r0.x, -r0.x
    add_pp r0.x, -r0.x, c4.x  // ::vertAtten<0>
    abs_sat_pp r0.y, r0.y
    add_pp r0.y, -r0.y, c4.x  // ::rim<0>
    pow_pp r4.w, r0.y, c70.w  // ::rim<0>
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r4.w, r0.x  // ::rim<0>
    mov_pp r5.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r0.yzw, -r5.xxyz, c71.xxyz
    mad_pp r0.xyz, r0.x, r0.yzww, c70  // ::ret<0,1,2>

#line 762
    mul_pp r0.xyz, r1, r0  // calcLambert::Qr<0,1,2>

#line 296
    add r5.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r5  // ::lightSpacePos<3>
    add r5.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>
    mul r6.xyz, c21, v2.y
    mad r6.xyz, v2.x, c20, r6
    mad r6.xyz, v2.z, c22, r6
    mad r6.xyz, v2.w, c23, r6  // ::lightSpacePos<0,1,2>
    mov r7, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r7, r5.x, r7, c24  // ::scaleOffset<0,1,2,3>
    cmp r7, r5.y, c26, r7  // ::scaleOffset<0,1,2,3>
    cmp r5, r5.z, c27, r7  // ::scaleOffset<0,1,2,3>
    mad r5.xy, r6, r5, r5.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r5.zw, r6.z, c4.xyxz, c4.xyzx
    texldp r5, r5, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    add r0.w, -r0.w, c30.z
    cmp r0.w, r0.w, r5.x, c4.x  // ::shadowValue<0>
    max_sat_pp r4.w, r0.w, c30.x  // ::calcShadow<0>

#line 1016
    mul_pp r5.xyz, r4.w, c2
    max_pp r0.w, c0.y, r4.w
    mul_pp r2.xyz, r2, r0.w
    mad_pp r2.xyz, r5, r3, r2
    mad_pp r2.xyz, r4, v1.w, r2
    mad_pp r0.xyz, c2, r0, r2  // ::Ir<0,1,2>

#line 517
    mad_pp r2.xyz, r0, c7.w, c7
    lrp_pp r3.xyz, c8.z, r2, r0  // ::outCol<0,1,2>
    mad_pp r0.x, r2.w, -v0.w, c4.x
    mad_pp oC0.w, c8.w, r0.x, r3.w  // ::main<3>

#line 1022
    mul_pp r0.xyz, r1, v4
    mad_pp oC0.xyz, r0, r1.w, r3  // ::main<0,1,2>

// approximately 93 instruction slots used (5 texture, 88 arithmetic)
