//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_AN_Dn_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_3DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   sampler2D g__detailNormalMap;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   sampler2D g__normalMap;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__straussParms;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     9
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__normalMap             s2       1
//   g__detailNormalMap       s4       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 4, 2, -1, 1.04999995
    def c9, 0.00999999978, 0, 0, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3  // IN<16,17,18,19>
    dcl_texcoord2 v4  // IN<20,21,22,23>
    dcl_texcoord3 v5  // IN<24,25,26,27>
    dcl_texcoord4 v6.xy  // IN<28,29>
    dcl_texcoord5 v7.xy  // IN<32,33>
    dcl_texcoord6 v8.xy  // IN<36,37>
    dcl vFace  // IN<40>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6

#line 984 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_AN_Dn_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_3DL.final"
    texld_pp r0, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r1, c5, v0

#line 671
    texld_pp r2, v7, s2  // ::sampl<0,1,3>

#line 528
    mad_pp r2.z, r0.w, -r1.w, r2.w

#line 985
    mul_pp r0, r0, r1  // ::diffuseSampl<0,1,2,3>

#line 528
    mad_pp oC0.w, c8.w, r2.z, r0.w  // ::main<3>

#line 841
    add_pp r1.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r1, r1
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r1.xyz, r1, r0.w  // ::lightVec<0,1,2>

#line 849
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c9.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 841
    add_pp r4.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 849
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c9.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 671
    texld_pp r6, v8, s4  // ::sampl<0,1>
    mad_pp r6.xy, r6, c4.y, c4.z  // ::sampl<0,1>
    dp2add_pp r0.w, r6, -r6, c0.x
    rsq_pp r0.w, r0.w
    rcp_pp r6.z, r0.w  // ::sampl<2>

#line 359
    cmp r0.w, vFace, c0.x, c0.y  // IN<40>
    cmp r0.w, -r0.w, c0.z, c0.x
    cmp r1.w, vFace, c0.w, c0.y
    add_pp r0.w, r0.w, r1.w  // ::g__face<0>

#line 674
    mul_pp r6.xyz, r6, -r0.w  // ::sampl<0,1,2>

#line 666
    mov_sat_pp r1.w, r6.z
    add_pp r1.w, -r1.w, c0.x  // ::w1<0>
    mul_pp r6.xyz, r6, r1.w

#line 672
    mad_pp r2.xy, r2, c4.y, c4.z  // ::sampl<0,1>

#line 527
    mul_pp r1.w, r2.w, c8.z

#line 673
    dp2add_pp r2.w, r2, -r2, c0.x
    rsq_pp r2.w, r2.w
    rcp_pp r2.z, r2.w  // ::sampl<2>
    mul_pp r2.xyz, -r0.w, r2  // ::sampl<0,1,2>

#line 665
    mov_sat_pp r2.w, r2.z
    add_pp r2.w, -r2.w, c4.w  // ::w0<0>
    mad_pp r2.xyz, r2, r2.w, r6
    nrm_pp r6.xyz, r2  // ::combineNormals<0,1,2>

#line 354
    nrm_pp r2.xyz, v3  // ::g__bx<0,1,2>

#line 999
    dp3_pp r2.x, r2, r6  // ::worldNormal<0>

#line 355
    nrm_pp r7.xyz, v4  // ::g__by<0,1,2>

#line 999
    dp3_pp r2.y, r7, r6  // ::worldNormal<1>

#line 356
    nrm_pp r7.xyz, v5  // ::g__bz<0,1,2>

#line 999
    dp3_pp r2.z, r7, r6  // ::worldNormal<2>

#line 1002
    mul_pp r2.xyz, -r0.w, r2  // ::worldNormal<0,1,2>

#line 780
    dp3_pp r2.w, r2, r4  // ::ndotl<0>
    mov_sat_pp r3.w, r2.w  // ::ndotl_satd<0>

#line 800
    add r6.xyz, r2, r2
    mad_pp r4.xyz, r6, r2.w, -r4  // ::RVec<0,1,2>

#line 796
    add_pp r7.xyz, c10, -v2
    nrm_pp r8.xyz, r7  // ::viewVec<0,1,2>

#line 801
    dp3_sat_pp r2.w, r8, r4  // ::vdotr<0>

#line 992
    mul_pp r4.x, c66.w, c66.y  // ::specSampl<3>
    max_pp r5.w, r4.x, c4.x  // ::specSampl<3>

#line 803
    pow_pp r4.x, r2.w, r5.w  // ::rs<0>
    mov r7.xy, c0
    mad_pp r4.yzw, v0.xxyz, c6.xxyz, r7.y  // ::Cs<0,1,2>
    mad_pp r4.yzw, r4, c66.x, r7.x  // ::Cs<0,1,2>
    mul_pp r4.yzw, r4, c6.w  // ::Cs<0,1,2>
    mul_pp r7.xyz, r4.x, r4.yzww  // calcStrauss::Qs<0,1,2>

#line 897
    mad_pp r7.xyz, r0, r3.w, r7  // ::Qd<0,1,2>
    mul_pp r5.xyz, r5, r7  // ::Qd<0,1,2>

#line 780
    dp3_pp r2.w, r2, r1  // ::ndotl<0>

#line 800
    mad_pp r1.xyz, r6, r2.w, -r1  // ::RVec<0,1,2>

#line 781
    mov_sat_pp r2.w, r2.w  // ::ndotl_satd<0>

#line 801
    dp3_sat_pp r1.x, r8, r1  // ::vdotr<0>
    pow_pp r3.w, r1.x, r5.w  // ::rs<0>

#line 809
    mul_pp r1.xyz, r4.yzww, r3.w  // calcStrauss::Qs<0,1,2>

#line 892
    mad_pp r1.xyz, r0, r2.w, r1  // ::Qd<0,1,2>

#line 899
    mad_pp r1.xyz, r1, r3, r5  // ::Ir<0,1,2>

#line 841
    add_pp r3.xyz, c107, -v2  // ::lightVec<0,1,2>
    dp3_pp r2.w, r3, r3
    rsq_pp r2.w, r2.w
    rcp_pp r3.w, r2.w  // ::lightVecLen<0>
    mul_pp r3.xyz, r3, r2.w  // ::lightVec<0,1,2>

#line 849
    add_pp r2.w, r3.w, -c108.x
    max_pp r3.w, r2.w, c9.x  // ::lightVecLenPrime<0>
    mul_pp r2.w, r3.w, r3.w
    mul_pp r2.w, r2.w, c108.w
    mad_pp r2.w, r3.w, c108.z, r2.w
    rcp_sat_pp r2.w, r2.w  // ::attenuation<0>
    mul_pp r5.xyz, r2.w, c106  // getDynamicPointLight::color<0,1,2>

#line 780
    dp3_pp r2.w, r2, r3  // ::ndotl<0>

#line 800
    mad_pp r3.xyz, r6, r2.w, -r3  // ::RVec<0,1,2>

#line 781
    mov_sat_pp r2.w, r2.w  // ::ndotl_satd<0>

#line 801
    dp3_sat_pp r3.x, r8, r3  // ::vdotr<0>
    pow_pp r4.x, r3.x, r5.w  // ::rs<0>

#line 809
    mul_pp r3.xyz, r4.yzww, r4.x  // calcStrauss::Qs<0,1,2>

#line 902
    mad_pp r3.xyz, r0, r2.w, r3  // ::Qd<0,1,2>
    mad_pp r1.xyz, r3, r5, r1  // ::Ir<0,1,2>

#line 780
    dp3_pp r2.w, r2, c3  // ::ndotl<0>

#line 800
    mad_pp r3.xyz, r6, r2.w, -c3  // ::RVec<0,1,2>

#line 781
    mov_sat_pp r2.w, r2.w  // ::ndotl_satd<0>
    mul_pp r5.xyz, r0, r2.w  // calcStrauss::Qd<0,1,2>

#line 801
    dp3_sat_pp r2.w, r8, r3  // ::vdotr<0>
    pow_pp r3.x, r2.w, r5.w  // ::rs<0>

#line 809
    mul_pp r3.xyz, r4.yzww, r3.x  // calcStrauss::Qs<0,1,2>

#line 653
    mad_sat_pp r4.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 826
    mul_pp r3.xyz, r3, r4.y  // calcStrauss::Qs<0,1,2>

#line 1017
    mad_pp r3.xyz, r5, r4.x, r3

#line 353
    nrm_pp r4.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 1003
    mul_pp r4.xyz, -r0.w, r4  // ::g__vertexNormal<0,1,2>

#line 642
    dp3_sat_pp r0.w, r2, r4
    texld_pp r2, r2, s6  // ::amb<0,1,2>
    mul_pp r2.xyz, r0.w, r2  // ::amb<0,1,2>
    mul_pp r2.xyz, r2, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r2.xyz, r2, c72, r4  // ::amb<0,1,2>

#line 787
    mul_pp r2.xyz, r0, r2  // calcStrauss::Qa<0,1,2>

#line 824
    mul_pp r2.xyz, r2, v1.w  // calcStrauss::Qa<0,1,2>

#line 296
    add r4.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r2.w, c11, r4  // ::lightSpacePos<3>
    add r4.xyz, r2.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r2.w, -r2.w, c30.z

#line 301
    mov r5, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r5, r4.x, r5, c24  // ::scaleOffset<0,1,2,3>
    cmp r5, r4.y, c26, r5  // ::scaleOffset<0,1,2,3>
    cmp r4, r4.z, c27, r5  // ::scaleOffset<0,1,2,3>

#line 299
    mul r5.xyz, c21, v2.y
    mad r5.xyz, v2.x, c20, r5
    mad r5.xyz, v2.z, c22, r5
    mad r5.xyz, v2.w, c23, r5  // ::lightSpacePos<0,1,2>

#line 304
    mad r4.xy, r5, r4, r4.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r4.zw, r5.z, c0.xyxz, c0.xyzx
    texldp r4, r4, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r2.w, r2.w, r4.x, c0.x  // ::shadowValue<0>
    max_sat_pp r3.w, r2.w, c30.x  // ::calcShadow<0>

#line 1017
    mul_pp r4.xyz, r3.w, c2
    mad_pp r2.xyz, r4, r3, r2  // ::Ir<0,1,2>

#line 527
    mad_pp r3.xyz, r2, c7.w, c7
    lrp_pp r4.xyz, r1.w, r3, r2  // ::outCol<0,1,2>

#line 1023
    mov r2.x, v3.w
    mov r2.y, v4.w
    mov r2.z, v5.w
    mul_pp r0.xyz, r0, r2
    mad_pp r0.xyz, r0, r0.w, r4  // ::Ir<0,1,2>

#line 1026
    add_pp oC0.xyz, r1, r0  // ::main<0,1,2>

// approximately 174 instruction slots used (5 texture, 169 arithmetic)
