//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_SpeedTree_Frond_Lit_ANS_Shdw_WPos_Vd_VNorm_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   sampler2D g__normalMap;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   sampler2D g__specularMap;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__sunDir              c3       1
//   g__diffColor           c5       1
//   g__specColor           c6       1
//   g__emissiveColor       c7       1
//   g__cameraPos           c10      1
//   g__cameraFront         c11      1
//   g__shadowMatrices      c20      4
//   g__shadowScaleOffset   c24      4
//   g__shadowDistances     c28      1
//   g__shadowMisc          c30      1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__normalMap           s2       1
//   g__specularMap         s3       1
//   g__shadowMap           s5       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 2, -1, 0, 0
    dcl_color v0.xyz  // IN<4,5,6>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord2 v4  // IN<19,20,21,22>
    dcl_texcoord3 v5  // IN<23,24,25,26>
    dcl_texcoord4 v6.xy  // IN<27,28>
    dcl_texcoord5 v7  // IN<31,32,33,34>
    dcl vFace  // IN<35>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s3
    dcl_2d s5
    dcl_cube s6

#line 296 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_SpeedTree_Frond_Lit_ANS_Shdw_WPos_Vd_VNorm_VtxAtm.final"
    add r0.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.x, c11, r0  // ::lightSpacePos<3>
    add r0.yzw, r0.x, -c28  // ::delta<0,1,2>

#line 311
    add r0.x, -r0.x, c30.z

#line 301
    mov r1, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r1, r0.y, r1, c24  // ::scaleOffset<0,1,2,3>
    cmp r1, r0.z, c26, r1  // ::scaleOffset<0,1,2,3>
    cmp r1, r0.w, c27, r1  // ::scaleOffset<0,1,2,3>

#line 299
    mul r0.yzw, c21.xxyz, v2.y
    mad r0.yzw, v2.x, c20.xxyz, r0
    mad r0.yzw, v2.z, c22.xxyz, r0
    mad r0.yzw, v2.w, c23.xxyz, r0  // ::lightSpacePos<0,1,2>

#line 304
    mad r1.xy, r0.yzzw, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r1.zw, r0.w, c0.xyxz, c0.xyzx
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.x, r0.x, r1.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.x, r0.x, c30.x  // ::calcShadow<0>

#line 985
    mul_pp r0.xyz, r1.x, c2

#line 964
    texld_pp r1, v7.zwzw, s3  // ::specSampl<0,1,2>
    mul_pp r1.xyz, r1, v0  // ::specSampl<0,1,2>

#line 720
    add_pp r2.xyz, c10, -v2
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w

#line 724
    mad_pp r2.xyz, r2, r0.w, c3
    nrm_pp r3.xyz, r2  // ::HVec<0,1,2>

#line 355
    cmp r0.w, vFace, c0.x, c0.y  // IN<35>
    cmp r0.w, -r0.w, c0.z, c0.x
    cmp r1.w, vFace, c0.w, c0.y
    add_pp r0.w, r0.w, r1.w  // ::g__face<0>

#line 660
    texld_pp r2, v7, s2  // ::sampl<0,1>
    mad_pp r2.xy, r2, c4.x, c4.y  // ::sampl<0,1>
    dp2add_pp r1.w, r2, -r2, c0.x
    rsq_pp r1.w, r1.w
    rcp_pp r2.z, r1.w  // ::sampl<2>
    mul_pp r2.xyz, -r0.w, r2  // ::sampl<0,1,2>

#line 350
    nrm_pp r4.xyz, v3  // ::g__bx<0,1,2>

#line 959
    dp3_pp r4.x, r4, r2  // ::worldNormal<0>

#line 351
    nrm_pp r5.xyz, v4  // ::g__by<0,1,2>

#line 959
    dp3_pp r4.y, r5, r2  // ::worldNormal<1>

#line 352
    nrm_pp r5.xyz, v5  // ::g__bz<0,1,2>

#line 959
    dp3_pp r4.z, r5, r2  // ::worldNormal<2>

#line 725
    dp3_sat_pp r0.w, r4, r3  // ::ndoth<0>
    pow_pp r1.w, r0.w, c6.w  // ::rs<0>
    mul_pp r1.xyz, r1, r1.w  // calcLambert::Qs<0,1,2>

#line 709
    dp3_sat_pp r0.w, r4, c3

#line 950
    texld_pp r2, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r2, r2, c5  // ::diffuseSampl<0,1,2,3>
    mul_pp r2.xyz, r2, v0  // ::diffuseSampl<0,1,2>

#line 986
    mov_pp oC0.w, r2.w  // ::main<3>

#line 710
    mul_pp r3.xyz, r0.w, r2  // calcLambert::Qd<0,1,2>

#line 985
    mad_pp r1.xyz, r3, c7.w, r1

#line 349
    nrm_pp r3.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 633
    dp3_sat_pp r0.w, r4, r3
    texld_pp r3, r4, s6  // ::amb<0,1,2>
    mul_pp r3.xyz, r0.w, r3  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r4  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c7
    mul_pp r3.xyz, r2, r3

#line 736
    add_pp r3.xyz, r3, r3  // calcLambert::Qa<0,1,2>

#line 985
    mad_pp r0.xyz, r0, r1, r3  // ::Ir<0,1,2>
    mov r1.x, v3.w
    mov r1.y, v4.w
    mov r1.z, v5.w
    mad_pp oC0.xyz, r1, r2, r0  // ::main<0,1,2>

// approximately 79 instruction slots used (5 texture, 74 arithmetic)
