//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_SpeedTree_Frond_Lit_AN_Shdw_WPos_Vd_VNorm_VtxAtm_4DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   sampler2D g__normalMap;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100    12
//   g__albedoMap             s0       1
//   g__normalMap             s2       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 2, -1, 0.00999999978, 0
    def c4, 1, -1, 0, -0
    dcl_color v0.xyz  // IN<4,5,6>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord2 v4  // IN<19,20,21,22>
    dcl_texcoord3 v5  // IN<23,24,25,26>
    dcl_texcoord4 v6.xy  // IN<27,28>
    dcl_texcoord5 v7.xy  // IN<31,32>
    dcl vFace  // IN<35>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s5
    dcl_cube s6

#line 808 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_SpeedTree_Frond_Lit_AN_Shdw_WPos_Vd_VNorm_VtxAtm_4DL.final"
    add_pp r0.xyz, c110, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 816
    add_pp r0.w, r1.x, -c111.x
    max_pp r1.x, r0.w, c0.z  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c111.w
    mad_pp r0.w, r1.x, c111.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c109  // getDynamicPointLight::color<0,1,2>

#line 808
    add_pp r2.xyz, c107, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 816
    add_pp r0.w, r1.w, -c108.x
    max_pp r1.w, r0.w, c0.z  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r1.w, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 808
    add_pp r4.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 816
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c0.z  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 808
    add_pp r6.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r6.xyz, r6, r0.w  // ::lightVec<0,1,2>

#line 816
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c0.z  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r7.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 719
    add_pp r8.xyz, c10, -v2
    dp3_pp r0.w, r8, r8
    rsq_pp r0.w, r0.w

#line 723
    mad_pp r9.xyz, r8, r0.w, r6
    nrm_pp r10.xyz, r9  // ::HVec<0,1,2>

#line 354
    cmp r1.w, vFace, c4.x, c4.y  // IN<35>
    cmp r1.w, -r1.w, c4.z, c4.x
    cmp r2.w, vFace, c4.w, c4.y
    add_pp r1.w, r1.w, r2.w  // ::g__face<0>

#line 659
    texld_pp r9, v7, s2  // ::sampl<0,1>
    mad_pp r9.xy, r9, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r2.w, r9, -r9, c4.x
    rsq_pp r2.w, r2.w
    rcp_pp r9.z, r2.w  // ::sampl<2>
    mul_pp r9.xyz, -r1.w, r9  // ::sampl<0,1,2>

#line 349
    nrm_pp r11.xyz, v3  // ::g__bx<0,1,2>

#line 1024
    dp3_pp r11.x, r11, r9  // ::worldNormal<0>

#line 350
    nrm_pp r12.xyz, v4  // ::g__by<0,1,2>

#line 1024
    dp3_pp r11.y, r12, r9  // ::worldNormal<1>

#line 351
    nrm_pp r12.xyz, v5  // ::g__bz<0,1,2>

#line 1024
    dp3_pp r11.z, r12, r9  // ::worldNormal<2>

#line 724
    dp3_sat_pp r1.w, r11, r10  // ::ndoth<0>
    pow_pp r2.w, r1.w, c6.w  // ::rs<0>

#line 1029
    mul_pp r9.xyz, c6, v0  // ::specSampl<0,1,2>

#line 726
    mul_pp r10.xyz, r2.w, r9  // calcLambert::Qs<0,1,2>

#line 708
    dp3_sat_pp r1.w, r11, r6

#line 1015
    texld_pp r6, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r6, r6, c5  // ::diffuseSampl<0,1,2,3>
    mul_pp r6.xyz, r6, v0  // ::diffuseSampl<0,1,2>

#line 1052
    mov_pp oC0.w, r6.w  // ::main<3>

#line 709
    mul_pp r12.xyz, r1.w, r6  // calcLambert::Qd<0,1,2>

#line 840
    mad_pp r10.xyz, r12, c7.w, r10  // ::Qd<0,1,2>
    mul_pp r7.xyz, r7, r10  // ::Qd<0,1,2>

#line 723
    mad_pp r10.xyz, r8, r0.w, r4

#line 708
    dp3_sat_pp r1.w, r11, r4
    mul_pp r4.xyz, r6, r1.w  // calcLambert::Qd<0,1,2>

#line 723
    nrm_pp r12.xyz, r10  // ::HVec<0,1,2>
    dp3_sat_pp r1.w, r11, r12  // ::ndoth<0>
    pow_pp r2.w, r1.w, c6.w  // ::rs<0>
    mul_pp r10.xyz, r9, r2.w  // calcLambert::Qs<0,1,2>

#line 835
    mad_pp r4.xyz, r4, c7.w, r10  // ::Qd<0,1,2>

#line 842
    mad_pp r4.xyz, r4, r5, r7  // ::Ir<0,1,2>

#line 723
    mad_pp r5.xyz, r8, r0.w, r2

#line 708
    dp3_sat_pp r1.w, r11, r2
    mul_pp r2.xyz, r6, r1.w  // calcLambert::Qd<0,1,2>

#line 723
    nrm_pp r7.xyz, r5  // ::HVec<0,1,2>
    dp3_sat_pp r1.w, r11, r7  // ::ndoth<0>
    pow_pp r2.w, r1.w, c6.w  // ::rs<0>
    mul_pp r5.xyz, r9, r2.w  // calcLambert::Qs<0,1,2>

#line 845
    mad_pp r2.xyz, r2, c7.w, r5  // ::Qd<0,1,2>
    mad_pp r2.xyz, r2, r3, r4  // ::Ir<0,1,2>

#line 723
    mad_pp r3.xyz, r8, r0.w, r0

#line 708
    dp3_sat_pp r0.x, r11, r0
    mul_pp r0.xyz, r6, r0.x  // calcLambert::Qd<0,1,2>

#line 723
    mad_pp r4.xyz, r8, r0.w, c3
    nrm_pp r5.xyz, r4  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r11, r5  // ::ndoth<0>
    pow_pp r1.w, r0.w, c6.w  // ::rs<0>
    mul_pp r4.xyz, r9, r1.w  // calcLambert::Qs<0,1,2>

#line 723
    nrm_pp r5.xyz, r3  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r11, r5  // ::ndoth<0>
    pow_pp r1.w, r0.w, c6.w  // ::rs<0>
    mul_pp r3.xyz, r9, r1.w  // calcLambert::Qs<0,1,2>

#line 850
    mad_pp r0.xyz, r0, c7.w, r3  // ::Qd<0,1,2>
    mad_pp r0.xyz, r0, r1, r2  // ::Ir<0,1,2>

#line 348
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 632
    dp3_sat_pp r0.w, r11, r1
    texld_pp r1, r11, s6  // ::amb<0,1,2>

#line 708
    dp3_sat_pp r1.w, r11, c3
    mul_pp r2.xyz, r6, r1.w  // calcLambert::Qd<0,1,2>

#line 1048
    mad_pp r2.xyz, r2, c7.w, r4

#line 632
    mul_pp r1.xyz, r0.w, r1  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c1.w  // ::amb<0,1,2>
    mov_pp r3.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.xyz, r1, c72, r3  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c7
    mul_pp r1.xyz, r6, r1

#line 735
    add_pp r1.xyz, r1, r1  // calcLambert::Qa<0,1,2>

#line 296
    add r3.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r3  // ::lightSpacePos<3>
    add r3.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r4, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r4, r3.x, r4, c24  // ::scaleOffset<0,1,2,3>
    cmp r4, r3.y, c26, r4  // ::scaleOffset<0,1,2,3>
    cmp r3, r3.z, c27, r4  // ::scaleOffset<0,1,2,3>

#line 299
    mul r4.xyz, c21, v2.y
    mad r4.xyz, v2.x, c20, r4
    mad r4.xyz, v2.z, c22, r4
    mad r4.xyz, v2.w, c23, r4  // ::lightSpacePos<0,1,2>

#line 304
    mad r3.xy, r4, r3, r3.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r3.zw, r4.z, c4.xyxz, c4.xyzx
    texldp r3, r3, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r3.x, c4.x  // ::shadowValue<0>
    max_sat_pp r1.w, r0.w, c30.x  // ::calcShadow<0>

#line 1048
    mul_pp r3.xyz, r1.w, c2
    mad_pp r1.xyz, r3, r2, r1  // ::Ir<0,1,2>
    mov r2.x, v3.w
    mov r2.y, v4.w
    mov r2.z, v5.w
    mad_pp r1.xyz, r2, r6, r1  // ::Ir<0,1,2>

#line 1052
    add_pp oC0.xyz, r0, r1  // ::main<0,1,2>

// approximately 179 instruction slots used (4 texture, 175 arithmetic)
