//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_T0_DBG_OverDraw.pso
//
//
// Parameters:
//
//   sampler2D g__colorCurve;
//   sampler2D g__hdr;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   g__hdr        s0       1
//   g__colorCurve s5       1
//

    ps_3_0
    def c0, 0.25, 0, 1, 0
    dcl_texcoord v0.xy  // IN<8,9>
    dcl_2d s0
    dcl_2d s5

#line 1144 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_T0_DBG_OverDraw.final"
    texld_pp r0, v0, s0
    mul_pp r0.x, r0.x, c0.x  // ::odSampl<0>
    mov_pp r0.y, c0.y
    texld_pp r0, r0, s5  // ::clr<0,1,2>
    mad_pp oC0, r0.xyzx, c0.zzzy, c0.yyyz  // ::main<0,1,2,3>

// approximately 5 instruction slots used (2 texture, 3 arithmetic)
