//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Lit_A_Vd_WPos_Shdw_VNorm_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__sunDir              c3       1
//   g__diffColor           c5       1
//   g__emissiveColor       c7       1
//   g__emissiveParms       c8       1
//   g__cameraPos           c10      1
//   g__cameraFront         c11      1
//   g__shadowMatrices      c20      4
//   g__shadowScaleOffset   c24      4
//   g__shadowDistances     c28      1
//   g__shadowMisc          c30      1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__shadowMap           s5       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3.xy  // IN<15,16>
    dcl_texcoord4 v4.xyz  // IN<19,20,21>
    dcl vFace  // IN<23>
    dcl_2d s0
    dcl_2d s5
    dcl_cube s6

#line 942 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Lit_A_Vd_WPos_Shdw_VNorm_VtxAtm.final"
    texld_pp r0, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r0, r0, c5  // ::diffuseSampl<0,1,2,3>

#line 515
    mad_pp r1.x, r0.w, -v0.w, c0.x

#line 944
    mul_pp r0, r0, v0  // ::diffuseSampl<0,1,2,3>

#line 515
    mad_pp oC0.w, c8.w, r1.x, r0.w  // ::main<3>

#line 296
    add r1.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r1  // ::lightSpacePos<3>
    add r1.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r2, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r2, r1.x, r2, c24  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.y, c26, r2  // ::scaleOffset<0,1,2,3>
    cmp r1, r1.z, c27, r2  // ::scaleOffset<0,1,2,3>

#line 299
    mul r2.xyz, c21, v2.y
    mad r2.xyz, v2.x, c20, r2
    mad r2.xyz, v2.z, c22, r2
    mad r2.xyz, v2.w, c23, r2  // ::lightSpacePos<0,1,2>

#line 304
    mad r1.xy, r2, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r1.zw, r2.z, c0.xyxz, c0.xyzx
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r1.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.x, r0.w, c30.x  // ::calcShadow<0>

#line 970
    mul_pp r1.xyz, r1.x, c2

#line 346
    cmp r0.w, vFace, c0.x, c0.y  // IN<23>
    cmp r0.w, -r0.w, c0.z, c0.x
    cmp r1.w, vFace, c0.w, c0.y
    add_pp r0.w, r0.w, r1.w  // ::g__face<0>

#line 343
    nrm_pp r2.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 951
    mul_pp r2.xyz, -r0.w, r2  // ::worldNormal<0,1,2>

#line 628
    texld_pp r3, r2, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r2, r2

#line 704
    dp3_sat_pp r1.w, r2, c3
    mul_pp r2.xyz, r0, r1.w  // calcLambert::Qd<0,1,2>

#line 629
    mul_pp r3.xyz, r3, r0.w  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r4  // ::amb<0,1,2>

#line 730
    mul_pp r3.xyz, r0, r3  // calcLambert::Qa<0,1,2>

#line 976
    mul_pp r0.xyz, r0, v4

#line 970
    mad_pp r1.xyz, r1, r2, r3  // ::Ir<0,1,2>

#line 514
    mad_pp r2.xyz, r1, c7.w, c7
    lrp_pp r3.xyz, c8.z, r2, r1  // ::outCol<0,1,2>

#line 976
    mad_pp oC0.xyz, r0, r0.w, r3  // ::main<0,1,2>

// approximately 45 instruction slots used (3 texture, 42 arithmetic)
