//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_ADNS_Dn_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   bool g__detailBools[2];
//   sampler2D g__detailMap;
//   sampler2D g__detailNormalMap;
//   float4 g__detailSelect;
//   float4 g__detailVariation;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   sampler2D g__normalMap;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   sampler2D g__specularMap;
//   float4 g__straussParms;
//   float4 g__straussParms1;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__detailBools           b0       1
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__straussParms1         c67      1
//   g__detailSelect          c69      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__detailVariation       c87      1
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__detailMap             s1       1
//   g__normalMap             s2       1
//   g__specularMap           s3       1
//   g__detailNormalMap       s4       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 4, 2, -1, 1.04999995
    def c4, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3  // IN<16,17,18,19>
    dcl_texcoord2 v4  // IN<20,21,22,23>
    dcl_texcoord3 v5  // IN<24,25,26,27>
    dcl_texcoord4 v6  // IN<28,29,30,31>
    dcl_texcoord5 v7  // IN<32,33,34,35>
    dcl_texcoord6 v8.xy  // IN<36,37>
    dcl vFace  // IN<40>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6

#line 363 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_ADNS_Dn_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim.final"
    cmp r0.x, vFace, c4.x, c4.y  // IN<40>

#line 357
    nrm_pp r1.xyz, v1  // ::g__vertexNormal<0,1,2>
    nrm_pp r2.xyz, v3  // ::g__bx<0,1,2>
    nrm_pp r3.xyz, v4  // ::g__by<0,1,2>
    nrm_pp r4.xyz, v5  // ::g__bz<0,1,2>

#line 363
    cmp r0.x, -r0.x, c4.z, c4.x
    cmp r0.y, vFace, c4.w, c4.y
    add_pp r0.x, r0.x, r0.y  // ::g__face<0>

#line 937
    texld_pp r5, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r6, c5, v0
    mul_pp r7, r5, r6  // ::diffuseSampl<0,1,2,3>

#line 943
    texld_pp r8, v7.zwzw, s3  // ::specSampl<0,1,2,3>
    mul_pp r0.yzw, c6.xxyz, v0.xxyz
    add_pp r1.w, r8.w, -c66.y
    mov r9.xy, c66  // ::g__straussParms<0,1>
    mad_pp r1.w, c67.x, r1.w, r9.y  // ::specSampl<3>
    mul_pp r1.w, r1.w, c66.w  // ::specSampl<3>
    max_pp r2.w, r1.w, c0.x  // ::specSampl<3>

#line 675
    texld_pp r10, v7, s2  // ::sampl<0,1,3>
    mad_pp r10.xy, r10, c0.y, c0.z  // ::sampl<0,1>
    dp2add_pp r1.w, r10, -r10, c4.x
    rsq_pp r1.w, r1.w
    rcp_pp r10.z, r1.w  // ::sampl<2>
    mul_pp r9.yzw, -r0.x, r10.xxyz  // ::sampl<0,1,2>

#line 675
    texld_pp r11, v8, s4  // ::sampl<0,1,3>
    mad_pp r10.xy, r11, c0.y, c0.z  // ::sampl<0,1>
    dp2add_pp r1.w, r10, -r10, c4.x
    rsq_pp r1.w, r1.w
    rcp_pp r10.z, r1.w  // ::sampl<2>
    mul_pp r10.xyz, -r0.x, r10  // ::sampl<0,1,2>

#line 669
    mov_sat_pp r1.w, r9.w
    add_pp r1.w, -r1.w, c0.w  // ::w0<0>
    mov_sat_pp r3.w, r10.z
    add_pp r3.w, -r3.w, c4.x  // ::w1<0>
    mul_pp r10.xyz, r10, r3.w
    mad_pp r9.yzw, r9, r1.w, r10.xxyz
    nrm_pp r10.xyz, r9.yzww  // ::combineNormals<0,1,2>

#line 954
    dp3_pp r2.x, r2, r10  // ::worldNormal<0>
    dp3_pp r2.y, r3, r10  // ::worldNormal<1>
    dp3_pp r2.z, r4, r10  // ::worldNormal<2>

#line 957
    mul_pp r2.xyz, -r0.x, r2.yxzw  // ::worldNormal<1,0,2>
    mul_pp r1.xyz, r1, -r0.x  // ::g__vertexNormal<0,1,2>

#line 591
    texld_pp r3, v6.zwzw, s1  // ::detailSampl<0,1,2,3>
    dp4_pp r0.x, r3, c69
    lrp_pp r4.xyz, c87.x, r0.x, r3  // ::detailSampl<0,1,2>
    if b0
      mad_pp r3.xyz, r5, r6, r4  // ::col<0,1,2>
    else

#line 600
      mul_pp r3.xyz, r7, r4  // ::col<0,1,2>

#line 594
    endif

#line 784
    dp3_pp r0.x, r2.yxzw, c3  // ::ndotl<0>
    mov_sat_pp r1.w, r0.x  // ::ndotl_satd<0>
    mul_pp r4.xyz, r3, r1.w  // calcStrauss::Qd<0,1,2>

#line 645
    texld_pp r11, r2.yxzw, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.x, r2.yxzw, r1
    mul_pp r1.yzw, r11.xxyz, r1.x  // ::amb<0,1,2>
    mul_pp r1.yzw, r1, c1.w  // ::amb<0,1,2>
    mov_pp r5.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.yzw, r1, c72.xxyz, r5.xxyz  // ::amb<0,1,2>

#line 791
    mul_pp r1.yzw, r3.xxyz, r1  // calcStrauss::Qa<0,1,2>

#line 800
    add_pp r5.xyz, c10, -v2
    nrm_pp r6.xyz, r5  // ::viewVec<0,1,2>

#line 804
    mul r5.xyz, r2.yxzw, r0.x
    mov r7.y, c0.y
    mad_pp r5.xyz, r5, r7.y, -c3  // ::RVec<0,1,2>
    dp3_sat_pp r0.x, r6, r5  // ::vdotr<0>
    pow_pp r3.w, r0.x, r2.w  // ::rs<0>
    mad_pp r0.xyz, r8, r0.yzww, c4.y  // ::Cs<0,1,2>
    mad_pp r0.xyz, r0, r9.x, c4.x  // ::Cs<0,1,2>
    mul_pp r0.xyz, r0, c6.w  // ::Cs<0,1,2>
    mul_pp r0.xyz, r3.w, r0  // calcStrauss::Qs<0,1,2>

#line 657
    mad_sat_pp r5.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 828
    mul_pp r1.yzw, r1, v1.w  // calcStrauss::Qa<0,1,2>
    mul_pp r0.xyz, r0, r5.y  // calcStrauss::Qs<0,1,2>

#line 537
    dp3_pp r0.w, r6.yxzw, r2  // ::dot_viewNrm<0>
    mov_sat_pp r2.x, -r2.x
    add_pp r2.x, -r2.x, c4.x  // ::vertAtten<0>
    abs_sat_pp r0.w, r0.w
    add_pp r0.w, -r0.w, c4.x  // ::rim<0>
    pow_pp r2.y, r0.w, c70.w  // ::rim<0>
    mul_pp r0.w, r2.x, r2.x
    mul_pp r0.w, r2.y, r0.w  // ::rim<0>
    mov_pp r2.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r2.xyz, -r2, c71
    mad_pp r2.xyz, r0.w, r2, c70  // ::ret<0,1,2>

#line 835
    mul_pp r2.xyz, r3, r2  // calcStrauss::Qr<0,1,2>

#line 296
    add r6.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r6  // ::lightSpacePos<3>
    add r6.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>
    mul r7.xyz, c21, v2.y
    mad r7.xyz, v2.x, c20, r7
    mad r7.xyz, v2.z, c22, r7
    mad r7.xyz, v2.w, c23, r7  // ::lightSpacePos<0,1,2>
    mov r8, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r8, r6.x, r8, c24  // ::scaleOffset<0,1,2,3>
    cmp r8, r6.y, c26, r8  // ::scaleOffset<0,1,2,3>
    cmp r8, r6.z, c27, r8  // ::scaleOffset<0,1,2,3>
    mad r8.xy, r7, r8, r8.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r8.zw, r7.z, c4.xyxz, c4.xyzx
    texldp r8, r8, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    add r0.w, -r0.w, c30.z
    cmp r0.w, r0.w, r8.x, c4.x  // ::shadowValue<0>
    max_sat_pp r2.w, r0.w, c30.x  // ::calcShadow<0>

#line 976
    mul_pp r6.xyz, r2.w, c2
    mad_pp r0.xyz, r4, r5.x, r0
    mad_pp r0.xyz, r6, r0, r1.yzww
    mad_pp r0.xyz, r2, c2, r0  // ::Ir<0,1,2>

#line 531
    mad_pp r1.yzw, r0.xxyz, c7.w, c7.xxyz
    mul_pp r0.w, r10.w, c8.z
    lrp_pp r2.xyz, r0.w, r1.yzww, r0  // ::outCol<0,1,2>
    mad_pp r0.x, r5.w, -r6.w, r10.w
    mad_pp oC0.w, c8.w, r0.x, r7.w  // ::main<3>

#line 982
    mov r0.x, v3.w
    mov r0.y, v4.w
    mov r0.z, v5.w
    mul_pp r0.xyz, r3, r0
    mad_pp oC0.xyz, r0, r1.x, r2  // ::main<0,1,2>

// approximately 137 instruction slots used (7 texture, 130 arithmetic)
