//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Trail.pso
//
//
// Parameters:
//
//   float4 g__RT;
//   sampler2D g__albedoMap;
//   sampler2D g__backBufferMap;
//   sampler2D g__refractionMap;
//   float4 g__viewPort;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   g__viewPort      c38      1
//   g__RT            c41      1
//   g__albedoMap     s0       1
//   g__refractionMap s10      1
//   g__backBufferMap s11      1
//

    ps_3_0
    def c0, 1, 0.5, 2, -1
    def c1, 1, 0, 0, 0
    dcl_color v0.w  // IN<7>
    dcl_texcoord v1.xyz  // IN<8,9,10>
    dcl_texcoord1 v2.xyw  // IN<12,13,15>
    dcl_2d s0
    dcl_2d s10
    dcl_2d s11

#line 1135 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Trail.final"
    rcp r0.x, c41.x
    rcp r0.y, c41.y
    mul_pp r0, r0.xyxy, c38.zwxy  // ::viewportRatio<0,1>, ::viewportOffset<0,1>

#line 1131
    rcp r1.x, v2.w
    mad_pp r1.xy, v2, r1.x, c0.x  // ::screenUV<0,1>
    mul_pp r1.x, r1.x, c0.y  // ::screenUV<0>

#line 1137
    mad_pp r1.z, r1.y, -c0.y, c0.x
    mad_pp r0.xy, r1.xzzw, r0, r0.zwzw  // ::screenUV<0,1>
    texld_pp r1, v1, s10  // ::refractionMap<0,1>
    mad_pp r0.zw, r1.xyxy, c0.z, c0.w  // ::offset<0,1>
    texld_pp r1, v1, s0  // ::alpha<0>

#line 1142
    mul_pp r1.x, r1.w, v0.w
    mul_pp r0.zw, r0, r1.x  // ::offset<0,1>
    mad_pp r0.xy, r0.zwzw, v1.z, r0  // ::screenUV<0,1>
    texld_pp r0, r0, s11  // ::Ir<0,1,2>
    mad_pp oC0, r0.xyzx, c1.xxxy, c1.yyyx  // ::main<0,1,2,3>

// approximately 16 instruction slots used (3 texture, 13 arithmetic)
