//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Foliage_WPos_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   samplerCUBE g__ambientMap;
//   float4 g__sunCol;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   g__ambient    c1       1
//   g__sunCol     c2       1
//   g__albedoMap  s0       1
//   g__ambientMap s6       1
//

    ps_3_0
    def c0, 0.00392156886, 1, 0, 0
    dcl_texcoord v0.w  // IN<7>
    dcl_color v1.xyz  // IN<8,9,10>
    dcl_texcoord1 v2.xy  // IN<12,13>
    dcl_2d s0
    dcl_cube s6

#line 1140 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Foliage_WPos_VtxAtm.final"
    texld_pp r0, c0.zyzw, s6
    mad_pp r0.xyz, r0, c1.w, c1  // ::ambient<0,1,2>
    add_pp r0.xyz, r0, c2

#line 1131
    texld_pp r1, v2, s0  // ::diffuseSampl<0,1,2,3>

#line 1141
    mul_pp r0.xyz, r0, r1  // ::accept<0,1,2>
    mul_pp r0.xyz, r0, v1  // ::accept<0,1,2>

#line 1133
    frc r0.w, v0.w  // ::density<0>

#line 1137
    add r1.x, r1.w, -r0.w

#line 1134
    add_pp r0.w, -r0.w, v0.w  // ::alpha<0>
    mul_pp r0.w, r0.w, c0.x  // ::accept<3>

#line 1143
    cmp_pp oC0.xyz, r1.x, r0, c0.z  // ::main<0,1,2>

#line 1137
    cmp_pp r0.x, r1.x, c0.y, c0.z  // ::interp<0>

#line 1144
    mul_pp oC0.w, r0.w, r0.x  // ::main<3>

// approximately 13 instruction slots used (2 texture, 11 arithmetic)
