//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Lit_AN_Dn_Em_Vd_WPos_Shdw_VNorm_VtxAtm_Rim_3DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   sampler2D g__detailNormalMap;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   sampler2D g__normalMap;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__hdrTexParms           c68      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     9
//   g__albedoMap             s0       1
//   g__normalMap             s2       1
//   g__detailNormalMap       s4       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 2, -1, 1.04999995, 0.5
    def c4, 0.349999994, 0.00999999978, 0, 0
    def c9, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2  // IN<11,12,13,14>
    dcl_texcoord1 v3  // IN<15,16,17,18>
    dcl_texcoord2 v4  // IN<19,20,21,22>
    dcl_texcoord3 v5  // IN<23,24,25,26>
    dcl_texcoord4 v6.xy  // IN<27,28>
    dcl_texcoord5 v7.xy  // IN<31,32>
    dcl_texcoord6 v8.xy  // IN<35,36>
    dcl vFace  // IN<39>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s4
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 1032 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Lit_AN_Dn_Em_Vd_WPos_Shdw_VNorm_VtxAtm_Rim_3DL.final"
    texld_pp r0, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r0, r0, c5  // ::diffuseSampl<0,1,2,3>

#line 667
    texld_pp r1, v7, s2  // ::sampl<0,1,3>

#line 527
    mad_pp r1.z, r0.w, -v0.w, r1.w

#line 1034
    mul_pp r0, r0, v0  // ::diffuseSampl<0,1,2,3>

#line 527
    mad_pp oC0.w, c8.w, r1.z, r0.w  // ::main<3>

#line 296
    add r2.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r2  // ::lightSpacePos<3>
    add r2.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r3, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r3, r2.x, r3, c24  // ::scaleOffset<0,1,2,3>
    cmp r3, r2.y, c26, r3  // ::scaleOffset<0,1,2,3>
    cmp r2, r2.z, c27, r3  // ::scaleOffset<0,1,2,3>

#line 299
    mul r3.xyz, c21, v2.y
    mad r3.xyz, v2.x, c20, r3
    mad r3.xyz, v2.z, c22, r3
    mad r3.xyz, v2.w, c23, r3  // ::lightSpacePos<0,1,2>

#line 304
    mad r2.xy, r3, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r2.zw, r3.z, c9.xyxz, c9.xyzx
    texldp r2, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r2.x, c9.x  // ::shadowValue<0>
    max_sat_pp r1.z, r0.w, c30.x  // ::calcShadow<0>

#line 1063
    mul_pp r2.xyz, r1.z, c2
    max_pp r0.w, c4.x, r1.z

#line 667
    texld_pp r3, v8, s4  // ::sampl<0,1>
    mad_pp r3.xy, r3, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r1.z, r3, -r3, c9.x
    rsq_pp r1.z, r1.z
    rcp_pp r3.z, r1.z  // ::sampl<2>

#line 358
    cmp r1.z, vFace, c9.x, c9.y  // IN<39>
    cmp r1.z, -r1.z, c9.z, c9.x
    cmp r2.w, vFace, c9.w, c9.y
    add_pp r1.z, r1.z, r2.w  // ::g__face<0>

#line 670
    mul_pp r3.xyz, r3, -r1.z  // ::sampl<0,1,2>

#line 662
    mov_sat_pp r2.w, r3.z
    add_pp r2.w, -r2.w, c9.x  // ::w1<0>
    mul_pp r3.xyz, r3, r2.w

#line 668
    mad_pp r4.xy, r1, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r1.x, r4, -r4, c9.x
    rsq_pp r1.x, r1.x
    rcp_pp r4.z, r1.x  // ::sampl<2>
    mul_pp r4.xyz, -r1.z, r4  // ::sampl<0,1,2>

#line 661
    mov_sat_pp r1.x, r4.z
    add_pp r1.x, -r1.x, c0.z  // ::w0<0>
    mad_pp r3.xyz, r4, r1.x, r3
    nrm_pp r4.xyz, r3  // ::combineNormals<0,1,2>

#line 353
    nrm_pp r3.xyz, v3  // ::g__bx<0,1,2>

#line 1041
    dp3_pp r3.x, r3, r4  // ::worldNormal<0>

#line 354
    nrm_pp r5.xyz, v4  // ::g__by<0,1,2>

#line 1041
    dp3_pp r3.y, r5, r4  // ::worldNormal<1>

#line 355
    nrm_pp r5.xyz, v5  // ::g__bz<0,1,2>

#line 1041
    dp3_pp r3.z, r5, r4  // ::worldNormal<2>

#line 1044
    mul_pp r3.xyz, -r1.z, r3  // ::worldNormal<0,1,2>

#line 732
    add_pp r4.xyz, c10, -v2
    nrm_pp r5.xyz, r4  // ::viewVec<0,1,2>

#line 756
    dp3_pp r1.x, -r5, r3
    add_pp r1.x, r1.x, r1.x
    mad_pp r4.xyz, r1.x, -r3, -r5  // ::reflectionVec<0,1,2>

#line 532
    dp3_pp r1.x, r5, r3  // ::dot_viewNrm<0>
    abs_sat_pp r1.x, r1.x
    add_pp r1.x, -r1.x, c9.x  // ::rim<0>
    pow_pp r2.w, r1.x, c70.w  // ::rim<0>

#line 654
    texld_pp r4, r4, s8  // ::sampl<0,1,2,3>
    mad_pp r1.x, r4.w, c68.x, c68.y
    exp_pp r1.x, r1.x  // ::f<0>
    mul_pp r4.xyz, r4, r1.x
    mul_pp r4.xyz, r4, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 1048
    mul_pp r5.xyz, c6, v0  // ::specSampl<0,1,2>

#line 758
    mul_pp r4.xyz, r4, r5  // ::envMapColor<0,1,2>

#line 722
    dp3_pp r1.x, r3, c3  // ::ndotl<0>

#line 759
    mad_pp r1.y, r1.x, c0.w, c0.w

#line 723
    mov_sat_pp r1.x, r1.x
    mul_pp r5.xyz, r0, r1.x  // calcLambert::Qd<0,1,2>

#line 759
    mul_pp r4.xyz, r4, r1.y  // calcLambert::Qe<0,1,2>

#line 1063
    mul_pp r4.xyz, r0.w, r4
    mul_pp r4.xyz, r1.w, r4

#line 526
    mul_pp r0.w, r1.w, c8.z

#line 1063
    mad_pp r1.xyw, r2.xyzz, r5.xyzz, r4.xyzz

#line 352
    nrm_pp r2.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 1045
    mul_pp r2.xyz, -r1.z, r2  // ::g__vertexNormal<0,1,2>

#line 641
    dp3_sat_pp r1.z, r3, r2
    texld_pp r4, r3, s6  // ::amb<0,1,2>
    mul_pp r2.xyz, r1.z, r4  // ::amb<0,1,2>
    mul_pp r2.xyz, r2, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r2.xyz, r2, c72, r4  // ::amb<0,1,2>

#line 1063
    mad_pp r1.xyw, r0.xyzz, r2.xyzz, r1

#line 533
    mov_sat_pp r2.x, -r3.y
    add_pp r2.x, -r2.x, c9.x  // ::vertAtten<0>

#line 536
    mul_pp r2.x, r2.x, r2.x
    mul_pp r2.x, r2.w, r2.x  // ::rim<0>
    mov_pp r4.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r2.yzw, -r4.xxyz, c71.xxyz
    mad_pp r2.xyz, r2.x, r2.yzww, c70  // ::ret<0,1,2>

#line 767
    mul_pp r2.xyz, r0, r2  // calcLambert::Qr<0,1,2>

#line 1063
    mad_pp r1.xyw, c2.xyzz, r2.xyzz, r1  // ::Ir<0,1,2>

#line 526
    mad_pp r2.xyz, r1.xyww, c7.w, c7
    lrp_pp r4.xyz, r0.w, r2, r1.xyww  // ::outCol<0,1,2>

#line 1069
    mov r2.x, v3.w
    mov r2.y, v4.w
    mov r2.z, v5.w
    mul_pp r1.xyw, r0.xyzz, r2.xyzz
    mad_pp r1.xyz, r1.xyww, r1.z, r4  // ::Ir<0,1,2>

#line 835
    add_pp r2.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>
    rcp_pp r0.w, r0.w  // ::lightVecLen<0>

#line 843
    add_pp r0.w, r0.w, -c105.x
    max_pp r1.w, r0.w, c4.y  // ::lightVecLenPrime<0>

#line 722
    dp3_sat_pp r0.w, r3, r2
    mul_pp r2.xyz, r0, r0.w  // calcLambert::Qd<0,1,2>

#line 844
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r4.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 866
    mul_pp r2.xyz, r2, r4  // ::Qd<0,1,2>

#line 835
    add_pp r4.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>
    rcp_pp r0.w, r0.w  // ::lightVecLen<0>

#line 843
    add_pp r0.w, r0.w, -c102.x
    max_pp r1.w, r0.w, c4.y  // ::lightVecLenPrime<0>

#line 722
    dp3_sat_pp r0.w, r3, r4
    mul_pp r4.xyz, r0, r0.w  // calcLambert::Qd<0,1,2>

#line 844
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 867
    mad_pp r2.xyz, r4, r5, r2  // ::Ir<0,1,2>

#line 835
    add_pp r4.xyz, c107, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>
    rcp_pp r0.w, r0.w  // ::lightVecLen<0>

#line 843
    add_pp r0.w, r0.w, -c108.x
    max_pp r1.w, r0.w, c4.y  // ::lightVecLenPrime<0>

#line 722
    dp3_sat_pp r0.w, r3, r4
    mul_pp r0.xyz, r0, r0.w  // calcLambert::Qd<0,1,2>

#line 844
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r1.w, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 871
    mad_pp r0.xyz, r0, r3, r2  // ::Ir<0,1,2>

#line 1072
    add_pp oC0.xyz, r1, r0  // ::main<0,1,2>

// approximately 166 instruction slots used (6 texture, 160 arithmetic)
