//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_Em_WPos_VNorm_Shdw_VtxAtm_4DL.pso
//
//
// Parameters:
//
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__waterFresnelParams;
//   float4 g__waterParams[2];
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__waterFresnelParams    c57      1
//   g__waterParams           c59      1
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100    12
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 64, 0.5, 1, 0
    def c4, 0.00999999978, 0.200000003, 0, 0
    dcl_normal v0.xyz  // IN<4,5,6>
    dcl_texcoord6 v1  // IN<7,8,9,10>
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 876 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_Em_WPos_VNorm_Shdw_VtxAtm_4DL.final"
    add_pp r0.xyz, c107, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 884
    add_pp r0.w, r1.x, -c108.x
    max_pp r1.x, r0.w, c4.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c108.w
    mad_pp r0.w, r1.x, c108.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c106  // getDynamicPointLight::color<0,1,2>

#line 876
    add_pp r2.xyz, c101, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r2, r2
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r2.xyz, r2, r0.w  // ::lightVec<0,1,2>

#line 884
    add_pp r0.w, r1.w, -c102.x
    max_pp r1.w, r0.w, c4.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r3.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 876
    add_pp r4.xyz, c104, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r4, r4
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r4.xyz, r4, r0.w  // ::lightVec<0,1,2>

#line 884
    add_pp r0.w, r1.w, -c105.x
    max_pp r1.w, r0.w, c4.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r5.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 337
    nrm_pp r6.xyz, v0  // ::g__vertexNormal<0,1,2>

#line 763
    dp3_sat_pp r0.w, r6, r4
    mul_pp r4.xyz, r0.w, c5  // calcLambert::Qd<0,1,2>

#line 907
    mul_pp r4.xyz, r5, r4  // ::Qd<0,1,2>

#line 763
    dp3_sat_pp r0.w, r6, r2
    mul_pp r2.xyz, r0.w, c5  // calcLambert::Qd<0,1,2>

#line 908
    mad_pp r2.xyz, r2, r3, r4  // ::Ir<0,1,2>

#line 763
    dp3_sat_pp r0.x, r6, r0
    mul_pp r0.xyz, r0.x, c5  // calcLambert::Qd<0,1,2>

#line 912
    mad_pp r0.xyz, r0, r1, r2  // ::Ir<0,1,2>

#line 876
    add_pp r1.xyz, c110, -v1  // ::lightVec<0,1,2>
    dp3_pp r0.w, r1, r1
    rsq_pp r0.w, r0.w
    rcp_pp r1.w, r0.w  // ::lightVecLen<0>
    mul_pp r1.xyz, r1, r0.w  // ::lightVec<0,1,2>

#line 763
    dp3_sat_pp r0.w, r6, r1
    mul_pp r1.xyz, r0.w, c5  // calcLambert::Qd<0,1,2>

#line 884
    add_pp r0.w, r1.w, -c111.x
    max_pp r1.w, r0.w, c4.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c111.w
    mad_pp r0.w, r1.w, c111.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r2.xyz, r0.w, c109  // getDynamicPointLight::color<0,1,2>

#line 916
    mad_pp r0.xyz, r1, r2, r0  // ::Ir<0,1,2>

#line 300
    add r1.xyz, -c10, v1  // ::delta<0,1,2>
    dp3 r0.w, c11, r1  // ::lightSpacePos<3>
    add r1.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 315
    add r0.w, -r0.w, c30.z

#line 305
    mov r2, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r2, r1.x, r2, c24  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.y, c26, r2  // ::scaleOffset<0,1,2,3>
    cmp r1, r1.z, c27, r2  // ::scaleOffset<0,1,2,3>

#line 303
    mul r2.xyz, c21, v1.y
    mad r2.xyz, v1.x, c20, r2
    mad r2.xyz, v1.z, c22, r2
    mad r2.xyz, v1.w, c23, r2  // ::lightSpacePos<0,1,2>

#line 308
    mad r1.xy, r2, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r1.zw, r2.z, c0, c0.xywz
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r0.w, r0.w, r1.x, c0.z  // ::shadowValue<0>
    max_sat_pp r1.x, r0.w, c30.x  // ::calcShadow<0>

#line 1328
    mul_pp r1.xyz, r1.x, c2

#line 622
    texld_pp r2, r6, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r6, r6
    mul_pp r2.xyz, r2, r0.w  // ::amb<0,1,2>
    mul_pp r2.xyz, r2, c1.w  // ::amb<0,1,2>
    mov_pp r3.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r2.xyz, r2, c72, r3  // ::amb<0,1,2>

#line 789
    mul_pp r2.xyz, r2, c5  // calcLambert::Qa<0,1,2>

#line 773
    add_pp r3.xyz, c10, -v1
    dp3_pp r0.w, r3, r3
    rsq_pp r0.w, r0.w

#line 777
    mad_pp r4.xyz, r3, r0.w, c3

#line 773
    mul_pp r3.xyz, r3, r0.w  // ::viewVec<0,1,2>

#line 777
    nrm_pp r5.xyz, r4  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r6, r5  // ::ndoth<0>
    pow_pp r1.w, r0.w, c0.x  // ::rs<0>

#line 763
    dp3_pp r0.w, r6, c3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w

#line 800
    mad_pp r0.w, r0.w, c0.y, c0.y

#line 1328
    mad_pp r4.xyz, r2.w, c5, r1.w
    mad_pp r1.xyz, r1, r4, r2  // ::Ir<0,1,2>

#line 1333
    add_pp r0.xyz, r0, r1  // ::Ir<0,1,2>

#line 797
    dp3_pp r1.x, -r3, r6
    add_pp r1.x, r1.x, r1.x
    mad_pp r1.xyz, r1.x, -r6, -r3  // ::reflectionVec<0,1,2>

#line 1343
    dp3_sat_pp r1.w, r3, r6
    pow_pp r2.x, r1.w, c57.y
    mad_sat_pp r1.w, c57.x, r2.x, c57.z  // ::fresnelTerm<0>

#line 1354
    add r1.w, -r1.w, c0.z
    max r2.x, c4.y, r1.w
    min_pp oC0.w, r2.x, c0.z  // ::main<3>

#line 636
    texld_pp r1, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r1.w, r1.w, c68.x, c68.y
    exp_pp r1.w, r1.w  // ::f<0>
    mul_pp r1.xyz, r1, r1.w
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 800
    mul_pp r1.xyz, r0.w, r1  // calcLambert::Qe<0,1,2>

#line 1349
    mul_pp r1.xyz, r1, c59.w
    mad_pp oC0.xyz, r0, c59.z, r1  // ::main<0,1,2>

// approximately 125 instruction slots used (3 texture, 122 arithmetic)
