//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_SpeedTree_LeafCard_Lit_A_Shdw_WPos_Vd_VNorm_VtxAtm_2DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__diffColor             c5       1
//   g__emissiveColor         c7       1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     3
//   g__albedoMap             s0       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 0.00999999978, 1, 0, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_texcoord v2.xyz  // IN<11,12,13>
    dcl_texcoord1 v3.xy  // IN<15,16>
    dcl_texcoord4 v4.xyz  // IN<19,20,21>
    dcl_2d s0
    dcl_cube s6

#line 802 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_SpeedTree_LeafCard_Lit_A_Shdw_WPos_Vd_VNorm_VtxAtm_2DL.final"
    add_pp r0.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 810
    add_pp r0.w, r1.x, -c102.x
    max_pp r1.x, r0.w, c0.x  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.x, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 345
    nrm_pp r2.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 625
    texld_pp r3, r2, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r2, r2

#line 702
    dp3_sat_pp r0.x, r2, r0

#line 626
    mul_pp r0.yzw, r3.xxyz, r0.w  // ::amb<0,1,2>
    mul_pp r0.yzw, r0, c1.w  // ::amb<0,1,2>
    mov_pp r2.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r0.yzw, r0, c72.xxyz, r2.xxyz  // ::amb<0,1,2>
    mul_pp r0.yzw, r0, c7.xxyz

#line 980
    texld_pp r2, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r2.xyz, r2, c5  // ::diffuseSampl<0,1,2>

#line 1014
    mad_pp r1.w, r2.w, c5.w, -v0.w
    cmp_pp oC0.w, r1.w, c0.y, c0.z  // ::main<3>

#line 982
    mul_pp r2.xyz, r2, v0  // ::diffuseSampl<0,1,2>

#line 630
    mul_pp r0.yzw, r0, r2.xxyz

#line 729
    add_pp r0.yzw, r0, r0  // calcLambert::Qa<0,1,2>

#line 1007
    mul_pp r3.xyz, c7.w, v4  // ::g__vertexLighting<0,1,2>
    mad_pp r0.yzw, r3.xxyz, r2.xxyz, r0  // ::Ir<0,1,2>

#line 703
    mul_pp r2.xyz, r0.x, r2  // calcLambert::Qd<0,1,2>
    mul_pp r2.xyz, r2, c7.w  // calcLambert::Qd<0,1,2>

#line 1012
    mad_pp oC0.xyz, r2, r1, r0.yzww  // ::main<0,1,2>

// approximately 35 instruction slots used (2 texture, 33 arithmetic)
