//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Foliage_Mesh_WPos_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   samplerCUBE g__ambientMap;
//   float4 g__sunCol;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   g__ambient    c1       1
//   g__sunCol     c2       1
//   g__albedoMap  s0       1
//   g__ambientMap s6       1
//

    ps_3_0
    def c0, 0, 1, 0, 0
    dcl_color v0.xyz  // IN<8,9,10>
    dcl_texcoord1 v1.xy  // IN<12,13>
    dcl_2d s0
    dcl_cube s6

#line 1136 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Foliage_Mesh_WPos_VtxAtm.final"
    texld_pp r0, c0.xyxw, s6
    mad_pp r0.xyz, r0, c1.w, c1  // ::ambient<0,1,2>
    add_pp r0.xyz, r0, c2

#line 1131
    texld_pp r1, v1, s0  // ::diffuseSampl<0,1,2,3>

#line 1137
    mul_pp r0.xyz, r0, r1  // ::accept<0,1,2>
    mov_pp oC0.w, r1.w  // ::main<3>
    mul_pp oC0.xyz, r0, v0  // ::main<0,1,2>

// approximately 7 instruction slots used (2 texture, 5 arithmetic)
