//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Water_A_T1_T3_Em_WPos_VNorm_Shdw_VtxAtm_1DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__waterFresnelParams;
//   sampler2D g__waterNormalMap1;
//   sampler2D g__waterNormalMap3;
//   float4 g__waterNormalScale;
//   float4 g__waterParams[2];
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__waterFresnelParams    c57      1
//   g__waterParams           c59      1
//   g__waterNormalScale      c62      1
//   g__hdrTexParms           c68      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     3
//   g__albedoMap             s0       1
//   g__waterNormalMap1       s1       1
//   g__waterNormalMap3       s3       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 2, -1, 1, 64
    def c4, 0.5, 1, 0, 0.00999999978
    def c6, 0.200000003, 0, 0, 0
    dcl_texcoord v0.xyz  // IN<4,5,6>
    dcl_texcoord1 v1.xyz  // IN<8,9,10>
    dcl_texcoord2 v2.xyz  // IN<12,13,14>
    dcl_texcoord3 v3  // IN<16,17,18,19>
    dcl_texcoord4 v4.zw  // IN<22,23>
    dcl_texcoord6 v5  // IN<24,25,26,27>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s3
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 889 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Water_A_T1_T3_Em_WPos_VNorm_Shdw_VtxAtm_1DL.final"
    add_pp r0.xyz, c101, -v5  // ::lightVec<0,1,2>
    dp3_pp r0.w, r0, r0
    rsq_pp r0.w, r0.w
    rcp_pp r1.x, r0.w  // ::lightVecLen<0>
    mul_pp r0.xyz, r0, r0.w  // ::lightVec<0,1,2>

#line 897
    add_pp r0.w, r1.x, -c102.x
    max_pp r1.x, r0.w, c4.w  // ::lightVecLenPrime<0>
    mul_pp r0.w, r1.x, r1.x
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.x, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r1.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 300
    add r2.xyz, -c10, v5  // ::delta<0,1,2>
    dp3 r0.w, c11, r2  // ::lightSpacePos<3>
    add r2.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 315
    add r0.w, -r0.w, c30.z

#line 305
    mov r3, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r3, r2.x, r3, c24  // ::scaleOffset<0,1,2,3>
    cmp r3, r2.y, c26, r3  // ::scaleOffset<0,1,2,3>
    cmp r2, r2.z, c27, r3  // ::scaleOffset<0,1,2,3>

#line 303
    mul r3.xyz, c21, v5.y
    mad r3.xyz, v5.x, c20, r3
    mad r3.xyz, v5.z, c22, r3
    mad r3.xyz, v5.w, c23, r3  // ::lightSpacePos<0,1,2>

#line 308
    mad r2.xy, r3, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 271
    mad r2.zw, r3.z, c4.xyyz, c4.xyzy
    texldp r2, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 315
    cmp r0.w, r0.w, r2.x, c0.z  // ::shadowValue<0>
    max_sat_pp r1.w, r0.w, c30.x  // ::calcShadow<0>

#line 1381
    mul_pp r2.xyz, r1.w, c2

#line 662
    texld_pp r3, v3.zwzw, s1  // ::sampl<0,1>
    mad_pp r3.xy, r3, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r0.w, r3, -r3, c0.z

#line 1361
    mul_pp r3.xy, r3, c62.x  // ::normSmpl<0,1>

#line 664
    rsq_pp r0.w, r0.w
    rcp_pp r3.z, r0.w  // ::sampl<2>
    texld_pp r4, v4.zwzw, s3  // ::sampl<0,1>
    mad_pp r4.xy, r4, c0.x, c0.y  // ::sampl<0,1>
    dp2add_pp r0.w, r4, -r4, c0.z

#line 1363
    mul_pp r4.xy, r4, c62.z  // ::normSmpl<6,7>

#line 664
    rsq_pp r0.w, r0.w
    rcp_pp r4.z, r0.w  // ::sampl<2>

#line 1367
    add_pp r3.xyz, r3, r4
    nrm_pp r4.xyz, r3  // ::combSampl<0,1,2>

#line 344
    nrm_pp r3.xyz, v0  // ::g__bx<0,1,2>

#line 1369
    dp3_pp r5.x, r3, r4  // ::worldNormal<0>

#line 636
    mov_pp r3.x, r3.z

#line 345
    nrm_pp r6.xyz, v1  // ::g__by<0,1,2>

#line 1369
    dp3_pp r5.y, r6, r4  // ::worldNormal<1>

#line 636
    mov_pp r3.y, r6.z

#line 346
    nrm_pp r6.xyz, v2  // ::g__bz<0,1,2>

#line 1369
    dp3_pp r5.z, r6, r4  // ::worldNormal<2>

#line 636
    mov_pp r3.z, r6.z
    dp3_sat_pp r0.w, r5, r3
    texld_pp r3, r5, s6  // ::amb<0,1,2>
    mul_pp r3.xyz, r0.w, r3  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r4  // ::amb<0,1,2>

#line 1350
    texld_pp r4, v3, s0  // ::diffuseSampl<0,1,2>
    mul_pp r4.xyz, r4, c5  // ::diffuseSampl<0,1,2>

#line 802
    mul_pp r3.xyz, r3, r4  // calcLambert::Qa<0,1,2>

#line 786
    add_pp r6.xyz, c10, -v5
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w

#line 790
    mad_pp r7.xyz, r6, r0.w, c3

#line 786
    mul_pp r6.xyz, r6, r0.w  // ::viewVec<0,1,2>

#line 790
    nrm_pp r8.xyz, r7  // ::HVec<0,1,2>
    dp3_sat_pp r0.w, r5, r8  // ::ndoth<0>
    pow_pp r1.w, r0.w, c0.w  // ::rs<0>

#line 776
    dp3_pp r0.w, r5, c3  // ::ndotl<0>
    mov_sat_pp r2.w, r0.w

#line 813
    mad_pp r0.w, r0.w, c4.x, c4.x

#line 1381
    mad_pp r7.xyz, r2.w, r4, r1.w
    mad_pp r2.xyz, r2, r7, r3  // ::Ir<0,1,2>

#line 776
    dp3_sat_pp r0.x, r5, r0
    mul_pp r0.xyz, r4, r0.x  // calcLambert::Qd<0,1,2>

#line 1386
    mad_pp r0.xyz, r0, r1, r2  // ::Ir<0,1,2>

#line 810
    dp3_pp r1.x, -r6, r5
    add_pp r1.x, r1.x, r1.x
    mad_pp r1.xyz, r1.x, -r5, -r6  // ::reflectionVec<0,1,2>

#line 1396
    dp3_sat_pp r1.w, r6, r5
    pow_pp r2.x, r1.w, c57.y
    mad_sat_pp r1.w, c57.x, r2.x, c57.z  // ::fresnelTerm<0>

#line 1407
    add r1.w, -r1.w, c0.z
    max r2.x, c6.x, r1.w
    min_pp oC0.w, r2.x, c0.z  // ::main<3>

#line 649
    texld_pp r1, r1, s8  // ::sampl<0,1,2,3>
    mad_pp r1.w, r1.w, c68.x, c68.y
    exp_pp r1.w, r1.w  // ::f<0>
    mul_pp r1.xyz, r1, r1.w
    mul_pp r1.xyz, r1, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 813
    mul_pp r1.xyz, r0.w, r1  // calcLambert::Qe<0,1,2>

#line 1402
    mul_pp r1.xyz, r1, c59.w
    mad_pp oC0.xyz, r0, c59.z, r1  // ::main<0,1,2>

// approximately 111 instruction slots used (6 texture, 105 arithmetic)
