//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_strauss_AS_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim_2DL.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   row_major float3x4 g__dynamicLightingLights[8];
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   samplerCUBE g__envMap;
//   float4 g__hdrTexParms;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__specColor;
//   sampler2D g__specularMap;
//   float4 g__straussParms;
//   float4 g__straussParms1;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__specColor             c6       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__straussParms          c66      1
//   g__straussParms1         c67      1
//   g__hdrTexParms           c68      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__dynamicLightingLights c100     6
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__specularMap           s3       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//   g__envMap                s8       1
//

    ps_3_0
    def c0, 4, 0.5, 0.349999994, 0.00999999978
    def c4, 1, -1, 0, -0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3.xy  // IN<16,17>
    dcl_texcoord2 v4.zw  // IN<22,23>
    dcl_texcoord4 v5.xyz  // IN<24,25,26>
    dcl vFace  // IN<28>
    dcl_2d s0
    dcl_2d s3
    dcl_2d s5
    dcl_cube s6
    dcl_cube s8

#line 976 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_strauss_AS_Em_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim_2DL.final"
    texld_pp r0, v3, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r1, c5, v0

#line 519
    mad_pp r2.x, r0.w, -r1.w, c4.x

#line 977
    mul_pp r0, r0, r1  // ::diffuseSampl<0,1,2,3>

#line 519
    mad_pp oC0.w, c8.w, r2.x, r0.w  // ::main<3>

#line 296
    add r1.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r1  // ::lightSpacePos<3>
    add r1.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r2, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r2, r1.x, r2, c24  // ::scaleOffset<0,1,2,3>
    cmp r2, r1.y, c26, r2  // ::scaleOffset<0,1,2,3>
    cmp r1, r1.z, c27, r2  // ::scaleOffset<0,1,2,3>

#line 299
    mul r2.xyz, c21, v2.y
    mad r2.xyz, v2.x, c20, r2
    mad r2.xyz, v2.z, c22, r2
    mad r2.xyz, v2.w, c23, r2  // ::lightSpacePos<0,1,2>

#line 304
    mad r1.xy, r2, r1, r1.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r1.zw, r2.z, c4.xyxz, c4.xyzx
    texldp r1, r1, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r1.x, c4.x  // ::shadowValue<0>
    max_sat_pp r1.x, r0.w, c30.x  // ::calcShadow<0>

#line 1008
    mul_pp r1.yzw, r1.x, c2.xxyz
    max_pp r0.w, c0.z, r1.x

#line 350
    cmp r1.x, vFace, c4.x, c4.y  // IN<28>
    cmp r1.x, -r1.x, c4.z, c4.x
    cmp r2.x, vFace, c4.w, c4.y
    add_pp r1.x, r1.x, r2.x  // ::g__face<0>

#line 347
    nrm_pp r2.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 993
    mul_pp r2.xyz, -r1.x, r2  // ::worldNormal<0,1,2>

#line 789
    add_pp r3.xyz, c10, -v2
    nrm_pp r4.xyz, r3  // ::viewVec<0,1,2>

#line 810
    dp3_pp r1.x, -r4, r2
    add_pp r1.x, r1.x, r1.x
    mad_pp r3.xyz, r1.x, -r2, -r4  // ::reflectionVec<0,1,2>

#line 649
    texld_pp r3, r3, s8  // ::sampl<0,1,2,3>
    mad_pp r1.x, r3.w, c68.x, c68.y
    exp_pp r1.x, r1.x  // ::f<0>
    mul_pp r3.xyz, r3, r1.x
    mul_pp r3.xyz, r3, c68.z  // ::sampleEnvironmentMap<0,1,2>

#line 983
    mul_pp r5.xyz, c6, v0
    texld_pp r6, v4.zwzw, s3  // ::specSampl<0,1,2,3>
    mul_pp r7.xyz, r5, r6  // ::specSampl<0,1,2>

#line 798
    mad_pp r5.xyz, r6, r5, c4.y  // ::Cs<0,1,2>

#line 985
    add_pp r1.x, r6.w, -c66.y
    mov r6.xy, c66  // ::g__straussParms<0,1>
    mad_pp r1.x, c67.x, r1.x, r6.y  // ::specSampl<3>
    mul_pp r1.x, r1.x, c66.w  // ::specSampl<3>
    max_pp r2.w, r1.x, c0.x  // ::specSampl<3>

#line 800
    mad_pp r5.xyz, r5, r6.x, c4.x  // ::Cs<0,1,2>
    mul_pp r5.xyz, r5, c6.w  // ::Cs<0,1,2>

#line 812
    mul_pp r3.xyz, r3, r7  // ::envMapColor<0,1,2>

#line 773
    dp3_pp r1.x, r2, c3  // ::ndotl<0>

#line 813
    mad_pp r3.w, r1.x, c0.y, c0.y
    mul_pp r3.xyz, r3, r3.w  // calcStrauss::Qe<0,1,2>

#line 644
    mad_sat_pp r6.xy, v1.w, c200.xzzw, c200.ywzw  // ::ao<1,2>

#line 827
    mul_pp r3.xyz, r3, r6.y  // calcStrauss::Qe<0,1,2>

#line 1008
    mul_pp r3.xyz, r0.w, r3

#line 793
    add r7.xyz, r2, r2
    mad_pp r8.xyz, r7, r1.x, -c3  // ::RVec<0,1,2>

#line 774
    mov_sat_pp r1.x, r1.x  // ::ndotl_satd<0>
    mul_pp r9.xyz, r0, r1.x  // calcStrauss::Qd<0,1,2>

#line 794
    dp3_sat_pp r0.w, r4, r8  // ::vdotr<0>
    pow_pp r1.x, r0.w, r2.w  // ::rs<0>

#line 802
    mul_pp r8.xyz, r5, r1.x  // calcStrauss::Qs<0,1,2>

#line 826
    mul_pp r6.yzw, r6.y, r8.xxyz  // calcStrauss::Qs<0,1,2>

#line 1008
    mad_pp r6.xyz, r9, r6.x, r6.yzww
    mad_pp r1.xyz, r1.yzww, r6, r3

#line 632
    texld_pp r3, r2, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r2, r2
    mul_pp r3.xyz, r3, r0.w  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r6.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r6  // ::amb<0,1,2>

#line 780
    mul_pp r3.xyz, r0, r3  // calcStrauss::Qa<0,1,2>

#line 1008
    mad_pp r1.xyz, r3, v1.w, r1

#line 525
    mov_sat_pp r1.w, -r2.y
    add_pp r1.w, -r1.w, c4.x  // ::vertAtten<0>

#line 528
    mul_pp r1.w, r1.w, r1.w

#line 524
    dp3_pp r3.x, r4, r2  // ::dot_viewNrm<0>
    abs_sat_pp r3.x, r3.x
    add_pp r3.x, -r3.x, c4.x  // ::rim<0>
    pow_pp r4.w, r3.x, c70.w  // ::rim<0>
    mul_pp r1.w, r1.w, r4.w  // ::rim<0>
    mov_pp r3.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r3.xyz, -r3, c71
    mad_pp r3.xyz, r1.w, r3, c70  // ::ret<0,1,2>

#line 832
    mul_pp r3.xyz, r0, r3  // calcStrauss::Qr<0,1,2>

#line 1008
    mad_pp r1.xyz, r3, c2, r1  // ::Ir<0,1,2>

#line 518
    mad_pp r3.xyz, r1, c7.w, c7
    lrp_pp r6.xyz, c8.z, r3, r1  // ::outCol<0,1,2>

#line 1014
    mul_pp r1.xyz, r0, v5
    mad_pp r1.xyz, r1, r0.w, r6  // ::Ir<0,1,2>

#line 842
    add_pp r3.xyz, c104, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r3, r3
    rsq_pp r0.w, r0.w
    mul_pp r3.xyz, r3, r0.w  // ::lightVec<0,1,2>
    rcp_pp r0.w, r0.w  // ::lightVecLen<0>

#line 850
    add_pp r0.w, r0.w, -c105.x
    max_pp r1.w, r0.w, c0.w  // ::lightVecLenPrime<0>

#line 773
    dp3_pp r0.w, r2, r3  // ::ndotl<0>

#line 793
    mad_pp r3.xyz, r7, r0.w, -r3  // ::RVec<0,1,2>

#line 774
    mov_sat_pp r0.w, r0.w  // ::ndotl_satd<0>

#line 794
    dp3_sat_pp r3.x, r4, r3  // ::vdotr<0>
    pow_pp r4.w, r3.x, r2.w  // ::rs<0>

#line 802
    mul_pp r3.xyz, r5, r4.w  // calcStrauss::Qs<0,1,2>

#line 894
    mad_pp r3.xyz, r0, r0.w, r3  // ::Qd<0,1,2>

#line 851
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c105.w
    mad_pp r0.w, r1.w, c105.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r6.xyz, r0.w, c103  // getDynamicPointLight::color<0,1,2>

#line 895
    mul_pp r3.xyz, r3, r6  // ::Qd<0,1,2>

#line 842
    add_pp r6.xyz, c101, -v2  // ::lightVec<0,1,2>
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w
    mul_pp r6.xyz, r6, r0.w  // ::lightVec<0,1,2>
    rcp_pp r0.w, r0.w  // ::lightVecLen<0>

#line 850
    add_pp r0.w, r0.w, -c102.x
    max_pp r1.w, r0.w, c0.w  // ::lightVecLenPrime<0>

#line 773
    dp3_pp r0.w, r2, r6  // ::ndotl<0>

#line 793
    mad_pp r2.xyz, r7, r0.w, -r6  // ::RVec<0,1,2>

#line 774
    mov_sat_pp r0.w, r0.w  // ::ndotl_satd<0>

#line 794
    dp3_sat_pp r2.x, r4, r2  // ::vdotr<0>
    pow_pp r3.w, r2.x, r2.w  // ::rs<0>

#line 802
    mul_pp r2.xyz, r5, r3.w  // calcStrauss::Qs<0,1,2>

#line 889
    mad_pp r0.xyz, r0, r0.w, r2  // ::Qd<0,1,2>

#line 851
    mul_pp r0.w, r1.w, r1.w
    mul_pp r0.w, r0.w, c102.w
    mad_pp r0.w, r1.w, c102.z, r0.w
    rcp_sat_pp r0.w, r0.w  // ::attenuation<0>
    mul_pp r2.xyz, r0.w, c100  // getDynamicPointLight::color<0,1,2>

#line 896
    mad_pp r0.xyz, r0, r2, r3  // ::Ir<0,1,2>

#line 1017
    add_pp oC0.xyz, r1, r0  // ::main<0,1,2>

// approximately 146 instruction slots used (5 texture, 141 arithmetic)
