//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Crowd_HA_Billboard_AN_Vd_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   sampler2D g__normalMap;
//   float4 g__sunCol;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__normalMap           s2       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 2, 1, -1, 0
    def c3, 2, 0.5, -1, 1
    dcl_texcoord v0.xy  // IN<8,9>
    dcl_texcoord1 v1  // IN<12,13,14,15>
    dcl_texcoord2 v2.xzw  // IN<16,18,19>
    dcl_texcoord3 v3  // IN<20,21,22,23>
    dcl_texcoord5 v4.xy  // IN<24,25>
    dcl_2d s0
    dcl_2d s2
    dcl_cube s6

#line 1180 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Crowd_HA_Billboard_AN_Vd_VtxAtm.final"
    mov r0.zw, v1  // IN<14,15>
    mad_pp r0.xy, v4, c3.x, -r0.zwzw
    mad_pp r0.xy, v2.zwzw, r0, r0.zwzw
    mul_sat_pp r0.xy, r0, c3.y  // ::texCoord<0,1>

#line 1185
    mov r1.xz, v0.xyyw
    mov r1.yw, v1.x
    mad_pp r0.zw, r0.xyxy, v1, r1.xyxy  // ::uvCurrFrameCurrCell<0,1>
    mad_pp r1.xy, r0, v1.zwzw, r1.zwzw  // ::uvCurrFrameNextCell<0,1>

#line 659
    texld_pp r2, r0.zwzw, s2  // ::sampl<0,1,3>

#line 1188
    texld_pp r3, r0.zwzw, s0  // ::diffuseCurrFrameCurrCell<0,1,2,3>

#line 660
    mad_pp r0.zw, r2.xyxy, c3.x, c3.z  // ::sampl<0,1>

#line 1195
    mad_pp r2.xyw, r2, c0.xxzy, c0.zzzw

#line 661
    dp2add_pp r0.z, r0.zwzw, -r0.zwzw, c3.w
    rsq_pp r0.z, r0.z
    rcp_pp r2.z, r0.z  // ::sampl<2>

#line 1195
    dp4_pp r0.z, r2, r2
    rsq_pp r0.z, r0.z
    mul_pp r2.xyz, r2, r0.z  // ::nrmSamplCurrFrameCurrCell<0,1,2>

#line 659
    texld_pp r4, r1, s2  // ::sampl<0,1,3>

#line 1189
    texld_pp r1, r1, s0  // ::diffuseCurrFrameNextCell<0,1,2,3>

#line 1192
    lrp_pp r5, v2.x, r1, r3

#line 660
    mad_pp r0.zw, r4.xyxy, c3.x, c3.z  // ::sampl<0,1>

#line 1196
    mad_pp r1.xyw, r4, c0.xxzy, c0.zzzw

#line 661
    dp2add_pp r0.z, r0.zwzw, -r0.zwzw, c3.w
    rsq_pp r0.z, r0.z
    rcp_pp r1.z, r0.z  // ::sampl<2>

#line 1196
    dp4_pp r0.z, r1, r1
    rsq_pp r0.z, r0.z
    mul_pp r1.xyz, r1, r0.z  // ::nrmSamplCurrFrameNextCell<0,1,2>

#line 1199
    lrp_pp r3.xyz, v2.x, r1, r2

#line 1187
    mov r1.xz, v0.xyyw
    mov r1.yw, v1.y
    mad_pp r0.zw, r0.xyxy, v1, r1.xyxy  // ::uvNextFrameCurrCell<0,1>
    mad_pp r0.xy, r0, v1.zwzw, r1.zwzw  // ::uvNextFrameNextCell<0,1>

#line 659
    texld_pp r1, r0.zwzw, s2  // ::sampl<0,1,3>

#line 1190
    texld_pp r2, r0.zwzw, s0  // ::diffuseNextFrameCurrCell<0,1,2,3>

#line 660
    mad_pp r0.zw, r1.xyxy, c3.x, c3.z  // ::sampl<0,1>

#line 1197
    mad_pp r1.xyw, r1, c0.xxzy, c0.zzzw

#line 661
    dp2add_pp r0.z, r0.zwzw, -r0.zwzw, c3.w
    rsq_pp r0.z, r0.z
    rcp_pp r1.z, r0.z  // ::sampl<2>

#line 1197
    dp4_pp r0.z, r1, r1
    rsq_pp r0.z, r0.z
    mul_pp r1.xyz, r1, r0.z  // ::nrmSamplNextFrameCurrCell<0,1,2>

#line 659
    texld_pp r4, r0, s2  // ::sampl<0,1,3>

#line 1191
    texld_pp r0, r0, s0  // ::diffuseNextFrameNextCell<0,1,2,3>
    lrp_pp r6, v2.x, r0, r2
    lrp_pp r0, v3.w, r6, r5  // ::color<0,1,2,3>

#line 660
    mad_pp r2.xy, r4, c3.x, c3.z  // ::sampl<0,1>

#line 1198
    mad_pp r4.xyw, r4, c0.xxzy, c0.zzzw

#line 661
    dp2add_pp r1.w, r2, -r2, c3.w
    rsq_pp r1.w, r1.w
    rcp_pp r4.z, r1.w  // ::sampl<2>

#line 1198
    dp4_pp r1.w, r4, r4
    rsq_pp r1.w, r1.w
    mul_pp r2.xyz, r4, r1.w  // ::nrmSamplNextFrameNextCell<0,1,2>
    lrp_pp r4.xyz, v2.x, r2, r1
    lrp_pp r1.xyz, v3.w, r4, r3  // ::nrmSampl<0,1,2>
    mov_pp r1.w, -r1.x
    nrm_pp r2.xyz, v3
    dp3_sat_pp r1.w, r1.wyzw, r2

#line 632
    mul_pp r1.xyz, r1, c3.zwww
    texld_pp r2, r1, s6  // ::amb<0,1,2>
    dp3_sat_pp r1.x, r1, r1
    mul_pp r1.xyz, r2, r1.x  // ::amb<0,1,2>
    mul_pp r1.xyz, r1, c1.w  // ::amb<0,1,2>
    mov_pp r2.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r1.xyz, r1, c72, r2  // ::amb<0,1,2>

#line 1203
    mad_pp r1.xyz, r1.w, c2, r1  // ::sunLight<0,1,2>
    mul_pp oC0.xyz, r0, r1  // ::main<0,1,2>
    mov_pp oC0.w, r0.w  // ::main<3>

// approximately 77 instruction slots used (9 texture, 68 arithmetic)
