//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_Lit_AN_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__ambientOcclusionParms;
//   float4 g__cameraFront;
//   float4 g__cameraPos;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float4 g__emissiveParms;
//   sampler2D g__normalMap;
//   float4 g__rimLightEdge;
//   float4 g__rimLightFront;
//   float4 g__shadowDistances;
//   sampler2D g__shadowMap;
//   row_major float4x4 g__shadowMatrices;
//   float4 g__shadowMisc;
//   float4 g__shadowScaleOffset[4];
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g__ambient               c1       1
//   g__sunCol                c2       1
//   g__sunDir                c3       1
//   g__diffColor             c5       1
//   g__emissiveColor         c7       1
//   g__emissiveParms         c8       1
//   g__cameraPos             c10      1
//   g__cameraFront           c11      1
//   g__shadowMatrices        c20      4
//   g__shadowScaleOffset     c24      4
//   g__shadowDistances       c28      1
//   g__shadowMisc            c30      1
//   g__rimLightFront         c70      1
//   g__rimLightEdge          c71      1
//   g__ambientCubeMapColor   c72      1
//   g__ambientOcclusionParms c200     1
//   g__albedoMap             s0       1
//   g__normalMap             s2       1
//   g__shadowMap             s5       1
//   g__ambientMap            s6       1
//

    ps_3_0
    def c0, 1, -1, 0, -0
    def c4, 2, -1, 0, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_normal v1  // IN<8,9,10,11>
    dcl_texcoord v2  // IN<12,13,14,15>
    dcl_texcoord1 v3  // IN<16,17,18,19>
    dcl_texcoord2 v4  // IN<20,21,22,23>
    dcl_texcoord3 v5  // IN<24,25,26,27>
    dcl_texcoord4 v6.xy  // IN<28,29>
    dcl_texcoord5 v7.xy  // IN<32,33>
    dcl vFace  // IN<36>
    dcl_2d s0
    dcl_2d s2
    dcl_2d s5
    dcl_cube s6

#line 974 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_Lit_AN_Vd_Ao_WPos_Shdw_VNorm_VtxAtm_Rim.final"
    texld_pp r0, v6, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r0, r0, c5  // ::diffuseSampl<0,1,2,3>

#line 668
    texld_pp r1, v7, s2  // ::sampl<0,1,3>

#line 525
    mad_pp r1.z, r0.w, -v0.w, r1.w

#line 976
    mul_pp r0, r0, v0  // ::diffuseSampl<0,1,2,3>

#line 525
    mad_pp oC0.w, c8.w, r1.z, r0.w  // ::main<3>

#line 296
    add r2.xyz, -c10, v2  // ::delta<0,1,2>
    dp3 r0.w, c11, r2  // ::lightSpacePos<3>
    add r2.xyz, r0.w, -c28.yzww  // ::delta<0,1,2>

#line 311
    add r0.w, -r0.w, c30.z

#line 301
    mov r3, c25  // ::g__shadowScaleOffset<4,5,6,7>
    cmp r3, r2.x, r3, c24  // ::scaleOffset<0,1,2,3>
    cmp r3, r2.y, c26, r3  // ::scaleOffset<0,1,2,3>
    cmp r2, r2.z, c27, r3  // ::scaleOffset<0,1,2,3>

#line 299
    mul r3.xyz, c21, v2.y
    mad r3.xyz, v2.x, c20, r3
    mad r3.xyz, v2.z, c22, r3
    mad r3.xyz, v2.w, c23, r3  // ::lightSpacePos<0,1,2>

#line 304
    mad r2.xy, r3, r2, r2.zwzw  // ::lightSpacePos<0,1>

#line 267
    mad r2.zw, r3.z, c0.xyxz, c0.xyzx
    texldp r2, r2, s5  // ::ShadowSample2D_Bilinear<0>

#line 311
    cmp r0.w, r0.w, r2.x, c0.x  // ::shadowValue<0>
    max_sat_pp r1.z, r0.w, c30.x  // ::calcShadow<0>

#line 1005
    mul_pp r2.xyz, r1.z, c2

#line 669
    mad_pp r1.xy, r1, c4.x, c4.y  // ::sampl<0,1>

#line 524
    mul_pp r0.w, r1.w, c8.z

#line 670
    dp2add_pp r1.w, r1, -r1, c0.x
    rsq_pp r1.w, r1.w
    rcp_pp r1.z, r1.w  // ::sampl<2>

#line 356
    cmp r1.w, vFace, c0.x, c0.y  // IN<36>
    cmp r1.w, -r1.w, c0.z, c0.x
    cmp r2.w, vFace, c0.w, c0.y
    add_pp r1.w, r1.w, r2.w  // ::g__face<0>

#line 671
    mul_pp r1.xyz, r1, -r1.w  // ::sampl<0,1,2>

#line 351
    nrm_pp r3.xyz, v3  // ::g__bx<0,1,2>

#line 983
    dp3_pp r3.x, r3, r1  // ::worldNormal<0>

#line 352
    nrm_pp r4.xyz, v4  // ::g__by<0,1,2>

#line 983
    dp3_pp r3.y, r4, r1  // ::worldNormal<1>

#line 353
    nrm_pp r4.xyz, v5  // ::g__bz<0,1,2>

#line 983
    dp3_pp r3.z, r4, r1  // ::worldNormal<2>

#line 986
    mul_pp r1.xyz, -r1.w, r3.yxzw  // ::worldNormal<1,0,2>

#line 350
    nrm_pp r3.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 987
    mul_pp r3.xyz, -r1.w, r3  // ::g__vertexNormal<0,1,2>

#line 639
    dp3_sat_pp r1.w, r1.yxzw, r3
    texld_pp r3, r1.yxzw, s6  // ::amb<0,1,2>
    mul_pp r3.xyz, r1.w, r3  // ::amb<0,1,2>
    mul_pp r3.xyz, r3, c1.w  // ::amb<0,1,2>
    mov_pp r4.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r3.xyz, r3, c72, r4  // ::amb<0,1,2>

#line 743
    mul_pp r3.xyz, r0, r3  // calcLambert::Qa<0,1,2>

#line 756
    mul_pp r3.xyz, r3, v1.w  // calcLambert::Qa<0,1,2>

#line 717
    dp3_sat_pp r2.w, r1.yxzw, c3
    mul_pp r4.xyz, r0, r2.w  // calcLambert::Qd<0,1,2>

#line 649
    mad_sat_pp r2.w, v1.w, c200.x, c200.y  // ::ao<1>

#line 757
    mul_pp r4.xyz, r4, r2.w  // calcLambert::Qd<0,1,2>

#line 1005
    mad_pp r2.xyz, r2, r4, r3

#line 727
    add_pp r3.xyz, c10, -v2
    nrm_pp r4.xyz, r3  // ::viewVec<0,1,2>

#line 530
    dp3_pp r1.y, r4.yxzw, r1  // ::dot_viewNrm<0>
    mov_sat_pp r1.x, -r1.x
    add_pp r1.x, -r1.x, c0.x  // ::vertAtten<0>

#line 534
    mul_pp r1.x, r1.x, r1.x
    abs_sat_pp r1.y, r1.y
    add_pp r1.y, -r1.y, c0.x  // ::rim<0>
    pow_pp r2.w, r1.y, c70.w  // ::rim<0>
    mul_pp r1.x, r1.x, r2.w  // ::rim<0>
    mov_pp r3.xyz, c70  // ::g__rimLightFront<0,1,2>
    add_pp r3.xyz, -r3, c71
    mad_pp r1.xyz, r1.x, r3, c70  // ::ret<0,1,2>

#line 761
    mul_pp r1.xyz, r0, r1  // calcLambert::Qr<0,1,2>

#line 1005
    mad_pp r1.xyz, c2, r1, r2  // ::Ir<0,1,2>

#line 524
    mad_pp r2.xyz, r1, c7.w, c7
    lrp_pp r3.xyz, r0.w, r2, r1  // ::outCol<0,1,2>

#line 1011
    mov r1.x, v3.w
    mov r1.y, v4.w
    mov r1.z, v5.w
    mul_pp r0.xyz, r0, r1
    mad_pp oC0.xyz, r0, r1.w, r3  // ::main<0,1,2>

// approximately 91 instruction slots used (4 texture, 87 arithmetic)
