//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_VolumetricFinal_AD.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__cameraClip;
//   sampler2D g__detailMap;
//   sampler2D g__normalMap;
//   sampler2D g__specularMap;
//   float4 g__volumetricControl;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   g__volumetricControl c88      1
//   g__cameraClip        c89      1
//   g__albedoMap         s0       1
//   g__detailMap         s1       1
//   g__normalMap         s2       1
//   g__specularMap       s3       1
//

    ps_3_0
    def c0, 0, 0, 0, 0
    def c1, 0.5, 1, 0.03125, 0.0009765625
    dcl_texcoord v0.xy  // IN<4,5>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3

#line 1160 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_VolumetricFinal_AD.final"
    texld r0, v0, s1  // ::frontCol<0,1,2,3>
    mul r1.x, r0.w, r0.w
    mul_sat r0.w, r0.w, r1.x  // ::vertexAlpha1<0>

#line 1159
    texld r1, v0, s0  // ::backCol<0,1,2,3>

#line 1163
    mul r2.x, r1.w, r1.w
    mul_sat r1.w, r1.w, r2.x  // ::vertexAlpha2<0>
    add r0.xyz, -r0, r1  // ::depthCol<0,1,2>
    dp3 r0.x, r0, c1.yzww  // ::depth<0>
    add r0.y, r0.w, r1.w
    mul r0.y, r0.y, c1.x  // ::vertexAlpha<0>

#line 1168
    add r0.z, -c89.x, c89.y  // ::farMinusNear<0>
    mul r0.x, r0.x, r0.z  // ::depth<0>
    mul r0.x, r0.x, c88.x  // ::depth<0>

#line 1161
    texld r1, v0, s2  // ::uvs<0,1,2,3>

#line 1172
    texld r2, r1, s3  // ::color<0,1,2>
    texld r1, r1.zwzw, s3
    add r1.xyz, r2, r1  // ::color<0,1,2>
    mul r0.xzw, r0.x, r1.xyyz  // ::color<0,1,2>
    mul_pp oC0.xyz, r0.y, r0.xzww  // ::main<0,1,2>
    mov_pp oC0.w, c0.x  // ::main<3>

// approximately 20 instruction slots used (5 texture, 15 arithmetic)
