//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_DBG_CubeMap_Vd_WPos_VNorm.pso
//
//
// Parameters:
//
//   samplerCUBE g__dbgCubeMap;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   g__dbgCubeMap s0       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_color v0.xyz  // IN<4,5,6>
    dcl_normal v1.xyz  // IN<8,9,10>
    dcl_cube s0

#line 340 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_DBG_CubeMap_Vd_WPos_VNorm.final"
    nrm_pp r0.xyz, v1  // ::g__vertexNormal<0,1,2>

#line 1134
    texld_pp r0, r0, s0  // ::diffuseSampl<0,1,2>
    mul_pp oC0.xyz, r0, v0  // ::main<0,1,2>
    mov_pp oC0.w, c0.x  // ::main<3>

// approximately 6 instruction slots used (1 texture, 5 arithmetic)
