//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\Mg_FP_SpeedTree_Billboard_Lit_A_Shdw_WPos_Vd_VNorm_VtxAtm.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__diffColor;
//   float4 g__emissiveColor;
//   float3 g__worldNormal;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__diffColor           c5       1
//   g__emissiveColor       c7       1
//   g__worldNormal         c12      1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_color v0.w  // IN<7>
    dcl_texcoord1 v1.xy  // IN<15,16>
    dcl_texcoord4 v2.xyz  // IN<19,20,21>
    dcl_2d s0
    dcl_cube s6

#line 624 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\Mg_FP_SpeedTree_Billboard_Lit_A_Shdw_WPos_Vd_VNorm_VtxAtm.final"
    texld_pp r0, c12, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, c12, c12
    mul_pp r0.xyz, r0, r0.w  // ::amb<0,1,2>
    mul_pp r0.xyz, r0, c1.w  // ::amb<0,1,2>
    mov_pp r1.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r0.xyz, r0, c72, r1  // ::amb<0,1,2>

#line 974
    texld_pp r1, v1, s0  // ::diffuseSampl<0,1,2,3>
    mul_pp r1.xyz, r1, c5  // ::diffuseSampl<0,1,2>

#line 979
    add_pp r0.w, r1.w, -v0.w
    cmp_pp oC0.w, r0.w, c0.x, c0.y  // ::main<3>
    mul_pp r0.xyz, r0, r1
    mul_pp r1.xyz, r1, v2
    mul r0.xyz, r0, c7.z
    add r0.xyz, r0, r0
    lrp_pp r0.w, c7.x, c7.y, v2.x
    mad_pp oC0.xyz, r1, r0.w, r0  // ::main<0,1,2>

// approximately 16 instruction slots used (2 texture, 14 arithmetic)
