//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\MgFP_ScreenScattering__filter.pso
//
//
// Parameters:
//
//   sampler2D g__backBufferMap;
//   float4 g__cameraPos;
//   row_major float4x4 g__invViewProjMatrix;
//   float4 g__scatteringBeta1PlusBeta2;
//   float4 g__scatteringBetaDash1;
//   float4 g__scatteringBetaDash2;
//   float4 g__scatteringConstant;
//   float4 g__scatteringExtinctionColor;
//   float4 g__scatteringHG;
//   float4 g__scatteringInscatteringColor;
//   float4 g__scatteringMultiplier;
//   float4 g__scatteringOneOverBeta1PlusBeta2;
//   float4 g__sunCol;
//   float4 g__sunDir;
//   float4 g__viewportAdjustOffset;
//   float4 g__viewportAdjustScale;
//   sampler2D g__zMap;
//
//
// Registers:
//
//   Name                               Reg   Size
//   ---------------------------------- ----- ----
//   g__sunCol                          c2       1
//   g__sunDir                          c3       1
//   g__cameraPos                       c10      1
//   g__viewportAdjustScale             c39      1
//   g__viewportAdjustOffset            c40      1
//   g__invViewProjMatrix               c47      4
//   g__scatteringInscatteringColor     c180     1
//   g__scatteringExtinctionColor       c181     1
//   g__scatteringConstant              c182     1
//   g__scatteringOneOverBeta1PlusBeta2 c183     1
//   g__scatteringBeta1PlusBeta2        c184     1
//   g__scatteringBetaDash1             c185     1
//   g__scatteringBetaDash2             c186     1
//   g__scatteringHG                    c187     1
//   g__scatteringMultiplier            c188     1
//   g__zMap                            s7       1
//   g__backBufferMap                   s11      1
//

    ps_3_0
    def c0, 1, 0.5, 0, 1.44269502
    def c1, 9.99999975e-005, 0, 0, 0
    dcl_texcoord v0.xy  // IN<0,1>
    dcl_2d s7
    dcl_2d s11

#line 1150 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgFP_ScreenScattering__filter.final"
    texld r0, v0, s7  // ::zValue<0>
    mov r0.z, r0.x
    mov r0.xy, v0
    mov r1.xyz, c39  // ::g__viewportAdjustScale<0,1,2>
    mad r0.xyz, r0, r1, c40  // ::pos<0,1,2>
    mul r1, r0.y, c48
    mad r1, r0.x, c47, r1
    mad r0, r0.z, c49, r1
    add r0, r0, c50  // ::pos<0,1,2,3>
    rcp r0.w, r0.w
    mul r1.x, r0.y, r0.w  // ::pos<1>

#line 596
    mad r0.xyz, r0, -r0.w, c10  // ::viewVec<0,1,2>

#line 581
    min r2.w, c10.y, r1.x  // ::r11<1>
    max r2.z, r1.x, c10.y  // ::r11<0>

#line 583
    mul r1, r2.zwzw, c182.yyww  // ::r11<0,1,2,3>
    mad r2.xy, r2.z, c182.ywzw, -r1.ywzw  // ::r11<0,1>
    min r3, r1, c0.x  // ::r10<0,1,2,3>
    add r2.zw, -r3.xyyw, r3.xyxz  // ::r11<2,3>

#line 591
    add r1.xy, r3.xzzw, r3.ywzw  // ::r10<1,3>
    mad r1.xy, r1, -c0.y, c0.x  // ::r10<1,3>

#line 587
    max r3, r2, c182.y  // ::r11<0,1,2,3>
    rcp r2.x, r3.x  // ::r11<0>
    rcp r2.y, r3.y  // ::r11<1>
    mul r1.zw, r3, r2.xyxy  // ::r11<0,1>

#line 594
    mul r1.xy, r1, r1.zwzw
    mul r1.xy, r1, c182.xzzw  // ::atmosphereDensity<0>, ::hazeDensity<0>
    add r0.w, r1.y, r1.x  // ::density<0>

#line 602
    mul r1.xyz, r0.w, -c184

#line 597
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    rcp r1.w, r0.w  // ::s<0>
    mul r0.xyz, r0, r0.w  // ::viewVec<0,1,2>
    dp3 r0.x, r0, c3
    min r2.x, r0.x, c0.z  // ::cosTheta<0>
    mul r0.x, r1.w, c181.w  // ::s<0>

#line 602
    mul r0.xyz, r1, r0.x
    mul r0.xyz, r0, c0.w  // calculateScattering::extinction<0,1,2>
    exp r1.x, r0.x  // calculateScattering::extinction<0>
    exp r1.y, r0.y  // calculateScattering::extinction<1>
    exp r1.z, r0.z  // calculateScattering::extinction<2>

#line 609
    add r0.xyz, -r1, c0.x
    mul r1.xyz, r1, c188.x  // calculateScattering::extinction<0,1,2>
    mul r1.xyz, r1, c181  // calculateScattering::extinction<0,1,2>

#line 606
    mad r0.w, c187.z, r2.x, c187.y

#line 601
    mad r1.w, r2.x, r2.x, c0.x  // ::phase1Theta<0>

#line 606
    max r2.x, c1.x, r0.w
    rsq r0.w, r2.x  // ::phase2Theta<0>
    rcp r2.x, r2.x
    mul r0.w, r0.w, r2.x
    mul r0.w, r0.w, c187.x  // ::phase2Theta<0>
    mul r2.xyz, r0.w, c186
    mad r2.xyz, c185, r1.w, r2  // calculateScattering::inscattering<0,1,2>
    mul r0.xyz, r0, r2  // calculateScattering::inscattering<0,1,2>
    mul r0.xyz, r0, c183  // calculateScattering::inscattering<0,1,2>

#line 613
    mov r2.y, c188.y  // ::g__scatteringMultiplier<1>
    mul r2.xyz, r2.y, c2
    mul r2.xyz, r2, c180
    mul r0.xyz, r0, r2  // calculateScattering::inscattering<0,1,2>

#line 1158
    texld r2, v0, s11  // ::Ir<0,1,2,3>
    mad_pp oC0.xyz, r2, r1, r0  // ::main<0,1,2>
    mov_pp oC0.w, r2.w  // ::main<3>

// approximately 61 instruction slots used (2 texture, 59 arithmetic)
