//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\MgFP_BinkYCrCbToRGBA.pso
//
//
// Parameters:
//
//   float4 consts;
//   sampler2D tex0;
//   sampler2D tex1;
//   sampler2D tex2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   consts       c3       1
//   tex0         s0       1
//   tex1         s1       1
//   tex2         s2       1
//

    ps_3_0
    def c0, 1.16412354, 1.59579468, -0.87065506, 0
    def c1, 1.16412354, -0.813476563, -0.391448975, 0.529705048
    def c2, 1.16412354, 2.01782227, -1.08166885, 0
    dcl_texcoord v0.xy  // In<0,1>
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2

#line 18 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgFP_BinkYCrCbToRGBA.final"
    texld r0, v0, s1  // ::c<1>

#line 21
    mov r0.y, r0.x

#line 17
    texld r1, v0, s0  // ::c<0>

#line 21
    mov r0.x, r1.x
    mov r0.w, c3.x
    dp3 oC0.x, c0, r0.xyww  // ::main<0>
    texld r1, v0, s2  // ::c<2>

#line 22
    mov r0.z, r1.x
    dp4 oC0.y, c1, r0  // ::main<1>
    dp3 oC0.z, c2, r0.xzww  // ::main<2>
    mov oC0.w, c3.w  // ::main<3>

// approximately 11 instruction slots used (3 texture, 8 arithmetic)
