//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\MgFP_HDR_Bright_Pass_Filter_hwfilter.pso
//
//
// Parameters:
//
//   float4 g__Bloom_Parms;
//   sampler2D g__HDRTex;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g__Bloom_Parms c20      1
//   g__HDRTex      s0       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    def c1, 0.212656006, 0.715157986, 0.0721855983, -0.00999999978
    dcl_texcoord_pp v0.xy  // IN<0,1>
    dcl_2d s0

#line 484 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgFP_HDR_Bright_Pass_Filter_hwfilter.final"
    texld_pp r0, v0, s0  // ::BilinearFilteredTex2D<0,1,2,3>

#line 441
    dp3_pp r1.x, c1, r0  // ::calcLuminance<0>

#line 1144
    add r1.x, r1.x, -c20.x
    cmp r1.x, r1.x, c0.x, c0.y  // ::threshStep<0>
    add r1.y, r0.w, c1.w
    cmp r1.y, r1.y, c0.x, c0.y  // ::alphaStep<0>
    add_sat r1.x, r1.x, r1.y  // ::samplSelect<0>
    mul oC0.xyz, r0, r1.x  // ::main<0,1,2>
    mov_pp oC0.w, r0.w  // ::main<3>

// approximately 9 instruction slots used (1 texture, 8 arithmetic)
