//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\MgFP_HDR_Bright_Pass_Filter_swfilter.pso
//
//
// Parameters:
//
//   float4 g__Bloom_Parms;
//   sampler2D g__HDRTex;
//   float4 g__T0Extents;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g__Bloom_Parms c20      1
//   g__T0Extents   c81      1
//   g__HDRTex      s0       1
//

    ps_3_0
    def c0, -0.5, 0.5, 1, 0
    def c1, 0.212656006, 0.715157986, 0.0721855983, -0.00999999978
    dcl_texcoord_pp v0.xy  // IN<0,1>
    dcl_2d s0

#line 469 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgFP_HDR_Bright_Pass_Filter_swfilter.final"
    mov r0.xy, c0
    mad_pp r0.xz, v0.xyyw, c81.xyyw, r0.x  // ::uvJustified<0,1>
    frc_pp r0.xz, r0  // ::uvRatio<0,1>
    mad_pp r1.zw, c81, -r0.y, v0.xyxy  // ::uvTopLeft<0,1>

#line 474
    texld_pp r2, r1.zwzw, s0  // ::sampl<0,1,2,3>
    mad_pp r1.xy, c81.zwzw, r0.y, v0  // ::uvBottomRight<0,1>

#line 475
    texld_pp r3, r1.xwzw, s0  // ::sampl<4,5,6,7>
    texld_pp r4, r1.zyzw, s0  // ::sampl<8,9,10,11>
    texld_pp r1, r1, s0  // ::sampl<12,13,14,15>
    lrp_pp r5, r0.x, r1, r4
    lrp_pp r1, r0.x, r3, r2
    lrp_pp r2, r0.z, r5, r1  // ::BilinearFilteredTex2DCentered<0,1,2,3>

#line 441
    dp3_pp r0.x, c1, r2  // ::calcLuminance<0>

#line 1144
    add r0.x, r0.x, -c20.x
    cmp r0.x, r0.x, c0.z, c0.w  // ::threshStep<0>
    add r0.y, r2.w, c1.w
    cmp r0.y, r0.y, c0.z, c0.w  // ::alphaStep<0>
    add_sat r0.x, r0.x, r0.y  // ::samplSelect<0>
    mul oC0.xyz, r2, r0.x  // ::main<0,1,2>
    mov_pp oC0.w, r2.w  // ::main<3>

// approximately 20 instruction slots used (4 texture, 16 arithmetic)
