//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /nologo /dumpbin
//    Z:\Modding\ConquestR\Vibe-Reverse-Engineering\rtx_remix_tools\dx\dx9_ffp_template\proxy\Shaders_PC_nvidia\fragment_shaders\MgFPTerrain_Base.pso
//
//
// Parameters:
//
//   sampler2D g__albedoMap;
//   float4 g__ambient;
//   float4 g__ambientCubeMapColor;
//   samplerCUBE g__ambientMap;
//   float4 g__sunCol;
//   float4 g__sunDir;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   g__ambient             c1       1
//   g__sunCol              c2       1
//   g__sunDir              c3       1
//   g__ambientCubeMapColor c72      1
//   g__albedoMap           s0       1
//   g__ambientMap          s6       1
//

    ps_3_0
    def c0, 0, 1, 0, 0
    dcl_color v0  // IN<4,5,6,7>
    dcl_color1 v1.xyz  // IN<8,9,10>
    dcl_normal v2.xyz  // IN<12,13,14>
    dcl_texcoord v3.xy  // IN<15,16>
    dcl_texcoord3 v4.xyz  // IN<19,20,21>
    dcl_2d s0
    dcl_cube s6

#line 344 "d:\Projects\magellan\final_pc\code\libraries\mggraphics\win32\shaders\MgFPTerrain_Base.final"
    nrm_pp r0.xyz, v2  // ::g__vertexNormal<0,1,2>

#line 628
    texld_pp r1, r0, s6  // ::amb<0,1,2>
    dp3_sat_pp r0.w, r0, r0

#line 1122
    dp3_sat_pp r0.x, r0, c3

#line 629
    mul_pp r0.yzw, r1.xxyz, r0.w  // ::amb<0,1,2>
    mul_pp r0.yzw, r0, c1.w  // ::amb<0,1,2>
    mov_pp r1.xyz, c1  // ::g__ambient<0,1,2>
    mad_pp r0.yzw, r0, c72.xxyz, r1.xxyz  // ::amb<0,1,2>

#line 1116
    texld_pp r1, v3, s0  // ::diffuseSampl<0,1,2,3>
    mad r2, v0.w, c0.xxxy, c0.yyyx
    mul_pp r1, r1, r2  // ::diffuseSampl<0,1,2,3>

#line 1123
    mul_pp r0.yzw, r0, r1.xxyz  // ::Qa<0,1,2>
    mul_pp r2.xyz, r0.x, r1  // ::Qd<0,1,2>
    mad_pp r0.xyz, r2, c2, r0.yzww  // ::Ir<0,1,2>
    mad_pp r0.xyz, v4, r1, r0  // ::Ir<0,1,2>

#line 1128
    mov_pp oC0.w, r1.w  // ::main<3>
    mov r1.xyz, v0  // IN<4,5,6>
    mad_pp oC0.xyz, r0, r1, v1  // ::main<0,1,2>

// approximately 20 instruction slots used (2 texture, 18 arithmetic)
